import { getRequiredElement } from "../dom-utils";

export const HUNT_REQUIRED_IDS = [
    "huntTab",
    "huntCaptureCurrentUiBtn",
    "huntCreateFromSavedConfigBtn",
    "huntImportJsonBtn",
    "huntImportFileBtn",
    "huntExportProfilesBtn",
    "huntImportFileInput",
    "huntSavedConfigSelect",
    "huntImportJsonInput",
    "huntImportStatus",
    "huntProfileList",
    "huntProfileEmpty",
    "huntStrategiesToggleAll",
    "huntStrategySearch",
    "huntStrategySelectAll",
    "huntStrategySelectNone",
    "huntStrategyInvertVisible",
    "huntStrategySelectVisible",
    "huntStrategySummary",
    "huntStrategyList",
    "huntPolymarketToggle",
    "huntRunSelectedProfileOnly",
    "huntAdvancedToggle",
    "huntAdvancedSettings",
    "huntPolymarketSettings",
    "huntPolymarketExitMode",
    "huntPolymarketRankMode",
    "huntPolymarketMinScored",
    "huntPolymarketLockOffset",
    "huntPolymarketAfterTakeProfitOnly",
    "huntFreezeRiskManagementToggle",
    "huntTradesToggle",
    "huntTradeFilters",
    "huntTradesMin",
    "huntTradesMax",
    "huntRunBtn",
    "huntCancelBtn",
    "huntProgress",
    "huntProgressFill",
    "huntProgressText",
    "huntCurrentProfileLabel",
    "huntCurrentStrategyLabel",
    "huntProgressCounts",
    "huntStatus",
    "huntViewSurvivors",
    "huntViewPerProfile",
    "huntResultsSummary",
    "huntMessages",
    "huntResultsEmpty",
    "huntSurvivorList",
    "huntPerProfileList",
] as const;

export function createHuntDom() {
    return {
        huntTab: getRequiredElement("huntTab"),
        huntCaptureCurrentUiBtn: getRequiredElement<HTMLButtonElement>("huntCaptureCurrentUiBtn"),
        huntCreateFromSavedConfigBtn: getRequiredElement<HTMLButtonElement>("huntCreateFromSavedConfigBtn"),
        huntImportJsonBtn: getRequiredElement<HTMLButtonElement>("huntImportJsonBtn"),
        huntImportFileBtn: getRequiredElement<HTMLButtonElement>("huntImportFileBtn"),
        huntExportProfilesBtn: getRequiredElement<HTMLButtonElement>("huntExportProfilesBtn"),
        huntImportFileInput: getRequiredElement<HTMLInputElement>("huntImportFileInput"),
        huntSavedConfigSelect: getRequiredElement<HTMLSelectElement>("huntSavedConfigSelect"),
        huntImportJsonInput: getRequiredElement<HTMLTextAreaElement>("huntImportJsonInput"),
        huntImportStatus: getRequiredElement("huntImportStatus"),
        huntProfileList: getRequiredElement<HTMLDivElement>("huntProfileList"),
        huntProfileEmpty: getRequiredElement("huntProfileEmpty"),
        huntStrategiesToggleAll: getRequiredElement<HTMLInputElement>("huntStrategiesToggleAll"),
        huntStrategySearch: getRequiredElement<HTMLInputElement>("huntStrategySearch"),
        huntStrategySelectAll: getRequiredElement<HTMLButtonElement>("huntStrategySelectAll"),
        huntStrategySelectNone: getRequiredElement<HTMLButtonElement>("huntStrategySelectNone"),
        huntStrategyInvertVisible: getRequiredElement<HTMLButtonElement>("huntStrategyInvertVisible"),
        huntStrategySelectVisible: getRequiredElement<HTMLButtonElement>("huntStrategySelectVisible"),
        huntStrategySummary: getRequiredElement("huntStrategySummary"),
        huntStrategyList: getRequiredElement<HTMLDivElement>("huntStrategyList"),
        huntPolymarketToggle: getRequiredElement<HTMLInputElement>("huntPolymarketToggle"),
        huntRunSelectedProfileOnly: getRequiredElement<HTMLInputElement>("huntRunSelectedProfileOnly"),
        huntAdvancedToggle: getRequiredElement<HTMLInputElement>("huntAdvancedToggle"),
        huntAdvancedSettings: getRequiredElement<HTMLDivElement>("huntAdvancedSettings"),
        huntPolymarketSettings: getRequiredElement<HTMLDivElement>("huntPolymarketSettings"),
        huntPolymarketExitMode: getRequiredElement<HTMLSelectElement>("huntPolymarketExitMode"),
        huntPolymarketRankMode: getRequiredElement<HTMLSelectElement>("huntPolymarketRankMode"),
        huntPolymarketMinScored: getRequiredElement<HTMLInputElement>("huntPolymarketMinScored"),
        huntPolymarketLockOffset: getRequiredElement<HTMLInputElement>("huntPolymarketLockOffset"),
        huntPolymarketAfterTakeProfitOnly: getRequiredElement<HTMLInputElement>("huntPolymarketAfterTakeProfitOnly"),
        huntFreezeRiskManagementToggle: getRequiredElement<HTMLInputElement>("huntFreezeRiskManagementToggle"),
        huntTradesToggle: getRequiredElement<HTMLInputElement>("huntTradesToggle"),
        huntTradeFilters: getRequiredElement<HTMLDivElement>("huntTradeFilters"),
        huntTradesMin: getRequiredElement<HTMLInputElement>("huntTradesMin"),
        huntTradesMax: getRequiredElement<HTMLInputElement>("huntTradesMax"),
        huntRunBtn: getRequiredElement<HTMLButtonElement>("huntRunBtn"),
        huntCancelBtn: getRequiredElement<HTMLButtonElement>("huntCancelBtn"),
        huntProgress: getRequiredElement("huntProgress"),
        huntProgressFill: getRequiredElement("huntProgressFill"),
        huntProgressText: getRequiredElement("huntProgressText"),
        huntCurrentProfileLabel: getRequiredElement("huntCurrentProfileLabel"),
        huntCurrentStrategyLabel: getRequiredElement("huntCurrentStrategyLabel"),
        huntProgressCounts: getRequiredElement("huntProgressCounts"),
        huntStatus: getRequiredElement("huntStatus"),
        huntViewSurvivors: getRequiredElement<HTMLButtonElement>("huntViewSurvivors"),
        huntViewPerProfile: getRequiredElement<HTMLButtonElement>("huntViewPerProfile"),
        huntResultsSummary: getRequiredElement("huntResultsSummary"),
        huntMessages: getRequiredElement<HTMLDivElement>("huntMessages"),
        huntResultsEmpty: getRequiredElement("huntResultsEmpty"),
        huntSurvivorList: getRequiredElement<HTMLDivElement>("huntSurvivorList"),
        huntPerProfileList: getRequiredElement<HTMLDivElement>("huntPerProfileList"),
    };
}

export type HuntDom = ReturnType<typeof createHuntDom>;
