import { getOptionalElement, getRequiredElement } from "../dom-utils";
import { ADVANCED_SIZING_DOM_IDS } from "../advanced-sizing-dom";

export const UI_EVENT_HANDLER_REQUIRED_IDS = [
    "symbolSelector",
    "symbolDropdown",
    "themeToggle",
    "strategySelect",
    "strategyTabs",
    "panelContent",
    "runBacktest",
    "clearTradesBtn",
    "togglePanel",
    "strategyPanel",
    "zoomInTool",
    "zoomOutTool",
    "fitTool",
    "riskSettingsToggle",
    "riskSettings",
    "tradeFilterSettingsToggle",
    "tradeFilterSettings",
    "riskMode",
    "takeProfitMode",
    "riskAdvanced",
    "tradeDirection",
    "flipAfterConsecutiveLosses",
    "flipCooldownTrades",
    "minTradesBeforeFirstFlip",
    "tradeFilterMode",
    "htfBiasEmaPeriod",
    "executionTrendEmaPeriod",
    "confirmLookback",
    "trendPersistenceWindow",
    "trendPersistenceMinBars",
    "trendSlopeLookback",
    "trendSlopeMinPercent",
    "volumeSmaPeriod",
    "volumeMultiplier",
    "confirmRsiPeriod",
    "confirmRsiBullish",
    "confirmRsiBearish",
    "strategyTimeframeToggle",
    "strategyTimeframeMinutes",
    "finderTradesToggle",
    "finderTradeFilters",
    "fixedTradeToggle",
    "initialCapitalGroup",
    "fixedTradeGroup",
    "tradeSizingModeGroup",
    "positionSizeGroup",
    "initialCapital",
    "tradeSizingMode",
    "fixedTradeAmount",
    "positionSize",
    "advancedSizingSettingsPanel",
    "kellySettings",
    "volatilityTargetingSettings",
    "riskParitySettings",
    "martingaleSettings",
    "optimalFSettings",
    "kellyFraction",
    "kellyWinRateCap",
    "kellyProfitFactorCap",
    "volTargetAnnual",
    "volLookbackBars",
    "volScalingMethod",
    "riskParityLookback",
    "riskParityMethod",
    "martingaleMultiplier",
    "martingaleMaxSequence",
    "martingaleResetOnWin",
    "martingaleResetOnLoss",
    "martingaleBaseSize",
    "optimalFLookback",
    "optimalFBootstrapSamples",
    "secureFConfidence",
    "secureFMethod",
    "panelResizeHandle",
] as const;

export function createUiEventHandlersDom() {
    return {
        symbolSelector: getRequiredElement("symbolSelector"),
        symbolDropdown: getRequiredElement("symbolDropdown"),
        symbolSearchInput: getOptionalElement<HTMLInputElement>("symbolSearchInput"),
        symbolSearchResults: getOptionalElement("symbolSearchResults"),
        symbolSearchSpinner: getOptionalElement("symbolSearchSpinner"),
        symbolSearchClear: getOptionalElement("symbolSearchClear"),
        symbolSearchLoading: getOptionalElement("symbolSearchLoading"),
        symbolSearchEmpty: getOptionalElement("symbolSearchEmpty"),
        localSp500Select: getOptionalElement<HTMLSelectElement>("localSp500Select"),
        mockModelSelect: getOptionalElement<HTMLSelectElement>("mockModelSelect"),
        mockBarsInput: getOptionalElement<HTMLInputElement>("mockBarsInput"),
        chartModeToggle: getOptionalElement<HTMLButtonElement>("chartModeToggle"),
        chartModeLabel: getOptionalElement("chartModeLabel"),
        timeframeMinutesInput: getOptionalElement<HTMLInputElement>("timeframeMinutesInput"),
        timeframeMinutesApply: getOptionalElement("timeframeMinutesApply"),
        visibleCandlesInput: getOptionalElement<HTMLInputElement>("visibleCandlesInput"),
        visibleCandlesApply: getOptionalElement("visibleCandlesApply"),
        themeToggle: getRequiredElement("themeToggle"),
        strategySelect: getRequiredElement<HTMLSelectElement>("strategySelect"),
        strategyTabs: getRequiredElement("strategyTabs"),
        panelContent: getRequiredElement("panelContent"),
        runBacktest: getRequiredElement("runBacktest"),
        clearTradesBtn: getRequiredElement("clearTradesBtn"),
        togglePanel: getRequiredElement("togglePanel"),
        strategyPanel: getRequiredElement("strategyPanel"),
        zoomInTool: getRequiredElement("zoomInTool"),
        zoomOutTool: getRequiredElement("zoomOutTool"),
        fitTool: getRequiredElement("fitTool"),
        screenshotTool: getOptionalElement("screenshotTool"),
        copyChartBtn: getOptionalElement("copyChartBtn"),
        riskSettingsToggle: getRequiredElement<HTMLInputElement>("riskSettingsToggle"),
        riskSettings: getRequiredElement("riskSettings"),
        tradeFilterSettingsToggle: getRequiredElement<HTMLInputElement>("tradeFilterSettingsToggle"),
        tradeFilterSettings: getRequiredElement("tradeFilterSettings"),
        riskMode: getRequiredElement<HTMLSelectElement>("riskMode"),
        takeProfitMode: getRequiredElement<HTMLSelectElement>("takeProfitMode"),
        riskSimpleAdvanced: getOptionalElement("riskSimpleAdvanced"),
        riskPercentage: getOptionalElement("riskPercentage"),
        riskAdvanced: getRequiredElement("riskAdvanced"),
        tradeDirection: getRequiredElement<HTMLSelectElement>("tradeDirection"),
        flipLossStreakSettingsRow: getOptionalElement("flipLossStreakSettingsRow"),
        flipAfterConsecutiveLosses: getRequiredElement<HTMLInputElement>("flipAfterConsecutiveLosses"),
        flipCooldownTrades: getRequiredElement<HTMLInputElement>("flipCooldownTrades"),
        minTradesBeforeFirstFlip: getRequiredElement<HTMLInputElement>("minTradesBeforeFirstFlip"),
        tradeFilterMode: getRequiredElement<HTMLSelectElement>("tradeFilterMode"),
        htfBiasEmaPeriod: getRequiredElement<HTMLInputElement>("htfBiasEmaPeriod"),
        executionTrendEmaPeriod: getRequiredElement<HTMLInputElement>("executionTrendEmaPeriod"),
        confirmLookback: getRequiredElement<HTMLInputElement>("confirmLookback"),
        trendPersistenceWindow: getRequiredElement<HTMLInputElement>("trendPersistenceWindow"),
        trendPersistenceMinBars: getRequiredElement<HTMLInputElement>("trendPersistenceMinBars"),
        trendSlopeLookback: getRequiredElement<HTMLInputElement>("trendSlopeLookback"),
        trendSlopeMinPercent: getRequiredElement<HTMLInputElement>("trendSlopeMinPercent"),
        volumeSmaPeriod: getRequiredElement<HTMLInputElement>("volumeSmaPeriod"),
        volumeMultiplier: getRequiredElement<HTMLInputElement>("volumeMultiplier"),
        confirmRsiPeriod: getRequiredElement<HTMLInputElement>("confirmRsiPeriod"),
        confirmRsiBullish: getRequiredElement<HTMLInputElement>("confirmRsiBullish"),
        confirmRsiBearish: getRequiredElement<HTMLInputElement>("confirmRsiBearish"),
        strategyTimeframeToggle: getRequiredElement<HTMLInputElement>("strategyTimeframeToggle"),
        strategyTimeframeMinutes: getRequiredElement<HTMLInputElement>("strategyTimeframeMinutes"),
        strategyTimeframeMinutesGroup: getOptionalElement("strategyTimeframeMinutesGroup"),
        twoHourCloseParity: getOptionalElement<HTMLSelectElement>("twoHourCloseParity"),
        finderTradesToggle: getRequiredElement<HTMLInputElement>("finderTradesToggle"),
        finderTradeFilters: getRequiredElement("finderTradeFilters"),
        fixedTradeToggle: getRequiredElement<HTMLInputElement>("fixedTradeToggle"),
        initialCapitalGroup: getRequiredElement("initialCapitalGroup"),
        fixedTradeGroup: getRequiredElement("fixedTradeGroup"),
        tradeSizingModeGroup: getRequiredElement("tradeSizingModeGroup"),
        positionSizeGroup: getRequiredElement("positionSizeGroup"),
        initialCapital: getRequiredElement<HTMLInputElement>("initialCapital"),
        tradeSizingMode: getRequiredElement<HTMLSelectElement>("tradeSizingMode"),
        fixedTradeAmount: getRequiredElement<HTMLInputElement>("fixedTradeAmount"),
        positionSize: getRequiredElement<HTMLInputElement>("positionSize"),
        advancedSizingSettingsPanel: getRequiredElement(ADVANCED_SIZING_DOM_IDS.advancedSizingSettingsPanel),
        kellySettings: getRequiredElement(ADVANCED_SIZING_DOM_IDS.kellySettings),
        volatilityTargetingSettings: getRequiredElement(ADVANCED_SIZING_DOM_IDS.volatilityTargetingSettings),
        riskParitySettings: getRequiredElement(ADVANCED_SIZING_DOM_IDS.riskParitySettings),
        martingaleSettings: getRequiredElement(ADVANCED_SIZING_DOM_IDS.martingaleSettings),
        optimalFSettings: getRequiredElement(ADVANCED_SIZING_DOM_IDS.optimalFSettings),
        kellyFraction: getRequiredElement<HTMLSelectElement>(ADVANCED_SIZING_DOM_IDS.kellyFraction),
        kellyWinRateCap: getRequiredElement<HTMLInputElement>(ADVANCED_SIZING_DOM_IDS.kellyWinRateCap),
        kellyProfitFactorCap: getRequiredElement<HTMLInputElement>(ADVANCED_SIZING_DOM_IDS.kellyProfitFactorCap),
        volTargetAnnual: getRequiredElement<HTMLInputElement>(ADVANCED_SIZING_DOM_IDS.volTargetAnnual),
        volLookbackBars: getRequiredElement<HTMLInputElement>(ADVANCED_SIZING_DOM_IDS.volLookbackBars),
        volScalingMethod: getRequiredElement<HTMLSelectElement>(ADVANCED_SIZING_DOM_IDS.volScalingMethod),
        riskParityLookback: getRequiredElement<HTMLInputElement>(ADVANCED_SIZING_DOM_IDS.riskParityLookback),
        riskParityMethod: getRequiredElement<HTMLSelectElement>(ADVANCED_SIZING_DOM_IDS.riskParityMethod),
        martingaleMultiplier: getRequiredElement<HTMLInputElement>(ADVANCED_SIZING_DOM_IDS.martingaleMultiplier),
        martingaleMaxSequence: getRequiredElement<HTMLInputElement>(ADVANCED_SIZING_DOM_IDS.martingaleMaxSequence),
        martingaleResetOnWin: getRequiredElement<HTMLInputElement>(ADVANCED_SIZING_DOM_IDS.martingaleResetOnWin),
        martingaleResetOnLoss: getRequiredElement<HTMLInputElement>(ADVANCED_SIZING_DOM_IDS.martingaleResetOnLoss),
        martingaleBaseSize: getRequiredElement<HTMLSelectElement>(ADVANCED_SIZING_DOM_IDS.martingaleBaseSize),
        optimalFLookback: getRequiredElement<HTMLInputElement>(ADVANCED_SIZING_DOM_IDS.optimalFLookback),
        optimalFBootstrapSamples: getRequiredElement<HTMLInputElement>(ADVANCED_SIZING_DOM_IDS.optimalFBootstrapSamples),
        secureFConfidence: getRequiredElement<HTMLInputElement>(ADVANCED_SIZING_DOM_IDS.secureFConfidence),
        secureFMethod: getRequiredElement<HTMLSelectElement>(ADVANCED_SIZING_DOM_IDS.secureFMethod),
        panelResizeHandle: getRequiredElement("panelResizeHandle"),
    };
}

export type UiEventHandlersDom = ReturnType<typeof createUiEventHandlersDom>;
