import type { StrategyParams } from "../types/strategies";

// AUTO-GENERATED by `npm run strategies:sync-manifest`.
// Do not manually edit.

export interface BuiltInStrategyMeta {
    key: string;
    name: string;
    description: string;
    defaultParams: StrategyParams;
    paramLabels: Record<string, string>;
    metadata?: {
        role?: string;
        direction?: string;
        walkForwardParams?: string[];
    };
}

export const builtInStrategyMeta: readonly BuiltInStrategyMeta[] = [
    {
        key: "entropy_ratio_regime_alignment",
        name: "Entropy Ratio Regime Alignment",
        description: "Trendable regimes are filtered by a fixed entropy-ratio gate (fast=0, threshold=2) and enter when price aligns with its slow rolling median.",
        defaultParams: {
        slowWindow: 30 } as Record<string, number>,
        paramLabels: {
        slowWindow: "Slow Entropy & Median Window" } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["slowWindow"] },
    },
    {
        key: "adx_skewness_drift",
        name: "ADX Skewness Drift",
        description: "Resolves the primary limitation of ADX - its lack of directionality - by overlaying rolling structural skewness. Defines trading regimes using raw unipolar trend momentum validated by an asymmetrically biased return distribution.",
        defaultParams: {
        adxPeriod: 14,
        adxThresh: 25,
        skewThreshold: 0.5 } as Record<string, number>,
        paramLabels: {
        adxPeriod: "ADX Period",
        adxThresh: "Trend Strength Level",
        skewThreshold: "Asymmetry Boundary" } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["adxPeriod", "adxThresh", "skewThreshold"] },
    },
    {
        key: "wick_responsive_boundary",
        name: "Wick Responsive Boundary",
        description: "A boundary forms where price repeatedly tests but fails to break through wicks. The boundary strength equals test count; break of strong boundary triggers entry.",
        defaultParams: {
		boundary_lookback: 15,
		test_threshold: 3 } as Record<string, number>,
        paramLabels: {
		boundary_lookback: "Boundary Lookback",
		test_threshold: "Test Threshold" } as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["boundary_lookback", "test_threshold"] },
    },
    {
        key: "wick_responsive_boundary_retest",
        name: "Boundary Retest Entry",
        description: "Variant 2: Requires price to retest the boundary after initial tests. More conservative - waits for pullback confirmation.",
        defaultParams: {
		boundary_lookback: 15,
		test_threshold: 3,
		retest_tolerance: 0.01 } as Record<string, number>,
        paramLabels: {
		boundary_lookback: "Boundary Lookback",
		test_threshold: "Test Threshold",
		retest_tolerance: "Retest Tolerance" } as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["boundary_lookback", "test_threshold", "retest_tolerance"] },
    },
    {
        key: "poly_5m_pivot_breakout_entry",
        name: "Poly 5m Pivot Breakout Entry",
        description: "When price breaks through a recent pivot level with momentum, enter in breakout direction. Uses pivot detection with consecutive bar confirmation and rate of change filter.",
        defaultParams: {
		pivotLookback: 12,
		breakoutBars: 2,
		minRoc: 0.15 } as Record<string, number>,
        paramLabels: {
		pivotLookback: "Pivot Lookback",
		breakoutBars: "Breakout Bars",
		minRoc: "Min ROC" } as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["pivotLookback", "breakoutBars", "minRoc"] },
    },
    {
        key: "true_range_ratio_pop_chase",
        name: "True Range Ratio Pop Chase",
        description: "When the current bar's true range is more than a multiple of the prior bar's true range, enter in the close direction.",
        defaultParams: {
		trMult: 1.2,
		minCloseReturn: 0.001 } as Record<string, number>,
        paramLabels: {
		trMult: "True Range Multiplier",
		minCloseReturn: "Min Close Return" } as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["trMult", "minCloseReturn"] },
    },
    {
        key: "probability_boundary_eigen_shift",
        name: "Probability Boundary Eigen-Shift",
        description: "When the typical price (representing the session's Eigenvalue) breaches a 3-sigma boundary of its own rolling state, the local probability density function has failed, forcing violent mean reversion.",
        defaultParams: { stateLookback: 50, eigenLimit: 3.0 } as Record<string, number>,
        paramLabels: { stateLookback: "State Lookback", eigenLimit: "Eigen Limit (Z-Score)" } as Record<string, string>,
        metadata: { role: "entry", direction: "both", walkForwardParams: ["stateLookback", "eigenLimit"] },
    },
    {
        key: "volume_divergent_roc_reversion",
        name: 'Volume Divergent ROC Reversion',
        description: 'Maximizes Sharpe by fading momentum extremes exclusively when the price-volume correlation is heavily negative, indicating a ghost-move unsupported by liquidity.',
        defaultParams: {
    lookback: 20,
    rocExtreme: 3.0,
    corrLimit: -0.6
  } as Record<string, number>,
        paramLabels: {
    lookback: 'Lookback Period',
    rocExtreme: 'ROC Extreme %',
    corrLimit: 'Correlation Limit'
  } as Record<string, string>,
        metadata: {
    role: 'entry',
    direction: 'both',
    walkForwardParams: ['lookback', 'rocExtreme', 'corrLimit']
  },
    },
    {
        key: "wick_imbalance_decay_fade",
        name: 'Wick Imbalance Decay Fade',
        description: 'Models sequential wick rejections as a coiled spring using a cumulative decay sum. When the decayed sum reaches a statistical extreme, the rejection is exhausted.',
        defaultParams: {
		decayRate: 0.75,
		zscoreExtreme: 2.5 } as Record<string, number>,
        paramLabels: {
		decayRate: 'Decay Rate',
		zscoreExtreme: 'Z-Score Extreme' } as Record<string, string>,
        metadata: {
		role: 'entry',
		direction: 'both',
		walkForwardParams: ['decayRate', 'zscoreExtreme'] },
    },
    {
        key: "velocity_percentile_phi_snap",
        name: "Velocity Percentile Phi Snap",
        description: "Identifies synthetic hyper-speed where absolute velocity is at the 99th percentile but path efficiency has collapsed below 0.382, fading the ghost thrust.",
        defaultParams: { velocityWindow: 5, erLookback: 13, phiInefficiency: 0.382 } as Record<string, number>,
        paramLabels: { velocityWindow: "Velocity Window", erLookback: "ER Lookback", phiInefficiency: "Phi Inefficiency" } as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["velocityWindow", "erLookback", "phiInefficiency"] },
    },
    {
        key: "autocorrelation_phi_decay",
        name: "Autocorrelation Phi Decay",
        description: "Applies a 0.618 decay factor to the rolling autocorrelation, creating an infinite-impulse memory of path dependency. Fades when this structural memory reaches a Z-score extreme.",
        defaultParams: { autoCorrLookback: 21, phiDecay: 0.618, zscoreExtreme: 1.618 } as Record<string, number>,
        paramLabels: { autoCorrLookback: "Autocorrelation Lookback", phiDecay: "Phi Decay", zscoreExtreme: "Z-Score Extreme" } as Record<string, string>,
        metadata: { role: "entry", direction: "both", walkForwardParams: ["autoCorrLookback", "phiDecay", "zscoreExtreme"] },
    },
    {
        key: "ichimoku_conversion_base_cross",
        name: 'Ichimoku Conversion-Base Cross',
        description: 'The Ichimoku conversion line (fast midpoint) crossing the base line (slow midpoint) is the core directional signal. The crossover uses two different rolling-midpoint windows, making it a structurally grounded momentum shift detector.',
        defaultParams: { conversionPeriod: 9, basePeriod: 26 } as Record<string, number>,
        paramLabels: { conversionPeriod: 'Conversion Period', basePeriod: 'Base Period' } as Record<string, string>,
        metadata: { role: 'entry', direction: 'both', walkForwardParams: ['conversionPeriod', 'basePeriod'] },
    },
    {
        key: "close_acceptance_streak_reversion",
        name: "Close Acceptance Streak Reversion",
        description: "When close acceptance is high and consistently in one direction for consecutive bars, the market is aggressively accepting one side of every bar. This one-sided acceptance creates a crowded position vulnerable to reversal. Fade the streak.",
        defaultParams: {
		acceptanceThreshold: 0.8,
		streakThreshold: 4 } as Record<string, number>,
        paramLabels: {
		acceptanceThreshold: "Acceptance Threshold",
		streakThreshold: "Streak Threshold" } as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["acceptanceThreshold", "streakThreshold"] },
    },
    {
        key: "entropy_acceleration_transition",
        name: "Entropy Acceleration Transition",
        description: "The rate of change of rolling entropy measures how fast the market's information structure is changing. When entropy ROC crosses from positive to negative, the market transitions from disordering to structuring. Enter in the direction of close versus rolling median.",
        defaultParams: {
		entropyWindow: 20,
		rocPeriod: 5 } as Record<string, number>,
        paramLabels: {
		entropyWindow: "Entropy Window",
		rocPeriod: "ROC Period" } as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["entropyWindow", "rocPeriod"] },
    },
    {
        key: "body_concentration_entropy_squeeze",
        name: "Body Concentration Entropy Squeeze",
        description: "When entropy of body percentage drops to a percentile extreme, bars have become highly predictable in directional commitment - a low-disorder conviction state. Enter in the direction of the rolling average close deviation.",
        defaultParams: {
		entropyWindow: 30,
		compressionRank: 20,
	} as Record<string, number>,
        paramLabels: {
		entropyWindow: "Entropy Window",
		compressionRank: "Compression Rank Max",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["entropyWindow", "compressionRank"],
	},
    },
    {
        key: "close_acceptance_volume_conviction",
        name: "Close Acceptance Volume Conviction",
        description: "When close acceptance reaches an extreme and volume simultaneously confirms with a high percentile rank, the market has produced a high-conviction directional settlement backed by genuine participation. Trade continuation.",
        defaultParams: {
		lookback: 30,
		convictionRank: 85 } as Record<string, number>,
        paramLabels: {
		lookback: "Lookback",
		convictionRank: "Conviction Rank" } as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["lookback", "convictionRank"] },
    },
    {
        key: "euphoria_volume_phi_divergence",
        name: "Euphoria Volume Phi Divergence",
        description: "A correlation between volume and price returns below -0.382 proves smart money is distributing directly into retail demand.",
        defaultParams: {
    corr_lookback: 20,
    phi_correlation: -0.382,
    vol_z_min: 1.5,
  } as Record<string, number>,
        paramLabels: {
    corr_lookback: "Correlation Lookback",
    phi_correlation: "Max Correlation",
    vol_z_min: "Min Volume Z-Score",
  } as Record<string, string>,
        metadata: {
    role: "entry",
    direction: "both",
    walkForwardParams: ["corr_lookback", "phi_correlation", "vol_z_min"],
  },
    },
    {
        key: "panic_skewness_phi_trap",
        name: "Panic Skewness Phi Trap",
        description: "When rolling skewness of returns exceeds structural limit but intraday close acceptance rejects the extreme, emotional sellers are mathematically trapped.",
        defaultParams: {
    skew_lookback: 30,
    phi_skew: 0.382,
    phi_acceptance: 0.382,
  } as Record<string, number>,
        paramLabels: {
    skew_lookback: "Skew Lookback",
    phi_skew: "Phi Skew",
    phi_acceptance: "Phi Acceptance",
  } as Record<string, string>,
        metadata: {
    role: "entry",
    direction: "both",
    walkForwardParams: ["skew_lookback", "phi_skew", "phi_acceptance"],
  },
    },
    {
        key: "weighted_typical_phi_dislocation",
        name: "Weighted Typical Phi Dislocation",
        description: "When the absolute difference between Weighted Close and Typical Price exceeds the golden ratio of True Range, intraday volume distribution has severely dislocated from the median price, creating a microstructure vacuum.",
        defaultParams: {
		atr_lookback: 14,
		phi_dislocation: 0.382 } as Record<string, number>,
        paramLabels: {
		atr_lookback: "ATR Lookback",
		phi_dislocation: "Phi Dislocation" } as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["atr_lookback", "phi_dislocation"] },
    },
    {
        key: "volume_zscore_phi_compression",
        name: "Volume Z-Score Phi Compression",
        description: "High volume effort (Z-score > 1.5) combined with True Range compressed below the golden ratio of the trailing spread proves massive institutional battle lines are drawn inside a coil.",
        defaultParams: {
		lookback: 20,
		vol_z_min: 1.5,
		phi_compression: 0.382 } as Record<string, number>,
        paramLabels: {
		lookback: "Lookback",
		vol_z_min: "Min Volume Z-Score",
		phi_compression: "Phi Compression" } as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["lookback", "vol_z_min", "phi_compression"] },
    },
    {
        key: "initiative_autocorrelation_phi_fade",
        name: "Initiative Autocorrelation Phi Fade",
        description: "When rolling autocorrelation of initiative pressure drops below phi, order flow has lost its memory and entered a random state, favoring mean reversion against the immediate price ROC.",
        defaultParams: {
		flow_lookback: 20,
		phi_memory_limit: 0.382 } as Record<string, number>,
        paramLabels: {
		flow_lookback: "Flow Lookback",
		phi_memory_limit: "Phi Memory Limit" } as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["flow_lookback", "phi_memory_limit"] },
    },
    {
        key: "range_clustering_momentum",
        name: "Range Clustering Momentum",
        description: "When range autocorrelation is high (volatility clustering active), a bar with range above the rolling median indicates a volatility impulse whose body direction predicts continuation.",
        defaultParams: {
		autocorrWindow: 30,
		rangeMedianWindow: 20 } as Record<string, number>,
        paramLabels: {
		autocorrWindow: "Autocorrelation Window",
		rangeMedianWindow: "Range Median Window" } as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["autocorrWindow", "rangeMedianWindow"] },
    },
    {
        key: "pivot_midpoint_anchor_fade",
        name: "Pivot Midpoint Anchor Fade",
        description: "The midpoint between the most recent pivot high and low anchors structural fair value. When price deviates significantly from this anchor, reversion is favored.",
        defaultParams: {
		pivotLeftBars: 5,
		deviationMultiplier: 0.7 } as Record<string, number>,
        paramLabels: {
		pivotLeftBars: "Pivot Bars",
		deviationMultiplier: "Deviation Multiplier" } as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["pivotLeftBars", "deviationMultiplier"] },
    },
    {
        key: "volatility_percentile_reversal",
        name: "Volatility Percentile Reversal",
        description: "When rolling std dev of returns reaches an extreme percentile, the market is in a volatility climax. A two-bar directional reversal within this state confirms the climax has reversed.",
        defaultParams: {
		stdDevWindow: 20,
		percentileWindow: 60 } as Record<string, number>,
        paramLabels: {
		stdDevWindow: "StdDev Window",
		percentileWindow: "Percentile Window" } as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["stdDevWindow", "percentileWindow"] },
    },
    {
        key: "efficiency_phi_micro_streak",
        name: "Efficiency Phi Micro Streak",
        description: "A consecutive streak of bars where path efficiency remains above 0.382 represents an unnatural swept orderbook. Trade the exhaustion fade the moment the streak breaks.",
        defaultParams: {
		er_lookback: 5,
		phi_efficiency: 0.382,
		streak_min: 4,
	} as Record<string, number>,
        paramLabels: {
		er_lookback: "ER Lookback",
		phi_efficiency: "Phi Efficiency",
		streak_min: "Streak Minimum",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["er_lookback", "phi_efficiency", "streak_min"],
	},
    },
    {
        key: "body_proportion_phi_implosion",
        name: "Body Proportion Phi Implosion",
        description: "Sustained median body proportion below 0.382 of true range identifies algorithmic churning; breaking a local extreme launches an unhindered impulse.",
        defaultParams: {
		lookback: 10,
		body_phi_limit: 0.382,
	} as Record<string, number>,
        paramLabels: {
		lookback: "Lookback",
		body_phi_limit: "Body Phi Limit",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["lookback", "body_phi_limit"],
	},
    },
    {
        key: "volume_thrust_phi_correlation",
        name: "Volume Thrust Phi Correlation",
        description: "If rolling correlation between volume and price drops below 0.382 during a high-volume thrust, the move has lost structural participation and is vulnerable to reversion.",
        defaultParams: {
		corr_lookback: 20,
		corr_ceiling: 0.382,
		vol_z_min: 1.5,
	} as Record<string, number>,
        paramLabels: {
		corr_lookback: "Correlation Lookback",
		corr_ceiling: "Correlation Ceiling",
		vol_z_min: "Volume Z Min",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["corr_lookback", "corr_ceiling", "vol_z_min"],
	},
    },
    {
        key: "midpoint_gravity_fade",
        name: "Midpoint Gravity Fade",
        description: "Extreme deviations of the close from the midpoint on high volume quickly revert.",
        defaultParams: {
        dev_z_threshold: 2.0,
        vol_z_min: 1.0
    } as Record<string, number>,
        paramLabels: {
        dev_z_threshold: "Midpoint Deviation Z-Score Threshold",
        vol_z_min: "Minimum Volume Z-Score"
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["dev_z_threshold", "vol_z_min"]
    },
    },
    {
        key: "volume_exhaustion_decay",
        name: "Volume Exhaustion Decay",
        description: "By comparing a fast rolling volume sum to a slow sum, we can mathematically pinpoint the exact bar where a frenzied buying/selling surge completely runs out of participants.",
        defaultParams: {
        fast_vol_window: 3,
        slow_vol_window: 20,
        decay_ratio_threshold: 0.5
    } as Record<string, number>,
        paramLabels: {
        fast_vol_window: "Fast Volume Window",
        slow_vol_window: "Slow Volume Window",
        decay_ratio_threshold: "Decay Ratio Threshold"
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["fast_vol_window", "slow_vol_window", "decay_ratio_threshold"]
    },
    },
    {
        key: "limit_wall_liquidity_vacuum",
        name: "Limit Wall Liquidity Vacuum",
        description: "An abnormally high volume bar with a historically tight true range means a massive limit wall absorbed everything. The resultant liquidity vacuum causes an immediate snapback.",
        defaultParams: {
        z_lookback: 30,
        vol_z_min: 2.0,
        tr_z_max: -1.0
    } as Record<string, number>,
        paramLabels: {
        z_lookback: "Z-Score Lookback",
        vol_z_min: "Minimum Volume Z-Score",
        tr_z_max: "Maximum TR Z-Score (Compression)"
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["z_lookback", "vol_z_min", "tr_z_max"]
    },
    },
    {
        key: "autocorrelation_momentum_divergence",
        name: "Autocorrelation Momentum Divergence",
        description: "If return autocorrelation remains dangerously high (retail perceives a perfect trend), but the raw rate-of-change crosses zero against them, the trend is an illusion running on fumes.",
        defaultParams: {
        auto_lookback: 20,
        auto_min: 0.6,
        roc_lookback: 5
    } as Record<string, number>,
        paramLabels: {
        auto_lookback: "Autocorrelation Lookback",
        auto_min: "Min Autocorrelation",
        roc_lookback: "ROC Lookback"
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["auto_lookback", "auto_min", "roc_lookback"]
    },
    },
    {
        key: "velocity_reversal_shock",
        name: "Velocity Reversal Shock",
        description: "Retail buys short-dated options at peak price velocity. A sudden 5m flip from an extreme momentum Z-score to the opposite direction instantly triggers stop-losses.",
        defaultParams: {
        roc_lookback: 5,
        z_lookback: 30,
        roc_z_extreme: 2.5
    } as Record<string, number>,
        paramLabels: {
        roc_lookback: "ROC Lookback",
        z_lookback: "Z-Score Lookback",
        roc_z_extreme: "ROC Z Extreme"
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["roc_lookback", "z_lookback", "roc_z_extreme"]
    },
    },
    {
        key: "true_range_skewness_initiation",
        name: "True Range Skewness Initiation",
        description: "A sudden spike in the skewness of True Range indicates unilateral directional panic or euphoria initiating a new auction. Volatility asymmetry signals a structural break.",
        defaultParams: {
		skew_window: 20,
		zscore_trigger: 2.0,
	} as Record<string, number>,
        paramLabels: {
		skew_window: "Skewness Window",
		zscore_trigger: "Z-Score Trigger",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["skew_window", "zscore_trigger"],
	},
    },
    {
        key: "body_proportion_entropy_ignition",
        name: "Body Proportion Entropy Ignition",
        description: "A sudden collapse in body percentage entropy means algorithmic execution is printing mechanically identical bars. This ignition signals a systematic move.",
        defaultParams: {
		entropy_window: 10,
		implosion_threshold: -0.4,
	} as Record<string, number>,
        paramLabels: {
		entropy_window: "Entropy Window",
		implosion_threshold: "Implosion Threshold",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["entropy_window", "implosion_threshold"],
	},
    },
    {
        key: "return_skewness_exhaustion_fade",
        name: "Return Skewness Exhaustion Fade",
        description: "A highly skewed distribution of returns indicates unilateral panic. Fading the extreme z-score of this skewness targets the exact moment the one-sided panic runs out of participants.",
        defaultParams: {
		skew_window: 30,
		zscore_threshold: 2.5,
	} as Record<string, number>,
        paramLabels: {
		skew_window: "Skewness Window",
		zscore_threshold: "Z-Score Threshold",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["skew_window", "zscore_threshold"],
	},
    },
    {
        key: "volume_weighted_entropy_ignition",
        name: "Volume Weighted Entropy Ignition",
        description: "Entropy of the volume-weighted close measures the disorder of liquidity. A sudden drop in this entropy means random algorithmic noise has synchronized, igniting directional flow.",
        defaultParams: {
		entropy_window: 6,
		roc_threshold: -0.3,
	} as Record<string, number>,
        paramLabels: {
		entropy_window: "Entropy Window",
		roc_threshold: "Entropy ROC Threshold",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["entropy_window", "roc_threshold"],
	},
    },
    {
        key: "poc_liquidity_rejection_fade",
        name: "POC Liquidity Rejection Fade",
        description: "The Volume Profile Point of Control acts as a high-liquidity magnet. When price touches the POC but suffers immediate, severe close rejection, passive liquidity has completely absorbed the directional attempt.",
        defaultParams: {
		poc_proximity_pct: 0.002,
		rejection_threshold: 0.25,
		profile_period: 30,
		profile_bins: 20,
	} as Record<string, number>,
        paramLabels: {
		poc_proximity_pct: "POC Proximity %",
		rejection_threshold: "Rejection Threshold",
		profile_period: "Profile Period",
		profile_bins: "Profile Bins",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["poc_proximity_pct", "rejection_threshold", "profile_period"],
	},
    },
    {
        key: "initiative_crossing_frequency_chop",
        name: "Initiative Crossing Frequency Chop",
        description: "The frequency of initiative pressure zero-crossings measures flow decisiveness. When crossing frequency drops from high to low, the market has committed to a flow direction. The sign of initiative pressure gives the direction.",
        defaultParams: {
		pressure_lookback: 20,
		count_window: 30,
	} as Record<string, number>,
        paramLabels: {
		pressure_lookback: "Pressure Lookback",
		count_window: "Count Window",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["pressure_lookback", "count_window"],
	},
    },
    {
        key: "relative_strength_mean_reversion",
        name: "Relative Strength Mean Reversion",
        description: "Mean-reversion on the z-score of the relative strength ratio (primary / secondary). When the ratio deviates significantly from its rolling mean, a reversal is expected.",
        defaultParams: {
        lookback: 30,
        zThreshold: 2.0,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
        zThreshold: "Z-Score Threshold",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback", "zThreshold"],
    },
    },
    {
        key: "cross_pressure_initiative_inversion",
        name: "Cross-Pressure Initiative Inversion",
        description: "Signals on z-score extremes of the divergence between primary and secondary initiative pressure. When the primary shows initiative buying while the secondary shows initiative selling, capital is actively rotating.",
        defaultParams: {
        initiativeLookback: 15,
        divergenceLookback: 25,
        zThreshold: 2.0,
    } as Record<string, number>,
        paramLabels: {
        initiativeLookback: "Initiative Lookback",
        divergenceLookback: "Divergence Lookback",
        zThreshold: "Z-Score Threshold",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["initiativeLookback", "divergenceLookback", "zThreshold"],
    },
    },
    {
        key: "dominance_handoff_exhaustion",
        name: "Dominance Handoff Exhaustion",
        description: "Signals when the rate of change of inverse RS (secondary/primary) crosses zero after a sustained dominance run, confirmed by primary close acceptance. Captures BTC-to-alt dominance rotation.",
        defaultParams: {
        dominanceLookback: 20,
        rocLookback: 10,
        acceptanceBuyThreshold: 0.6,
        acceptanceSellThreshold: 0.4,
    } as Record<string, number>,
        paramLabels: {
        dominanceLookback: "Dominance Lookback",
        rocLookback: "ROC Lookback",
        acceptanceBuyThreshold: "Acceptance Buy Threshold",
        acceptanceSellThreshold: "Acceptance Sell Threshold",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["dominanceLookback", "rocLookback", "acceptanceBuyThreshold", "acceptanceSellThreshold"],
    },
    },
    {
        key: "close_location_correlation_break",
        name: "Close Location Correlation Break",
        description: "Signals when close-location correlation between the pair declines (auction quality diverging) while price correlation remains stable — hidden regime break preceding visible price decoupling.",
        defaultParams: {
        lookback: 25,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
    },
    {
        key: "correlation_range_fragmentation",
        name: "Correlation Range Fragmentation",
        description: "Signals when price correlation remains high but range correlation has dropped — volatility structure fragmenting beneath stable directional surface, likely to resolve with range catching up.",
        defaultParams: {
        lookback: 25,
        corrGapThreshold: 0.35,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
        corrGapThreshold: "Correlation Gap Threshold",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback", "corrGapThreshold"],
    },
    },
    {
        key: "correlation_flash_gamma_trigger",
        name: "Correlation Flash Gamma Trigger",
        description: "Signals when rolling pair correlation drops sharply (flash decoupling) with high body pct on the primary bar — a vol-expansion gamma trigger with directional conviction.",
        defaultParams: {
        corrLookback: 10,
        corrDropThreshold: -0.15,
    } as Record<string, number>,
        paramLabels: {
        corrLookback: "Correlation Lookback",
        corrDropThreshold: "Correlation Drop Threshold",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["corrLookback", "corrDropThreshold"],
    },
    },
    {
        key: "volatility_ratio_overextension",
        name: "Volatility Ratio Overextension",
        description: "When short-term volatility spikes far above the baseline ratio and the bar was directional, the volatility overextension created a temporary mispricing. Fade the overextension.",
        defaultParams: {
		fast_window: 5,
		slow_window: 30,
		ratio_threshold: 2.0,
	} as Record<string, number>,
        paramLabels: {
		fast_window: "Fast Window",
		slow_window: "Slow Window",
		ratio_threshold: "Ratio Threshold",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["fast_window", "slow_window", "ratio_threshold"],
	},
    },
    {
        key: "rolling_vwap_center",
        name: "Rolling VWAP Center",
        description: "A rolling window volume-weighted average price represents the capital-weighted consensus. Closes above indicate value acceptance above where capital was most recently deployed.",
        defaultParams: {
		lookback: 20,
	} as Record<string, number>,
        paramLabels: {
		lookback: "Lookback",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["lookback"],
	},
    },
    {
        key: "initiative_pressure_side",
        name: "Initiative Pressure Side",
        description: "Initiative pressure measures whether aggressive takers are buying or selling. Positive pressure indicates buyers lifting offers; negative indicates sellers hitting bids.",
        defaultParams: {
		lookback: 20,
		threshold: 0.0,
	} as Record<string, number>,
        paramLabels: {
		lookback: "Lookback",
		threshold: "Min Pressure Threshold",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["lookback", "threshold"],
	},
    },
    {
        key: "decay_momentum_alignment",
        name: "Decay Momentum Alignment",
        description: "An exponentially decayed cumulative sum of signed bar-to-bar returns creates a smooth, lag-aware momentum reference frame. The decay sum is positive when recent net directional pressure is bullish; negative when bearish. Its sign directly drives entries.",
        defaultParams: {
        decay: 0.92,
        roc_period: 1,
    } as Record<string, number>,
        paramLabels: {
        decay: "Decay Factor",
        roc_period: "ROC Period",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["decay", "roc_period"],
    },
    },
    {
        key: "initiative_pressure_gated_median",
        name: "Initiative Pressure Gated Median",
        description: "Initiative pressure measures whether aggressive participants are buying or selling based on bar geometry. When pressure is positive, buyers are dominant; when negative, sellers are dominant. Align the close with the rolling median only in the direction indicated by initiative pressure.",
        defaultParams: {
        median_lookback: 20,
        pressure_lookback: 10,
    } as Record<string, number>,
        paramLabels: {
        median_lookback: "Median Lookback",
        pressure_lookback: "Pressure Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["median_lookback", "pressure_lookback"],
    },
    },
    {
        key: "roc_percentile_regime",
        name: "ROC Percentile Regime",
        description: "Percentile rank of the current rate of change measures how extreme momentum is relative to recent history. High-percentile ROC indicates unusually strong upward momentum.",
        defaultParams: {
		roc_period: 5,
		lookback: 50,
		upper_pct: 0.7,
		lower_pct: 0.3,
	} as Record<string, number>,
        paramLabels: {
		roc_period: "ROC Period",
		lookback: "Lookback",
		upper_pct: "Upper Percentile",
		lower_pct: "Lower Percentile",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["roc_period", "lookback", "upper_pct", "lower_pct"],
	},
    },
    {
        key: "accumulation_persistence_streak_gate",
        name: "Accumulation Persistence Streak Gate",
        description: "Requires sustained positive or negative Chaikin money flow before allowing price to align with a rolling median, filtering out one-bar accumulation noise.",
        defaultParams: {
        streakReq: 5,
        medianLookback: 20,
    } as Record<string, number>,
        paramLabels: {
        streakReq: "CMF Streak Requirement",
        medianLookback: "Median Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["streakReq", "medianLookback"],
    },
    },
    {
        key: "keltner_halfband_acceptance",
        name: "Keltner Halfband Acceptance",
        description: "Uses a Keltner envelope as a volatility-adjusted value band and enters when settlement is accepted in the outer bullish or bearish half of that same-bar channel.",
        defaultParams: {
        period: 30,
        multiplier: 1.5,
        halfband_frac: 0.5,
    } as Record<string, number>,
        paramLabels: {
        period: "Period",
        multiplier: "Multiplier",
        halfband_frac: "Halfband Fraction",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["period", "multiplier", "halfband_frac"],
    },
    },
    {
        key: "kurtosis_distribution_alignment",
        name: "Kurtosis Distribution Alignment",
        description: "Uses excess kurtosis of daily closes as a higher-moment regime filter and aligns entries with the side of a trailing rolling median only when tails are elevated.",
        defaultParams: {
        lookback: 63,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
    },
    {
        key: "close_location_median_alignment",
        name: "Close Location Median Alignment",
        description: "Combines intrabar close location with a trailing rolling median so entries only align when both same-bar acceptance and multi-week centerline position agree.",
        defaultParams: {
        lookback: 63,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
    },
    {
        key: "typical_price_percentile_alignment",
        name: "Typical Price Percentile Alignment",
        description: "Measures where the current typical price sits inside its own trailing distribution and aligns entries only when that state is already meaningfully high or low.",
        defaultParams: {
        lookback: 63,
        threshold: 65,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
        threshold: "Threshold",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback", "threshold"],
    },
    },
    {
        key: "volatility_regime_median_alignment",
        name: "Volatility Regime Median Alignment",
        description: "Defines volatility regime via percentile rank of trailing standard deviation, then applies median centerline alignment only within the high-volatility regime.",
        defaultParams: {
		lookback: 63,
		vol_threshold: 70 } as Record<string, number>,
        paramLabels: {
		lookback: "Lookback",
		vol_threshold: "Vol Percentile Threshold" } as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["lookback", "vol_threshold"] },
    },
    {
        key: "trailing_boundary_composite",
        name: "Trailing Boundary Composite",
        description: "Combines trailing range-position acceptance and expanding boundary momentum into independent completed-bar boundary signals.",
        defaultParams: {
        boundary_lookback: 126,
        extreme_threshold: 0.85,
    } as Record<string, number>,
        paramLabels: {
        boundary_lookback: "Boundary Lookback",
        extreme_threshold: "Extreme Threshold",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["boundary_lookback", "extreme_threshold"],
    },
    },
    {
        key: "true_range_skew_acceptance",
        name: "True Range Skew Acceptance",
        description: "Trades true-range skew only when the current expanded bar also closes with directional acceptance.",
        defaultParams: {
        lookback: 10,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
    },
    {
        key: "volume_roc_regime_router",
        name: "Volume ROC Regime Router",
        description: "Routes rising volume to median trend alignment and falling volume to value-boundary reversion.",
        defaultParams: {
        volume_lookback: 20,
        regime_threshold: 0,
    } as Record<string, number>,
        paramLabels: {
        volume_lookback: "Volume Lookback",
        regime_threshold: "Regime Threshold",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["volume_lookback", "regime_threshold"],
    },
    },
    {
        key: "atr_range_conviction_follow",
        name: "ATR Range Conviction Follow",
        description: "Trades completed volatility expansion bars only when true range is large versus ATR and the candle settles with strong directional acceptance.",
        defaultParams: {
		atr_period: 14,
		range_atr_min: 1.6,
		acceptance_min: 0.55,
	} as Record<string, number>,
        paramLabels: {
		atr_period: "ATR Period",
		range_atr_min: "Min Range / ATR",
		acceptance_min: "Min Close Acceptance",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["atr_period", "range_atr_min", "acceptance_min"],
	},
    },
];
