import type { Strategy } from "../types/strategies";

// AUTO-GENERATED by `npm run strategies:sync-manifest`.
// Do not manually edit strategy imports or `strategyManifest` entries.

import { entropy_ratio_regime_alignment } from "./lib/entropy_ratio_regime_alignment";
import { adx_skewness_drift } from "./lib/adx_skewness_drift";
import { wick_responsive_boundary } from "./lib/wick_responsive_boundary";
import { wick_responsive_boundary_retest } from "./lib/wick_responsive_boundary_retest";
import { poly_5m_pivot_breakout_entry } from "./lib/poly_5m_pivot_breakout_entry";
import { true_range_ratio_pop_chase } from "./lib/true_range_ratio_pop_chase";
import { probability_boundary_eigen_shift } from "./lib/probability_boundary_eigen_shift";
import { volume_divergent_roc_reversion } from "./lib/volume_divergent_roc_reversion";
import { wick_imbalance_decay_fade } from "./lib/wick_imbalance_decay_fade";
import { velocity_percentile_phi_snap } from "./lib/velocity_percentile_phi_snap";
import { autocorrelation_phi_decay } from "./lib/autocorrelation_phi_decay";
import { ichimoku_conversion_base_cross } from "./lib/ichimoku_conversion_base_cross";
import { close_acceptance_streak_reversion } from "./lib/close_acceptance_streak_reversion";
import { entropy_acceleration_transition } from "./lib/entropy_acceleration_transition";
import { body_concentration_entropy_squeeze } from "./lib/body_concentration_entropy_squeeze";
import { close_acceptance_volume_conviction } from "./lib/close_acceptance_volume_conviction";
import { euphoria_volume_phi_divergence } from "./lib/euphoria_volume_phi_divergence";
import { panic_skewness_phi_trap } from "./lib/panic_skewness_phi_trap";
import { weighted_typical_phi_dislocation } from "./lib/weighted_typical_phi_dislocation";
import { volume_zscore_phi_compression } from "./lib/volume_zscore_phi_compression";
import { initiative_autocorrelation_phi_fade } from "./lib/initiative_autocorrelation_phi_fade";
import { range_clustering_momentum } from "./lib/range_clustering_momentum";
import { pivot_midpoint_anchor_fade } from "./lib/pivot_midpoint_anchor_fade";
import { volatility_percentile_reversal } from "./lib/volatility_percentile_reversal";
import { efficiency_phi_micro_streak } from "./lib/efficiency_phi_micro_streak";
import { body_proportion_phi_implosion } from "./lib/body_proportion_phi_implosion";
import { volume_thrust_phi_correlation } from "./lib/volume_thrust_phi_correlation";
import { midpoint_gravity_fade } from "./lib/midpoint_gravity_fade";
import { volume_exhaustion_decay } from "./lib/volume_exhaustion_decay";
import { limit_wall_liquidity_vacuum } from "./lib/limit_wall_liquidity_vacuum";
import { autocorrelation_momentum_divergence } from "./lib/autocorrelation_momentum_divergence";
import { velocity_reversal_shock } from "./lib/velocity_reversal_shock";
import { true_range_skewness_initiation } from "./lib/true_range_skewness_initiation";
import { body_proportion_entropy_ignition } from "./lib/body_proportion_entropy_ignition";
import { return_skewness_exhaustion_fade } from "./lib/return_skewness_exhaustion_fade";
import { volume_weighted_entropy_ignition } from "./lib/volume_weighted_entropy_ignition";
import { initiative_crossing_frequency_chop } from "./lib/initiative_crossing_frequency_chop";
import { relative_strength_mean_reversion } from "./lib/relative_strength_mean_reversion";
import { cross_pressure_initiative_inversion } from "./lib/cross_pressure_initiative_inversion";
import { dominance_handoff_exhaustion } from "./lib/dominance_handoff_exhaustion";
import { close_location_correlation_break } from "./lib/close_location_correlation_break";
import { correlation_range_fragmentation } from "./lib/correlation_range_fragmentation";
import { correlation_flash_gamma_trigger } from "./lib/correlation_flash_gamma_trigger";
import { rolling_vwap_center } from "./lib/rolling_vwap_center";
import { initiative_pressure_side } from "./lib/initiative_pressure_side";
import { decay_momentum_alignment } from "./lib/decay_momentum_alignment";
import { initiative_pressure_gated_median } from "./lib/initiative_pressure_gated_median";
import { roc_percentile_regime } from "./lib/roc_percentile_regime";
import { accumulation_persistence_streak_gate } from "./lib/accumulation_persistence_streak_gate";
import { keltner_halfband_acceptance } from "./lib/keltner_halfband_acceptance";
import { close_location_median_alignment } from "./lib/close_location_median_alignment";
import { typical_price_percentile_alignment } from "./lib/typical_price_percentile_alignment__20260429T162454Z";
import { volatility_regime_median_alignment } from "./lib/volatility_regime_median_alignment__20260429T162454Z";
import { trailing_boundary_composite } from "./lib/trailing_boundary_composite";
import { true_range_skew_acceptance } from "./lib/true_range_skew_acceptance";
import { volume_roc_regime_router } from "./lib/volume_roc_regime_router";
import { atr_range_conviction_follow } from "./lib/atr_range_conviction_follow";
import { cmf_pressure_alignment } from "./lib/cmf_pressure_alignment";
import { keltner_boundary_pressure_gap } from "./lib/keltner_boundary_pressure_gap";
import { weighted_price_roc_veto } from "./lib/weighted_price_roc_veto";
import { micro_level_ping_adverse_veto } from "./lib/micro_level_ping_adverse_veto";
import { chop_breakout_adverse_veto } from "./lib/chop_breakout_adverse_veto";
import { efficiency_median_adverse_veto } from "./lib/efficiency_median_adverse_veto";
import { acceptance_flash_crash } from "./lib/acceptance_flash_crash";
import { golden_conjugate_initiative_trend } from "./lib/golden_conjugate_initiative_trend";
import { golden_initiative_quorum } from "./lib/golden_initiative_quorum";
import { golden_squeeze_rotation_composite } from "./lib/golden_squeeze_rotation_composite";
import { width_compression_golden_breakout } from "./lib/width_compression_golden_breakout";
import { acceptance_sourced_momentum_quorum } from "./lib/acceptance_sourced_momentum_quorum";
import { structural_rotation_shock } from "./lib/structural_rotation_shock";
import { width_expansion_zscore_router } from "./lib/width_expansion_zscore_router";
import { efficiency_keltner_router } from "./lib/efficiency_keltner_router";
import { polymarket_event_direction_follow } from "./lib/polymarket_event_direction_follow";
import { polymarket_fair_value_mispricing } from "./lib/polymarket_fair_value_mispricing";
import { polymarket_fair_value_catchup_scalper } from "./lib/polymarket_fair_value_catchup_scalper";
import { polymarket_event_direction_gamma_skew_filter } from "./lib/polymarket_event_direction_gamma_skew_filter";
import { close_acceptance_streak_ignition } from "./lib/close_acceptance_streak_ignition";
import { rolling_distribution_asymmetry_alignment } from "./lib/rolling_distribution_asymmetry_alignment";
import { entropy_volume_gated_no_adverse } from "./lib/entropy_volume_gated_no_adverse";
import { micro_wick_exhaustion_executable_agreement } from "./lib/micro_wick_exhaustion_executable_agreement";
import { midpoint_deviation_no_adverse } from "./lib/midpoint_deviation_no_adverse";
import { price_volume_correlation_break_gamma } from "./lib/price_volume_correlation_break_gamma";
import { volume_skewness_acceleration_no_adverse } from "./lib/volume_skewness_acceleration_no_adverse";
import { vw_typical_dispersion_no_adverse } from "./lib/vw_typical_dispersion_no_adverse";
import { event_direction_1s } from "./lib/event_direction_1s";
import { cumulative_return_zscore_reversion } from "./lib/cumulative_return_zscore_reversion";
import { range_expansion_exhaustion_reversion } from "./lib/range_expansion_exhaustion_reversion";
import { acceptance_deviation_median_reversion } from "./lib/acceptance_deviation_median_reversion";
import { negative_autocorrelation_median_reversion } from "./lib/negative_autocorrelation_median_reversion";
import { cumulative_return_percentile_reversion } from "./lib/cumulative_return_percentile_reversion";
import { decay_pressure_percentile_reversion } from "./lib/decay_pressure_percentile_reversion";
import { volatility_breakout_follow } from "./lib/volatility_breakout_follow";
import { initiative_pressure_acceleration_follow } from "./lib/initiative_pressure_acceleration_follow";

export interface StrategyManifestEntry {
    key: string;
    strategy: Strategy;
    assets?: string[];
}

export const strategyManifest: readonly StrategyManifestEntry[] = [
    { key: "entropy_ratio_regime_alignment", strategy: entropy_ratio_regime_alignment },
    { key: "adx_skewness_drift", strategy: adx_skewness_drift },
    { key: "wick_responsive_boundary", strategy: wick_responsive_boundary },
    { key: "wick_responsive_boundary_retest", strategy: wick_responsive_boundary_retest },
    { key: "poly_5m_pivot_breakout_entry", strategy: poly_5m_pivot_breakout_entry },
    { key: "true_range_ratio_pop_chase", strategy: true_range_ratio_pop_chase },
    { key: "probability_boundary_eigen_shift", strategy: probability_boundary_eigen_shift },
    { key: "volume_divergent_roc_reversion", strategy: volume_divergent_roc_reversion },
    { key: "wick_imbalance_decay_fade", strategy: wick_imbalance_decay_fade },
    { key: "velocity_percentile_phi_snap", strategy: velocity_percentile_phi_snap },
    { key: "autocorrelation_phi_decay", strategy: autocorrelation_phi_decay },
    { key: "ichimoku_conversion_base_cross", strategy: ichimoku_conversion_base_cross },
    { key: "close_acceptance_streak_reversion", strategy: close_acceptance_streak_reversion },
    { key: "entropy_acceleration_transition", strategy: entropy_acceleration_transition },
    { key: "body_concentration_entropy_squeeze", strategy: body_concentration_entropy_squeeze },
    { key: "close_acceptance_volume_conviction", strategy: close_acceptance_volume_conviction },
    { key: "euphoria_volume_phi_divergence", strategy: euphoria_volume_phi_divergence },
    { key: "panic_skewness_phi_trap", strategy: panic_skewness_phi_trap },
    { key: "weighted_typical_phi_dislocation", strategy: weighted_typical_phi_dislocation },
    { key: "volume_zscore_phi_compression", strategy: volume_zscore_phi_compression },
    { key: "initiative_autocorrelation_phi_fade", strategy: initiative_autocorrelation_phi_fade },
    { key: "range_clustering_momentum", strategy: range_clustering_momentum },
    { key: "pivot_midpoint_anchor_fade", strategy: pivot_midpoint_anchor_fade },
    { key: "volatility_percentile_reversal", strategy: volatility_percentile_reversal },
    { key: "efficiency_phi_micro_streak", strategy: efficiency_phi_micro_streak },
    { key: "body_proportion_phi_implosion", strategy: body_proportion_phi_implosion },
    { key: "volume_thrust_phi_correlation", strategy: volume_thrust_phi_correlation },
    { key: "midpoint_gravity_fade", strategy: midpoint_gravity_fade },
    { key: "volume_exhaustion_decay", strategy: volume_exhaustion_decay },
    { key: "limit_wall_liquidity_vacuum", strategy: limit_wall_liquidity_vacuum },
    { key: "autocorrelation_momentum_divergence", strategy: autocorrelation_momentum_divergence },
    { key: "velocity_reversal_shock", strategy: velocity_reversal_shock },
    { key: "true_range_skewness_initiation", strategy: true_range_skewness_initiation },
    { key: "body_proportion_entropy_ignition", strategy: body_proportion_entropy_ignition },
    { key: "return_skewness_exhaustion_fade", strategy: return_skewness_exhaustion_fade },
    { key: "volume_weighted_entropy_ignition", strategy: volume_weighted_entropy_ignition },
    { key: "initiative_crossing_frequency_chop", strategy: initiative_crossing_frequency_chop },
    { key: "relative_strength_mean_reversion", strategy: relative_strength_mean_reversion },
    { key: "cross_pressure_initiative_inversion", strategy: cross_pressure_initiative_inversion },
    { key: "dominance_handoff_exhaustion", strategy: dominance_handoff_exhaustion },
    { key: "close_location_correlation_break", strategy: close_location_correlation_break },
    { key: "correlation_range_fragmentation", strategy: correlation_range_fragmentation },
    { key: "correlation_flash_gamma_trigger", strategy: correlation_flash_gamma_trigger },
    { key: "rolling_vwap_center", strategy: rolling_vwap_center },
    { key: "initiative_pressure_side", strategy: initiative_pressure_side },
    { key: "decay_momentum_alignment", strategy: decay_momentum_alignment },
    { key: "initiative_pressure_gated_median", strategy: initiative_pressure_gated_median },
    { key: "roc_percentile_regime", strategy: roc_percentile_regime },
    { key: "accumulation_persistence_streak_gate", strategy: accumulation_persistence_streak_gate },
    { key: "keltner_halfband_acceptance", strategy: keltner_halfband_acceptance },
    { key: "close_location_median_alignment", strategy: close_location_median_alignment },
    { key: "typical_price_percentile_alignment", strategy: typical_price_percentile_alignment },
    { key: "volatility_regime_median_alignment", strategy: volatility_regime_median_alignment },
    { key: "trailing_boundary_composite", strategy: trailing_boundary_composite },
    { key: "true_range_skew_acceptance", strategy: true_range_skew_acceptance },
    { key: "volume_roc_regime_router", strategy: volume_roc_regime_router },
    { key: "atr_range_conviction_follow", strategy: atr_range_conviction_follow },
    { key: "cmf_pressure_alignment", strategy: cmf_pressure_alignment },
    { key: "keltner_boundary_pressure_gap", strategy: keltner_boundary_pressure_gap },
    { key: "weighted_price_roc_veto", strategy: weighted_price_roc_veto },
    { key: "micro_level_ping_adverse_veto", strategy: micro_level_ping_adverse_veto },
    { key: "chop_breakout_adverse_veto", strategy: chop_breakout_adverse_veto },
    { key: "efficiency_median_adverse_veto", strategy: efficiency_median_adverse_veto },
    { key: "acceptance_flash_crash", strategy: acceptance_flash_crash },
    { key: "golden_conjugate_initiative_trend", strategy: golden_conjugate_initiative_trend },
    { key: "golden_initiative_quorum", strategy: golden_initiative_quorum },
    { key: "golden_squeeze_rotation_composite", strategy: golden_squeeze_rotation_composite },
    { key: "width_compression_golden_breakout", strategy: width_compression_golden_breakout },
    { key: "acceptance_sourced_momentum_quorum", strategy: acceptance_sourced_momentum_quorum },
    { key: "structural_rotation_shock", strategy: structural_rotation_shock },
    { key: "width_expansion_zscore_router", strategy: width_expansion_zscore_router },
    { key: "efficiency_keltner_router", strategy: efficiency_keltner_router },
    { key: "polymarket_event_direction_follow", strategy: polymarket_event_direction_follow },
    { key: "polymarket_fair_value_mispricing", strategy: polymarket_fair_value_mispricing },
    { key: "polymarket_fair_value_catchup_scalper", strategy: polymarket_fair_value_catchup_scalper },
    { key: "polymarket_event_direction_gamma_skew_filter", strategy: polymarket_event_direction_gamma_skew_filter },
    { key: "close_acceptance_streak_ignition", strategy: close_acceptance_streak_ignition },
    { key: "rolling_distribution_asymmetry_alignment", strategy: rolling_distribution_asymmetry_alignment },
    { key: "entropy_volume_gated_no_adverse", strategy: entropy_volume_gated_no_adverse },
    { key: "micro_wick_exhaustion_executable_agreement", strategy: micro_wick_exhaustion_executable_agreement },
    { key: "midpoint_deviation_no_adverse", strategy: midpoint_deviation_no_adverse },
    { key: "price_volume_correlation_break_gamma", strategy: price_volume_correlation_break_gamma },
    { key: "volume_skewness_acceleration_no_adverse", strategy: volume_skewness_acceleration_no_adverse },
    { key: "vw_typical_dispersion_no_adverse", strategy: vw_typical_dispersion_no_adverse },
    { key: "event_direction_1s", strategy: event_direction_1s },
    { key: "cumulative_return_zscore_reversion", strategy: cumulative_return_zscore_reversion },
    { key: "range_expansion_exhaustion_reversion", strategy: range_expansion_exhaustion_reversion },
    { key: "acceptance_deviation_median_reversion", strategy: acceptance_deviation_median_reversion },
    { key: "negative_autocorrelation_median_reversion", strategy: negative_autocorrelation_median_reversion },
    { key: "cumulative_return_percentile_reversion", strategy: cumulative_return_percentile_reversion },
    { key: "decay_pressure_percentile_reversion", strategy: decay_pressure_percentile_reversion },
    { key: "volatility_breakout_follow", strategy: volatility_breakout_follow },
    { key: "initiative_pressure_acceleration_follow", strategy: initiative_pressure_acceleration_follow },
];

export function createStrategiesRecordFromManifest(
    manifest: readonly StrategyManifestEntry[] = strategyManifest
): Record<string, Strategy> {
    const strategies: Record<string, Strategy> = {};

    for (const entry of manifest) {
        if (entry.key in strategies) {
            throw new Error(`Duplicate strategy key in manifest: ${entry.key}`);
        }
        strategies[entry.key] = entry.strategy;
    }

    return strategies;
}
