import type { Strategy } from "../types/strategies";

// AUTO-GENERATED by `npm run strategies:sync-manifest`.
// Do not manually edit strategy imports or `strategyManifest` entries.

import { entropy_ratio_regime_alignment } from "./lib/entropy_ratio_regime_alignment";
import { wick_responsive_boundary_retest } from "./lib/wick_responsive_boundary_retest";
import { probability_boundary_eigen_shift } from "./lib/probability_boundary_eigen_shift";
import { pivot_midpoint_anchor_fade } from "./lib/pivot_midpoint_anchor_fade";
import { true_range_skewness_initiation } from "./lib/true_range_skewness_initiation";
import { true_range_skew_acceptance } from "./lib/true_range_skew_acceptance";
import { efficiency_keltner_router } from "./lib/efficiency_keltner_router";
import { cumulative_return_zscore_reversion } from "./lib/cumulative_return_zscore_reversion";
import { cumulative_return_percentile_reversion } from "./lib/cumulative_return_percentile_reversion";
import { body_proportion_percentile_fade } from "./lib/body_proportion_percentile_fade";
import { return_sign_streak_fade } from "./lib/return_sign_streak_fade";
import { close_location_gradient_acceleration } from "./lib/close_location_gradient_acceleration";
import { modern_arbitrage_speed_reversion } from "./lib/modern_arbitrage_speed_reversion";
import { ema_confirmation } from "./lib/ema_confirmation";
import { typical_close_skewness_acceptance } from "./lib/typical_close_skewness_acceptance";
import { kelly_streak_exhaustion_reversion } from "./lib/kelly_streak_exhaustion_reversion";
import { dmi_direction_confirmation } from "./lib/dmi_direction_confirmation";
import { parabolic_sar_confirmation } from "./lib/parabolic_sar_confirmation";
import { dema_confirmation } from "./lib/dema_confirmation";
import { donchian_midpoint_confirmation } from "./lib/donchian_midpoint_confirmation";
import { mcginley_dynamic_confirmation } from "./lib/mcginley_dynamic_confirmation";
import { n_bar_momentum_confirmation } from "./lib/n_bar_momentum_confirmation";
import { rolling_median_confirmation } from "./lib/rolling_median_confirmation";
import { typical_price_ema_confirmation } from "./lib/typical_price_ema_confirmation";
import { volume_weighted_median_confirmation } from "./lib/volume_weighted_median_confirmation";
import { wilder_ma_confirmation } from "./lib/wilder_ma_confirmation";
import { zero_lag_ema_confirmation } from "./lib/zero_lag_ema_confirmation";
import { body_direction_placement_coherence } from "./lib/body_direction_placement_coherence";
import { nested_bar_oscillation_fade } from "./lib/nested_bar_oscillation_fade";

export interface StrategyManifestEntry {
    key: string;
    strategy: Strategy;
    assets?: string[];
}

export const strategyManifest: readonly StrategyManifestEntry[] = [
    { key: "entropy_ratio_regime_alignment", strategy: entropy_ratio_regime_alignment },
    { key: "wick_responsive_boundary_retest", strategy: wick_responsive_boundary_retest },
    { key: "probability_boundary_eigen_shift", strategy: probability_boundary_eigen_shift },
    { key: "pivot_midpoint_anchor_fade", strategy: pivot_midpoint_anchor_fade },
    { key: "true_range_skewness_initiation", strategy: true_range_skewness_initiation },
    { key: "true_range_skew_acceptance", strategy: true_range_skew_acceptance },
    { key: "efficiency_keltner_router", strategy: efficiency_keltner_router },
    { key: "cumulative_return_zscore_reversion", strategy: cumulative_return_zscore_reversion },
    { key: "cumulative_return_percentile_reversion", strategy: cumulative_return_percentile_reversion },
    { key: "body_proportion_percentile_fade", strategy: body_proportion_percentile_fade },
    { key: "return_sign_streak_fade", strategy: return_sign_streak_fade },
    { key: "close_location_gradient_acceleration", strategy: close_location_gradient_acceleration },
    { key: "modern_arbitrage_speed_reversion", strategy: modern_arbitrage_speed_reversion },
    { key: "ema_confirmation", strategy: ema_confirmation },
    { key: "typical_close_skewness_acceptance", strategy: typical_close_skewness_acceptance },
    { key: "kelly_streak_exhaustion_reversion", strategy: kelly_streak_exhaustion_reversion },
    { key: "dmi_direction_confirmation", strategy: dmi_direction_confirmation },
    { key: "parabolic_sar_confirmation", strategy: parabolic_sar_confirmation },
    { key: "dema_confirmation", strategy: dema_confirmation },
    { key: "donchian_midpoint_confirmation", strategy: donchian_midpoint_confirmation },
    { key: "mcginley_dynamic_confirmation", strategy: mcginley_dynamic_confirmation },
    { key: "n_bar_momentum_confirmation", strategy: n_bar_momentum_confirmation },
    { key: "rolling_median_confirmation", strategy: rolling_median_confirmation },
    { key: "typical_price_ema_confirmation", strategy: typical_price_ema_confirmation },
    { key: "volume_weighted_median_confirmation", strategy: volume_weighted_median_confirmation },
    { key: "wilder_ma_confirmation", strategy: wilder_ma_confirmation },
    { key: "zero_lag_ema_confirmation", strategy: zero_lag_ema_confirmation },
    { key: "body_direction_placement_coherence", strategy: body_direction_placement_coherence },
    { key: "nested_bar_oscillation_fade", strategy: nested_bar_oscillation_fade },
];

export function createStrategiesRecordFromManifest(
    manifest: readonly StrategyManifestEntry[] = strategyManifest
): Record<string, Strategy> {
    const strategies: Record<string, Strategy> = {};

    for (const entry of manifest) {
        if (entry.key in strategies) {
            throw new Error(`Duplicate strategy key in manifest: ${entry.key}`);
        }
        strategies[entry.key] = entry.strategy;
    }

    return strategies;
}
