import type { Strategy } from "../types/strategies";

// AUTO-GENERATED by `npm run strategies:sync-manifest`.
// Do not manually edit strategy imports or `strategyManifest` entries.

import { keltner_channel_streak_squeeze } from "./lib/keltner_channel_streak_squeeze";
import { fractal_wick_barrier_engulfing } from "./lib/fractal_wick_barrier_engulfing";
import { median_deviation_streak } from "./lib/median_deviation_streak";
import { median_deviation_streak_v7 } from "./lib/median_deviation_streak_v7";
import { skew_entropy_polarization_entry } from "./lib/skew_entropy_polarization_entry";
import { entropy_ratio_regime_alignment } from "./lib/entropy_ratio_regime_alignment";
import { pattern_regime_alignment } from "./lib/pattern_regime_alignment";
import { value_area_median_shift } from "./lib/value_area_median_shift";
import { supertrend_friction_pinch } from "./lib/supertrend_friction_pinch";
import { candle_pattern_persistence_score } from "./lib/candle-pattern-persistence-score";
import { candle_pattern_persistence_score_stoch_mid } from "./lib/candle-pattern-persistence-score-stoch-mid";
import { candle_pattern_persistence_score_median_deviation_streak } from "./lib/candle-pattern-persistence-score-median-deviation-streak";
import { efficiency_ratio_pinch_trigger } from "./lib/efficiency_ratio_pinch_trigger";
import { dead_zone_efficiency_breakout } from "./lib/dead_zone_efficiency_breakout";
import { fractal_volatility_pinch_impulse } from "./lib/fractal_volatility_pinch_impulse";
import { crossing_persistence_event_regime } from "./lib/crossing_persistence_event_regime";
import { efficiency_pinch_roc_breakout } from "./lib/efficiency_pinch_roc_breakout";
import { cumulative_decay_regime_filter } from "./lib/cumulative_decay_regime_filter";
import { skewness_deadzone_break } from "./lib/skewness_deadzone_break";
import { crossing_churn_suppression } from "./lib/crossing_churn_suppression";
import { vwap_zscore_reversion } from "./lib/vwap_zscore_reversion";
import { supertrend_churn_resilience } from "./lib/supertrend_churn_resilience";
import { adx_skewness_drift } from "./lib/adx_skewness_drift";
import { macd_signal_pinch_explosion } from "./lib/macd_signal_pinch_explosion";
import { bollinger_skewness_ride } from "./lib/bollinger_skewness_ride";
import { supertrend_distance_zscore } from "./lib/supertrend_distance_zscore";
import { rsi_volatility_pinch_pop } from "./lib/rsi_volatility_pinch_pop";
import { volume_profile_poc_median_shift } from "./lib/volume_profile_poc_median_shift";
import { absorptive_wick_volume_spike } from "./lib/absorptive_wick_volume_spike";
import { noisy_wick_fade_reversion } from "./lib/noisy_wick_fade_reversion";
import { micro_shock_retrace_scalp } from "./lib/micro_shock_retrace_scalp";
import { keltner_pinch_momentum_break } from "./lib/keltner_pinch_momentum_break";
import { percentile_rank_deadzone_launch } from "./lib/percentile_rank_deadzone_launch";
import { zscore_kurtosis_regime } from "./lib/zscore_kurtosis_regime";
import { zscore_false_break } from "./lib/zscore_false_break";
import { close_percentile_range_entry } from "./lib/close_percentile_range_entry";
import { wick_responsive_boundary } from "./lib/wick_responsive_boundary";
import { wick_responsive_boundary_retest } from "./lib/wick_responsive_boundary_retest";
import { deadzone_orb_asymmetric_long } from "./lib/deadzone_orb_asymmetric_long";
import { deadzone_orb_asymmetric_short } from "./lib/deadzone_orb_asymmetric_short";
import { deadzone_consecutive_closes } from "./lib/deadzone_consecutive_closes";
import { poly_5m_cumulative_decay_momentum } from "./lib/poly_5m_cumulative_decay_momentum";
import { poly_5m_pivot_breakout_entry } from "./lib/poly_5m_pivot_breakout_entry";
import { midpoint_streak_breakout } from "./lib/midpoint_streak_breakout";
import { close_location_oscillator_extremes } from "./lib/close_location_oscillator_extremes";
import { efficiency_ratio_implosion } from "./lib/efficiency_ratio_implosion";
import { single_bar_roc_snapback } from "./lib/single_bar_roc_snapback";
import { volume_thrust_zscore_continuation } from "./lib/volume_thrust_zscore_continuation";
import { asymmetric_trailing_pullback } from "./lib/asymmetric_trailing_pullback";
import { ema_distance_efficiency_snapback } from "./lib/ema_distance_efficiency_snapback";
import { typical_price_vwap_distance_zscore } from "./lib/typical_price_vwap_distance_zscore";
import { vwap_distance_zscore_fade } from "./lib/vwap_distance_zscore_fade";
import { typical_price_zscore_reversion } from "./lib/typical_price_zscore_reversion";
import { supertrend_extreme_overextension_fade } from "./lib/supertrend_extreme_overextension_fade";
import { true_range_ratio_pop_chase } from "./lib/true_range_ratio_pop_chase";
import { ema_touch_continuation } from "./lib/ema_touch_continuation";
import { sma_slope_micro_chase } from "./lib/sma_slope_micro_chase";

export interface StrategyManifestEntry {
    key: string;
    strategy: Strategy;
    assets?: string[];
}

export const strategyManifest: readonly StrategyManifestEntry[] = [
    { key: "keltner_channel_streak_squeeze", strategy: keltner_channel_streak_squeeze },
    { key: "fractal_wick_barrier_engulfing", strategy: fractal_wick_barrier_engulfing },
    { key: "median_deviation_streak", strategy: median_deviation_streak },
    { key: "median_deviation_streak_v7", strategy: median_deviation_streak_v7 },
    { key: "skew_entropy_polarization_entry", strategy: skew_entropy_polarization_entry },
    { key: "entropy_ratio_regime_alignment", strategy: entropy_ratio_regime_alignment },
    { key: "pattern_regime_alignment", strategy: pattern_regime_alignment },
    { key: "value_area_median_shift", strategy: value_area_median_shift },
    { key: "supertrend_friction_pinch", strategy: supertrend_friction_pinch },
    { key: "candle_pattern_persistence_score", strategy: candle_pattern_persistence_score },
    { key: "candle_pattern_persistence_score_stoch_mid", strategy: candle_pattern_persistence_score_stoch_mid },
    { key: "candle_pattern_persistence_score_median_deviation_streak", strategy: candle_pattern_persistence_score_median_deviation_streak },
    { key: "efficiency_ratio_pinch_trigger", strategy: efficiency_ratio_pinch_trigger },
    { key: "dead_zone_efficiency_breakout", strategy: dead_zone_efficiency_breakout },
    { key: "fractal_volatility_pinch_impulse", strategy: fractal_volatility_pinch_impulse },
    { key: "crossing_persistence_event_regime", strategy: crossing_persistence_event_regime },
    { key: "efficiency_pinch_roc_breakout", strategy: efficiency_pinch_roc_breakout },
    { key: "cumulative_decay_regime_filter", strategy: cumulative_decay_regime_filter },
    { key: "skewness_deadzone_break", strategy: skewness_deadzone_break },
    { key: "crossing_churn_suppression", strategy: crossing_churn_suppression },
    { key: "vwap_zscore_reversion", strategy: vwap_zscore_reversion },
    { key: "supertrend_churn_resilience", strategy: supertrend_churn_resilience },
    { key: "adx_skewness_drift", strategy: adx_skewness_drift },
    { key: "macd_signal_pinch_explosion", strategy: macd_signal_pinch_explosion },
    { key: "bollinger_skewness_ride", strategy: bollinger_skewness_ride },
    { key: "supertrend_distance_zscore", strategy: supertrend_distance_zscore },
    { key: "rsi_volatility_pinch_pop", strategy: rsi_volatility_pinch_pop },
    { key: "volume_profile_poc_median_shift", strategy: volume_profile_poc_median_shift },
    { key: "absorptive_wick_volume_spike", strategy: absorptive_wick_volume_spike },
    { key: "noisy_wick_fade_reversion", strategy: noisy_wick_fade_reversion },
    { key: "micro_shock_retrace_scalp", strategy: micro_shock_retrace_scalp },
    { key: "keltner_pinch_momentum_break", strategy: keltner_pinch_momentum_break },
    { key: "percentile_rank_deadzone_launch", strategy: percentile_rank_deadzone_launch },
    { key: "zscore_kurtosis_regime", strategy: zscore_kurtosis_regime },
    { key: "zscore_false_break", strategy: zscore_false_break },
    { key: "close_percentile_range_entry", strategy: close_percentile_range_entry },
    { key: "wick_responsive_boundary", strategy: wick_responsive_boundary },
    { key: "wick_responsive_boundary_retest", strategy: wick_responsive_boundary_retest },
    { key: "deadzone_orb_asymmetric_long", strategy: deadzone_orb_asymmetric_long },
    { key: "deadzone_orb_asymmetric_short", strategy: deadzone_orb_asymmetric_short },
    { key: "deadzone_consecutive_closes", strategy: deadzone_consecutive_closes },
    { key: "poly_5m_cumulative_decay_momentum", strategy: poly_5m_cumulative_decay_momentum },
    { key: "poly_5m_pivot_breakout_entry", strategy: poly_5m_pivot_breakout_entry },
    { key: "midpoint_streak_breakout", strategy: midpoint_streak_breakout },
    { key: "close_location_oscillator_extremes", strategy: close_location_oscillator_extremes },
    { key: "efficiency_ratio_implosion", strategy: efficiency_ratio_implosion },
    { key: "single_bar_roc_snapback", strategy: single_bar_roc_snapback },
    { key: "volume_thrust_zscore_continuation", strategy: volume_thrust_zscore_continuation },
    { key: "asymmetric_trailing_pullback", strategy: asymmetric_trailing_pullback },
    { key: "ema_distance_efficiency_snapback", strategy: ema_distance_efficiency_snapback },
    { key: "typical_price_vwap_distance_zscore", strategy: typical_price_vwap_distance_zscore },
    { key: "vwap_distance_zscore_fade", strategy: vwap_distance_zscore_fade },
    { key: "typical_price_zscore_reversion", strategy: typical_price_zscore_reversion },
    { key: "supertrend_extreme_overextension_fade", strategy: supertrend_extreme_overextension_fade },
    { key: "true_range_ratio_pop_chase", strategy: true_range_ratio_pop_chase },
    { key: "ema_touch_continuation", strategy: ema_touch_continuation },
    { key: "sma_slope_micro_chase", strategy: sma_slope_micro_chase },
];

export function createStrategiesRecordFromManifest(
    manifest: readonly StrategyManifestEntry[] = strategyManifest
): Record<string, Strategy> {
    const strategies: Record<string, Strategy> = {};

    for (const entry of manifest) {
        if (entry.key in strategies) {
            throw new Error(`Duplicate strategy key in manifest: ${entry.key}`);
        }
        strategies[entry.key] = entry.strategy;
    }

    return strategies;
}
