import type { StrategyParams } from "../types/strategies";

// AUTO-GENERATED by `npm run strategies:sync-manifest`.
// Do not manually edit.

export interface BuiltInStrategyMeta {
    key: string;
    name: string;
    description: string;
    defaultParams: StrategyParams;
    paramLabels: Record<string, string>;
    metadata?: {
        role?: string;
        direction?: string;
        walkForwardParams?: string[];
    };
    crossSymbolConfig?: boolean;
    polymarket1sConfig?: boolean;
}

export const builtInStrategyMeta: readonly BuiltInStrategyMeta[] = [
    {
        key: "entropy_ratio_regime_alignment",
        name: "Entropy Ratio Regime Alignment",
        description: "Trendable regimes are filtered by a fixed entropy-ratio gate (fast=0, threshold=2) and enter when price aligns with its slow rolling median.",
        defaultParams: {
        slowWindow: 30 } as Record<string, number>,
        paramLabels: {
        slowWindow: "Slow Entropy & Median Window" } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["slowWindow"] },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "wick_responsive_boundary_retest",
        name: "Boundary Retest Entry",
        description: "Variant 2: Requires price to retest the boundary after initial tests. More conservative - waits for pullback confirmation.",
        defaultParams: {
		boundary_lookback: 15,
		test_threshold: 3,
		retest_tolerance: 0.01 } as Record<string, number>,
        paramLabels: {
		boundary_lookback: "Boundary Lookback",
		test_threshold: "Test Threshold",
		retest_tolerance: "Retest Tolerance" } as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["boundary_lookback", "test_threshold", "retest_tolerance"] },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "probability_boundary_eigen_shift",
        name: "Probability Boundary Eigen-Shift",
        description: "When the typical price (representing the session's Eigenvalue) breaches a 3-sigma boundary of its own rolling state, the local probability density function has failed, forcing violent mean reversion.",
        defaultParams: { stateLookback: 50, eigenLimit: 3.0 } as Record<string, number>,
        paramLabels: { stateLookback: "State Lookback", eigenLimit: "Eigen Limit (Z-Score)" } as Record<string, string>,
        metadata: { role: "entry", direction: "both", walkForwardParams: ["stateLookback", "eigenLimit"] },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "pivot_midpoint_anchor_fade",
        name: "Pivot Midpoint Anchor Fade",
        description: "The midpoint between the most recent pivot high and low anchors structural fair value. When price deviates significantly from this anchor, reversion is favored.",
        defaultParams: {
		pivotLeftBars: 5,
		deviationMultiplier: 0.7 } as Record<string, number>,
        paramLabels: {
		pivotLeftBars: "Pivot Bars",
		deviationMultiplier: "Deviation Multiplier" } as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["pivotLeftBars", "deviationMultiplier"] },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "true_range_skewness_initiation",
        name: "True Range Skewness Initiation",
        description: "A sudden spike in the skewness of True Range indicates unilateral directional panic or euphoria initiating a new auction. Volatility asymmetry signals a structural break.",
        defaultParams: {
		skew_window: 20,
		zscore_trigger: 2.0,
	} as Record<string, number>,
        paramLabels: {
		skew_window: "Skewness Window",
		zscore_trigger: "Z-Score Trigger",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["skew_window", "zscore_trigger"],
	},
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "true_range_skew_acceptance",
        name: "True Range Skew Acceptance",
        description: "Trades true-range skew only when the current expanded bar also closes with directional acceptance.",
        defaultParams: {
        lookback: 10,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "efficiency_keltner_router",
        name: "Efficiency Keltner Router",
        description: "Routes Keltner boundary signals to fades in chop and continuation entries in efficient trends.",
        defaultParams: {
		er_lookback: 20,
		keltner_lookback: 55,
		er_threshold: 0.4,
	} as Record<string, number>,
        paramLabels: {
		er_lookback: "Efficiency Lookback",
		keltner_lookback: "Keltner Lookback",
		er_threshold: "Efficiency Threshold",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["er_lookback", "keltner_lookback", "er_threshold"],
	},
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "cumulative_return_zscore_reversion",
        name: "Cumulative Return Z-Score Reversion",
        description: "Fades cumulative multi-bar returns when they reach extreme z-scores.",
        defaultParams: {
        lookback: 20,
        zThreshold: 2.2,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
        zThreshold: "Z-Score Threshold",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback", "zThreshold"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "cumulative_return_percentile_reversion",
        name: "Cumulative Return Percentile Reversion",
        description: "Fades cumulative return over lookback when it sits at a percentile extreme of its own history.",
        defaultParams: {
        lookback: 30,
        pctlExtreme: 0.9,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
        pctlExtreme: "Percentile Extreme",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback", "pctlExtreme"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "body_proportion_percentile_fade",
        name: "Body Proportion Percentile Fade",
        description: "Fades high body-proportion conviction bars closing near extremes.",
        defaultParams: {
        lookback: 30,
        pctlExtreme: 0.85,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
        pctlExtreme: "Percentile Extreme",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback", "pctlExtreme"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "return_sign_streak_fade",
        name: "Return Sign Streak Fade",
        description: "Fades persistent same-sign return streaks when one leg has outperformed for multiple bars.",
        defaultParams: {
        lookback: 5,
        streakMin: 5,
    } as Record<string, number>,
        paramLabels: {
        lookback: "ROC Period",
        streakMin: "Min Streak Length",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback", "streakMin"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "close_location_gradient_acceleration",
        name: "Close Location Gradient Acceleration",
        description: "Follows accelerating directional pressure when close location gradient percentile is elevated with level confirmation.",
        defaultParams: {
        lookback: 25,
        gradientPercentileMin: 0.65,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
        gradientPercentileMin: "Min Gradient Percentile",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback", "gradientPercentileMin"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "modern_arbitrage_speed_reversion",
        name: "Modern Arbitrage Speed Reversion",
        description: "Fast mean reversion enabled by modern arbitrage infrastructure.",
        defaultParams: {
        lookback: 25,
        zThreshold: 1.3,
        efficiencyMax: 0.35,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
        zThreshold: "Z-Score Threshold",
        efficiencyMax: "Efficiency Max",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback", "zThreshold", "efficiencyMax"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "ema_confirmation",
        name: "EMA Confirmation",
        description: "Confirms entries only while close trades above (long) or below (short) its EMA. Use as an entry confirmation strategy.",
        defaultParams: {
        emaPeriod: 50,
    } as Record<string, number>,
        paramLabels: {
        emaPeriod: "EMA Period",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["emaPeriod"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "typical_close_skewness_acceptance",
        name: "Typical Close Skewness Acceptance",
        description: "Enters when typical price returns display asymmetry (skewness) and close acceptance agrees.",
        defaultParams: {
        lookback: 40,
        minSkew: 0.2,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
        minSkew: "Min Skew",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback", "minSkew"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "kelly_streak_exhaustion_reversion",
        name: "Kelly Streak Exhaustion Reversion",
        description: "Fades directional close return streaks when win probability scaled to streak length yields a positive Kelly allocation above minKellyFraction.",
        defaultParams: {
		lookback: 50,
		minKellyFraction: 0.2,
	} as Record<string, number>,
        paramLabels: {
		lookback: "Lookback Window",
		minKellyFraction: "Min Kelly Fraction",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["lookback", "minKellyFraction"],
	},
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "dmi_direction_confirmation",
        name: "DMI Direction Confirmation",
        description: "Signals with the dominant directional movement line without an ADX threshold.",
        defaultParams: {
        dmiPeriod: 14,
    } as Record<string, number>,
        paramLabels: {
        dmiPeriod: "DMI Period",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["dmiPeriod"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "parabolic_sar_confirmation",
        name: "Parabolic SAR Confirmation",
        description: "Signals when Parabolic SAR flips direction, using a fixed maximum acceleration of 0.20.",
        defaultParams: {
        accelerationStep: 0.02,
    } as Record<string, number>,
        paramLabels: {
        accelerationStep: "Acceleration Step",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["accelerationStep"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "dema_confirmation",
        name: "DEMA Confirmation",
        description: "Confirms direction relative to a double exponential moving average with reduced lag.",
        defaultParams: {
        lookback: 200,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "donchian_midpoint_confirmation",
        name: "Donchian Midpoint Confirmation",
        description: "Confirms direction relative to the midpoint of the trailing high-low price channel.",
        defaultParams: {
        lookback: 200,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "mcginley_dynamic_confirmation",
        name: "McGinley Dynamic Confirmation",
        description: "Confirms direction relative to a dynamic average that adjusts its response to price movement.",
        defaultParams: {
        lookback: 200,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "n_bar_momentum_confirmation",
        name: "N-Bar Momentum Confirmation",
        description: "Confirms direction from the sign of the close-to-close change over one trailing lookback.",
        defaultParams: {
        lookback: 200,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "rolling_median_confirmation",
        name: "Rolling Median Confirmation",
        description: "Confirms direction relative to a trailing median that is resistant to isolated price spikes.",
        defaultParams: {
        lookback: 200,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "typical_price_ema_confirmation",
        name: "Typical Price EMA Confirmation",
        description: "Confirms direction using an EMA of typical price so each bar's high and low inform the regime.",
        defaultParams: {
        lookback: 200,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "volume_weighted_median_confirmation",
        name: "Volume-Weighted Median Confirmation",
        description: "Confirms direction relative to the trailing median price weighted by traded volume.",
        defaultParams: {
        lookback: 200,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "wilder_ma_confirmation",
        name: "Wilder MA Confirmation",
        description: "Confirms direction relative to Wilder's slower recursively smoothed moving average.",
        defaultParams: {
        lookback: 200,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "zero_lag_ema_confirmation",
        name: "Zero-Lag EMA Confirmation",
        description: "Confirms direction relative to a de-lagged EMA input derived from the same lookback.",
        defaultParams: {
        lookback: 200,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "body_direction_placement_coherence",
        name: "Body Direction Placement Coherence",
        description: "Follows the current bar's direction when the rolling correlation between body direction and close placement exceeds a magic threshold.",
        defaultParams: {
        coherenceThreshold: 0.7,
    } as Record<string, number>,
        paramLabels: {
        coherenceThreshold: "Coherence Threshold",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["coherenceThreshold"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "nested_bar_oscillation_fade",
        name: "Nested Bar Oscillation Fade",
        description: "Fades the edge of a bar fully nested inside the previous bar while the market coils at a low range percentile.",
        defaultParams: {
        rangePctThreshold: 0.5,
    } as Record<string, number>,
        paramLabels: {
        rangePctThreshold: "Coil Range Percentile",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["rangePctThreshold"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "median_deviation_fade_chop",
        name: "Median Deviation Fade Chop",
        description: "Fades closes deviating more than 1.5 standard deviations from the rolling central value, catching chop-range edges that revert to center.",
        defaultParams: {
        lookback: 20,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "short_return_streak_fade_chop",
        name: "Short Return Streak Fade Chop",
        description: "Fades 3-bar same-sign return streaks, tuned for choppy markets where directional moves exhaust faster than the 5-bar threshold.",
        defaultParams: {} as Record<string, number>,
        paramLabels: {} as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: [],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "short_term_overextension_fade",
        name: "Short Term Overextension Fade",
        description: "Fades 5-bar average moves more than 1.2 standard deviations from the rolling average, reverting short-term overshoot of the medium-term center.",
        defaultParams: {
        lookback: 20,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Slow Average Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "open_location_zscore_reversion",
        name: "Open Location Z-Score Reversion",
        description: "Fades extreme open locations within the prior bar's range when the close reverses across the current bar's midpoint, catching failed breakouts.",
        defaultParams: {
        lookback: 20,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "decay_anchor_reversion",
        name: "Decay Anchor Reversion",
        description: "Fades closes stretched at least 2 ATR from an exponentially decay-weighted fair center.",
        defaultParams: {
        decay: 0.95,
    } as Record<string, number>,
        paramLabels: {
        decay: "Decay Factor",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["decay"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "defended_low_reversion",
        name: "Defended Low Reversion",
        description: "Fades channel-edge prints where the opposing side won the close, showing the edge was defended.",
        defaultParams: {
        lookback: 50,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "lagged_value_anchor_reversion",
        name: "Lagged Value Anchor Reversion",
        description: "Fades closes stretched at least 2 ATR from where the rolling median sat 10 bars ago.",
        defaultParams: {
        lookback: 40,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "rejection_confirmed_depth_fade",
        name: "Rejection Confirmed Depth Fade",
        description: "Fades robust z-score extremes only when the extreme bar's wick imbalance shows the push was rejected intrabar.",
        defaultParams: {
        lookback: 40,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "vwap_deviation_reversion",
        name: "VWAP Deviation Reversion",
        description: "Fades multi-ATR excursions from the rolling participation-weighted VWAP anchor.",
        defaultParams: {
        period: 30,
    } as Record<string, number>,
        paramLabels: {
        period: "Anchor Period",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["period"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "robust_zscore_typical_fade",
        name: "Robust Z-Score Typical Fade",
        description: "Fades typical-price extremes standardized by their own rolling median and MAD instead of mean and standard deviation.",
        defaultParams: {
        lookback: 40,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "cmf_extreme_fade",
        name: "CMF Extreme Fade",
        description: "Fades the cumulative money-flow proxy when it pins at an extreme over the lookback.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "CMF Period",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "robust_placement_extreme_continuation",
        name: "Robust Placement Extreme Continuation",
        description: "Continues when close location is robustly extreme relative to its own trailing median and MAD.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Robust Z Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "median_velocity_pullback",
        name: "Median Velocity Pullback",
        description: "Buys dips into a rising rolling median and rallies into a falling one.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Median Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
];
