import type { StrategyParams } from "../types/strategies";

// AUTO-GENERATED by `npm run strategies:sync-manifest`.
// Do not manually edit.

export interface BuiltInStrategyMeta {
    key: string;
    name: string;
    description: string;
    defaultParams: StrategyParams;
    paramLabels: Record<string, string>;
    metadata?: {
        role?: string;
        direction?: string;
        walkForwardParams?: string[];
    };
    crossSymbolConfig?: boolean;
    polymarket1sConfig?: boolean;
}

export const builtInStrategyMeta: readonly BuiltInStrategyMeta[] = [
    {
        key: "entropy_ratio_regime_alignment",
        name: "Entropy Ratio Regime Alignment",
        description: "Trendable regimes are filtered by a fixed entropy-ratio gate (fast=0, threshold=2) and enter when price aligns with its slow rolling median.",
        defaultParams: {
        slowWindow: 30 } as Record<string, number>,
        paramLabels: {
        slowWindow: "Slow Entropy & Median Window" } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["slowWindow"] },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "wick_responsive_boundary_retest",
        name: "Boundary Retest Entry",
        description: "Variant 2: Requires price to retest the boundary after initial tests. More conservative - waits for pullback confirmation.",
        defaultParams: {
		boundary_lookback: 15,
		test_threshold: 3,
		retest_tolerance: 0.01 } as Record<string, number>,
        paramLabels: {
		boundary_lookback: "Boundary Lookback",
		test_threshold: "Test Threshold",
		retest_tolerance: "Retest Tolerance" } as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["boundary_lookback", "test_threshold", "retest_tolerance"] },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "probability_boundary_eigen_shift",
        name: "Probability Boundary Eigen-Shift",
        description: "When the typical price (representing the session's Eigenvalue) breaches a 3-sigma boundary of its own rolling state, the local probability density function has failed, forcing violent mean reversion.",
        defaultParams: { stateLookback: 50, eigenLimit: 3.0 } as Record<string, number>,
        paramLabels: { stateLookback: "State Lookback", eigenLimit: "Eigen Limit (Z-Score)" } as Record<string, string>,
        metadata: { role: "entry", direction: "both", walkForwardParams: ["stateLookback", "eigenLimit"] },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "pivot_midpoint_anchor_fade",
        name: "Pivot Midpoint Anchor Fade",
        description: "The midpoint between the most recent pivot high and low anchors structural fair value. When price deviates significantly from this anchor, reversion is favored.",
        defaultParams: {
		pivotLeftBars: 5,
		deviationMultiplier: 0.7 } as Record<string, number>,
        paramLabels: {
		pivotLeftBars: "Pivot Bars",
		deviationMultiplier: "Deviation Multiplier" } as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["pivotLeftBars", "deviationMultiplier"] },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "true_range_skewness_initiation",
        name: "True Range Skewness Initiation",
        description: "A sudden spike in the skewness of True Range indicates unilateral directional panic or euphoria initiating a new auction. Volatility asymmetry signals a structural break.",
        defaultParams: {
		skew_window: 20,
		zscore_trigger: 2.0,
	} as Record<string, number>,
        paramLabels: {
		skew_window: "Skewness Window",
		zscore_trigger: "Z-Score Trigger",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["skew_window", "zscore_trigger"],
	},
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "true_range_skew_acceptance",
        name: "True Range Skew Acceptance",
        description: "Trades true-range skew only when the current expanded bar also closes with directional acceptance.",
        defaultParams: {
        lookback: 10,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "efficiency_keltner_router",
        name: "Efficiency Keltner Router",
        description: "Routes Keltner boundary signals to fades in chop and continuation entries in efficient trends.",
        defaultParams: {
		er_lookback: 20,
		keltner_lookback: 55,
		er_threshold: 0.4,
	} as Record<string, number>,
        paramLabels: {
		er_lookback: "Efficiency Lookback",
		keltner_lookback: "Keltner Lookback",
		er_threshold: "Efficiency Threshold",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["er_lookback", "keltner_lookback", "er_threshold"],
	},
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "cumulative_return_zscore_reversion",
        name: "Cumulative Return Z-Score Reversion",
        description: "Fades cumulative multi-bar returns when they reach extreme z-scores.",
        defaultParams: {
        lookback: 20,
        zThreshold: 2.2,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
        zThreshold: "Z-Score Threshold",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback", "zThreshold"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "cumulative_return_percentile_reversion",
        name: "Cumulative Return Percentile Reversion",
        description: "Fades cumulative return over lookback when it sits at a percentile extreme of its own history.",
        defaultParams: {
        lookback: 30,
        pctlExtreme: 0.9,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
        pctlExtreme: "Percentile Extreme",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback", "pctlExtreme"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "body_proportion_percentile_fade",
        name: "Body Proportion Percentile Fade",
        description: "Fades high body-proportion conviction bars closing near extremes.",
        defaultParams: {
        lookback: 30,
        pctlExtreme: 0.85,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
        pctlExtreme: "Percentile Extreme",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback", "pctlExtreme"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "return_sign_streak_fade",
        name: "Return Sign Streak Fade",
        description: "Fades persistent same-sign return streaks when one leg has outperformed for multiple bars.",
        defaultParams: {
        lookback: 5,
        streakMin: 5,
    } as Record<string, number>,
        paramLabels: {
        lookback: "ROC Period",
        streakMin: "Min Streak Length",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback", "streakMin"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "close_location_gradient_acceleration",
        name: "Close Location Gradient Acceleration",
        description: "Follows accelerating directional pressure when close location gradient percentile is elevated with level confirmation.",
        defaultParams: {
        lookback: 25,
        gradientPercentileMin: 0.65,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
        gradientPercentileMin: "Min Gradient Percentile",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback", "gradientPercentileMin"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "modern_arbitrage_speed_reversion",
        name: "Modern Arbitrage Speed Reversion",
        description: "Fast mean reversion enabled by modern arbitrage infrastructure.",
        defaultParams: {
        lookback: 25,
        zThreshold: 1.3,
        efficiencyMax: 0.35,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
        zThreshold: "Z-Score Threshold",
        efficiencyMax: "Efficiency Max",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback", "zThreshold", "efficiencyMax"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "ema_confirmation",
        name: "EMA Confirmation",
        description: "Confirms entries only while close trades above (long) or below (short) its EMA. Use as an entry confirmation strategy.",
        defaultParams: {
        emaPeriod: 50,
    } as Record<string, number>,
        paramLabels: {
        emaPeriod: "EMA Period",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["emaPeriod"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "typical_close_skewness_acceptance",
        name: "Typical Close Skewness Acceptance",
        description: "Enters when typical price returns display asymmetry (skewness) and close acceptance agrees.",
        defaultParams: {
        lookback: 40,
        minSkew: 0.2,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
        minSkew: "Min Skew",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback", "minSkew"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "kelly_streak_exhaustion_reversion",
        name: "Kelly Streak Exhaustion Reversion",
        description: "Fades directional close return streaks when win probability scaled to streak length yields a positive Kelly allocation above minKellyFraction.",
        defaultParams: {
		lookback: 50,
		minKellyFraction: 0.2,
	} as Record<string, number>,
        paramLabels: {
		lookback: "Lookback Window",
		minKellyFraction: "Min Kelly Fraction",
	} as Record<string, string>,
        metadata: {
		role: "entry",
		direction: "both",
		walkForwardParams: ["lookback", "minKellyFraction"],
	},
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "dmi_direction_confirmation",
        name: "DMI Direction Confirmation",
        description: "Signals with the dominant directional movement line without an ADX threshold.",
        defaultParams: {
        dmiPeriod: 14,
    } as Record<string, number>,
        paramLabels: {
        dmiPeriod: "DMI Period",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["dmiPeriod"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "parabolic_sar_confirmation",
        name: "Parabolic SAR Confirmation",
        description: "Signals when Parabolic SAR flips direction, using a fixed maximum acceleration of 0.20.",
        defaultParams: {
        accelerationStep: 0.02,
    } as Record<string, number>,
        paramLabels: {
        accelerationStep: "Acceleration Step",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["accelerationStep"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "dema_confirmation",
        name: "DEMA Confirmation",
        description: "Confirms direction relative to a double exponential moving average with reduced lag.",
        defaultParams: {
        lookback: 200,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "donchian_midpoint_confirmation",
        name: "Donchian Midpoint Confirmation",
        description: "Confirms direction relative to the midpoint of the trailing high-low price channel.",
        defaultParams: {
        lookback: 200,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "mcginley_dynamic_confirmation",
        name: "McGinley Dynamic Confirmation",
        description: "Confirms direction relative to a dynamic average that adjusts its response to price movement.",
        defaultParams: {
        lookback: 200,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "n_bar_momentum_confirmation",
        name: "N-Bar Momentum Confirmation",
        description: "Confirms direction from the sign of the close-to-close change over one trailing lookback.",
        defaultParams: {
        lookback: 200,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "rolling_median_confirmation",
        name: "Rolling Median Confirmation",
        description: "Confirms direction relative to a trailing median that is resistant to isolated price spikes.",
        defaultParams: {
        lookback: 200,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "typical_price_ema_confirmation",
        name: "Typical Price EMA Confirmation",
        description: "Confirms direction using an EMA of typical price so each bar's high and low inform the regime.",
        defaultParams: {
        lookback: 200,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "volume_weighted_median_confirmation",
        name: "Volume-Weighted Median Confirmation",
        description: "Confirms direction relative to the trailing median price weighted by traded volume.",
        defaultParams: {
        lookback: 200,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "wilder_ma_confirmation",
        name: "Wilder MA Confirmation",
        description: "Confirms direction relative to Wilder's slower recursively smoothed moving average.",
        defaultParams: {
        lookback: 200,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "zero_lag_ema_confirmation",
        name: "Zero-Lag EMA Confirmation",
        description: "Confirms direction relative to a de-lagged EMA input derived from the same lookback.",
        defaultParams: {
        lookback: 200,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "body_direction_placement_coherence",
        name: "Body Direction Placement Coherence",
        description: "Follows the current bar's direction when the rolling correlation between body direction and close placement exceeds a magic threshold.",
        defaultParams: {
        coherenceThreshold: 0.7,
    } as Record<string, number>,
        paramLabels: {
        coherenceThreshold: "Coherence Threshold",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["coherenceThreshold"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "nested_bar_oscillation_fade",
        name: "Nested Bar Oscillation Fade",
        description: "Fades the edge of a bar fully nested inside the previous bar while the market coils at a low range percentile.",
        defaultParams: {
        rangePctThreshold: 0.5,
    } as Record<string, number>,
        paramLabels: {
        rangePctThreshold: "Coil Range Percentile",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["rangePctThreshold"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "median_deviation_fade_chop",
        name: "Median Deviation Fade Chop",
        description: "Fades closes deviating more than 1.5 standard deviations from the rolling central value, catching chop-range edges that revert to center.",
        defaultParams: {
        lookback: 20,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "short_return_streak_fade_chop",
        name: "Short Return Streak Fade Chop",
        description: "Fades 3-bar same-sign return streaks, tuned for choppy markets where directional moves exhaust faster than the 5-bar threshold.",
        defaultParams: {} as Record<string, number>,
        paramLabels: {} as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: [],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "short_term_overextension_fade",
        name: "Short Term Overextension Fade",
        description: "Fades 5-bar average moves more than 1.2 standard deviations from the rolling average, reverting short-term overshoot of the medium-term center.",
        defaultParams: {
        lookback: 20,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Slow Average Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "open_location_zscore_reversion",
        name: "Open Location Z-Score Reversion",
        description: "Fades extreme open locations within the prior bar's range when the close reverses across the current bar's midpoint, catching failed breakouts.",
        defaultParams: {
        lookback: 20,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "decay_anchor_reversion",
        name: "Decay Anchor Reversion",
        description: "Fades closes stretched at least 2 ATR from an exponentially decay-weighted fair center.",
        defaultParams: {
        decay: 0.95,
    } as Record<string, number>,
        paramLabels: {
        decay: "Decay Factor",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["decay"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "defended_low_reversion",
        name: "Defended Low Reversion",
        description: "Fades channel-edge prints where the opposing side won the close, showing the edge was defended.",
        defaultParams: {
        lookback: 50,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "lagged_value_anchor_reversion",
        name: "Lagged Value Anchor Reversion",
        description: "Fades closes stretched at least 2 ATR from where the rolling median sat 10 bars ago.",
        defaultParams: {
        lookback: 40,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "rejection_confirmed_depth_fade",
        name: "Rejection Confirmed Depth Fade",
        description: "Fades robust z-score extremes only when the extreme bar's wick imbalance shows the push was rejected intrabar.",
        defaultParams: {
        lookback: 40,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "vwap_deviation_reversion",
        name: "VWAP Deviation Reversion",
        description: "Fades multi-ATR excursions from the rolling participation-weighted VWAP anchor.",
        defaultParams: {
        period: 30,
    } as Record<string, number>,
        paramLabels: {
        period: "Anchor Period",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["period"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "robust_zscore_typical_fade",
        name: "Robust Z-Score Typical Fade",
        description: "Fades typical-price extremes standardized by their own rolling median and MAD instead of mean and standard deviation.",
        defaultParams: {
        lookback: 40,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Lookback Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "atr_r_multiple_follow",
        name: "ATR R-Multiple Follow",
        description: "Follows single-bar moves of 2+ prior-ATR, trading impulse magnitude in volatility units.",
        defaultParams: {
        lookback: 20,
    } as Record<string, number>,
        paramLabels: {
        lookback: "ATR Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "atr_regime_follow",
        name: "ATR Regime Follow",
        description: "Trades single-bar direction only when ATR sits at a high percentile of its own history.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "ATR / Regime Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "body_direction_autocorr_switch",
        name: "Body Direction Autocorrelation Switch",
        description: "Routes follow vs fade by the sign of the rolling lag-1 autocorrelation of body direction.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Autocorrelation Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "deep_wick_reversal",
        name: "Deep Wick Reversal",
        description: "Reverses at bars whose lower or upper wick sits at a percentile extreme of its own history.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Percentile Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "dual_median_crossover",
        name: "Dual Median Crossover",
        description: "Trades the crossover of a fast rolling median of closes through a slow one.",
        defaultParams: {
        lookback: 60,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Slow Median Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "gap_percentile_fade",
        name: "Gap Percentile Fade",
        description: "Fades reopen gaps whose |gap| sits at a percentile extreme of its own history.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Percentile Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "indecision_share_fade",
        name: "Indecision Share Fade",
        description: "Fades directional closes when most bars in the window are doji.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Indecision Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "median_extreme_envelope_breakout",
        name: "Median Extreme Envelope Breakout",
        description: "Enters when the close breaks the trailing median of highs or median of lows.",
        defaultParams: {
        lookback: 40,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Envelope Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "median_side_streak_follow",
        name: "Median Side Streak Follow",
        description: "Follows streaks of consecutive closes on the same side of the rolling median.",
        defaultParams: {
        lookback: 40,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Median Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "true_range_extreme_fade",
        name: "True Range Extreme Fade",
        description: "Fades the direction of bars whose true range sits at a percentile extreme of its own history.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Percentile Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "band_walkaway_fade",
        name: "Band Walkaway Fade",
        description: "Fades when the close has spent consecutive bars outside the median +/- ATR band.",
        defaultParams: {
        bandWidth: 2,
    } as Record<string, number>,
        paramLabels: {
        bandWidth: "Band Width (ATR)",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["bandWidth"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "cmf_extreme_fade",
        name: "CMF Extreme Fade",
        description: "Fades the cumulative money-flow proxy when it pins at an extreme over the lookback.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "CMF Period",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "decay_dispersion_fade",
        name: "Decay Dispersion Fade",
        description: "Fades stretch measured in decay-weighted standard deviations around a decay-weighted fair center.",
        defaultParams: {
        decay: 0.95,
    } as Record<string, number>,
        paramLabels: {
        decay: "Decay Retention",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["decay"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "initiative_pressure_extreme_follow",
        name: "Initiative Pressure Extreme Follow",
        description: "Follows bars whose initiative pressure sits at a percentile extreme of its own history.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Pressure Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "median_crossing_chop_fade",
        name: "Median Crossing Chop Fade",
        description: "Fades toward the rolling median when the close flips it often enough to signal chop.",
        defaultParams: {
        lookback: 24,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Median / Crossing Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "placement_forecast_slope",
        name: "Placement Forecast Slope",
        description: "Trades the estimated rolling correlation between close placement and the next bar's return.",
        defaultParams: {
        lookback: 40,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Estimation Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "return_kurtosis_regime_switch",
        name: "Return Kurtosis Regime Switch",
        description: "Follows moves in thin-tailed return regimes and fades them in fat-tailed regimes.",
        defaultParams: {
        lookback: 40,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Kurtosis Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "trailing_envelope_breakout",
        name: "Trailing Envelope Breakout",
        description: "Breaks the prior-only trailing high/low envelope only when the close earns the new territory.",
        defaultParams: {
        lookback: 20,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Envelope Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "trend_slope_strength_follow",
        name: "Trend Slope Strength",
        description: "Trades the rolling correlation of closes with the bar index, the scale-free steepness of the trend line.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Trend Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "vol_expansion_ratio_follow",
        name: "Volatility Expansion Ratio",
        description: "Follows the expansion bar when short-window return volatility jumps relative to its long baseline.",
        defaultParams: {
        lookback: 60,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Baseline Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "body_size_acceleration",
        name: "Body Size Acceleration",
        description: "Continues direction when body conviction has grown sharply over the window and the bar is still large.",
        defaultParams: {
        lookback: 12,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Growth Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "cmf_flow_flip_confirmation",
        name: "CMF Flow Flip Confirmation",
        description: "Trades the zero-crossing of the cumulative money-flow proxy when the bar confirms the flip.",
        defaultParams: {
        lookback: 20,
    } as Record<string, number>,
        paramLabels: {
        lookback: "CMF Period",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "decayed_body_direction_balance",
        name: "Decayed Body Direction Balance",
        description: "Follows the current body when the decayed balance of body directions is clearly biased in its favor.",
        defaultParams: {
        decay: 0.9,
    } as Record<string, number>,
        paramLabels: {
        decay: "Decay Retention",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["decay"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "gap_autocorrelation_persistence",
        name: "Gap Autocorrelation Persistence",
        description: "Follows the current gap when gap directions have been serially dependent over the window.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Autocorrelation Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "initiative_pressure_flip_continuation",
        name: "Initiative Pressure Flip Continuation",
        description: "Follows the bar when initiative pressure flips from rejection into acceptance or back.",
        defaultParams: {
        lookback: 24,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Pressure Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "open_close_sweep_momentum",
        name: "Open Close Sweep Momentum",
        description: "Follows rare full-range sweeps, measured as close location minus open location at a percentile extreme.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Sweep Percentile Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "placement_band_breakout",
        name: "Placement Band Breakout",
        description: "Breaks the prior-only trailing envelope of close acceptance, a new extreme in how bars close.",
        defaultParams: {
        lookback: 20,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Envelope Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "positional_streak_persistence",
        name: "Positional Streak Persistence",
        description: "Follows streaks of closes on the same side of the rolling median when the current bar agrees.",
        defaultParams: {
        lookback: 20,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Median Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "robust_placement_extreme_continuation",
        name: "Robust Placement Extreme Continuation",
        description: "Continues when close location is robustly extreme relative to its own trailing median and MAD.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Robust Z Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "volatility_cascade_streak",
        name: "Volatility Cascade Streak",
        description: "Follows the net direction when consecutive expanding-range bars form a volatility cascade.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Net-Change Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "acceptance_entropy_consistency",
        name: "Acceptance Entropy Consistency",
        description: "Follows the current bar only when close-acceptance placement has been consistent over the window.",
        defaultParams: {
        lookback: 24,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Entropy Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "body_mid_drift_continuation",
        name: "Body Mid Drift Continuation",
        description: "Continues the drift of the wick-robust body midpoint when both the smoothed and current drift agree.",
        defaultParams: {
        lookback: 20,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Smoothing Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "efficiency_transition_momentum",
        name: "Efficiency Transition Momentum",
        description: "Enters on the one-bar acceleration of the efficiency ratio, the moment a path straightens.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Efficiency Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "gap_fill_intrabar_fade",
        name: "Gap Fill Intrabar Fade",
        description: "Fades extreme gaps that the same bar recovers intrabar back through the gap level.",
        defaultParams: {
        lookback: 24,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Gap Percentile Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "median_velocity_pullback",
        name: "Median Velocity Pullback",
        description: "Buys dips into a rising rolling median and rallies into a falling one.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Median Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "placement_regime_flip",
        name: "Placement Regime Flip",
        description: "Trades the zero-cross of the smoothed close-acceptance series, a flip in how bars close.",
        defaultParams: {
        lookback: 24,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Smoothing Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "placement_skewness_anchor",
        name: "Placement Skewness Anchor",
        description: "Trades with the tail of the close-location distribution when the current bar confirms it.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Skewness Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "price_flow_divergence_fade",
        name: "Price Flow Divergence Fade",
        description: "Fades trailing-range extremes printed without supporting money flow.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Range / Flow Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "range_volume_coupling_fade",
        name: "Range Volume Coupling Fade",
        description: "Routes by the correlation of bar size with relative volume participation.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Coupling Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "wick_imbalance_persistence_continuation",
        name: "Wick Imbalance Persistence Continuation",
        description: "Continues the side whose wick imbalance has been persistently defending.",
        defaultParams: {
        lookback: 20,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Smoothing Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "adaptive_threshold_reversion",
        name: "Adaptive Threshold Reversion",
        description: "Fades closes stretched beyond an ATR band whose width adapts to the estimated mean-reversion speed of the deviation series.",
        defaultParams: {
        decay: 0.95,
    } as Record<string, number>,
        paramLabels: {
        decay: "Decay Factor",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["decay"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "ar1_residual_reversion",
        name: "AR(1) Residual Reversion",
        description: "Fades closes that deviate at least 1.5 residual standard deviations from their own trailing-window AR(1) forecast.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "AR Fit Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "climax_volume_reversion",
        name: "Climax Volume Reversion",
        description: "Fades closes at least 1.5 ATR from the rolling median when the bar's volume ranks at or above the 90th percentile.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Median & Volume Percentile Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "confirmed_reversion_fade",
        name: "Confirmed Reversion Fade",
        description: "Fades closes still at least 1.5 ATR from the rolling median once the stretch has started collapsing over the prior 3 bars.",
        defaultParams: {
        lookback: 40,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Median Anchor Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "dislocation_extreme_fade",
        name: "Dislocation Extreme Fade",
        description: "Fades the first bar whose median-ATR stretch becomes a new prior-only record for the lookback window.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Median & Record Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "double_stretch_exhaustion_fade",
        name: "Double Stretch Exhaustion Fade",
        description: "Fades the second consecutive bar stretched at least 1.2 ATR from the rolling median.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Median Anchor Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "quiet_regime_reversion",
        name: "Quiet Regime Reversion",
        description: "Fades closes at least 1.5 ATR from the rolling median only while ATR sits at or below the 30th percentile of its own history.",
        defaultParams: {
        lookback: 30,
    } as Record<string, number>,
        paramLabels: {
        lookback: "ATR Period & Percentile Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "stationary_center_fade",
        name: "Stationary Center Fade",
        description: "Fades closes at least 1.5 ATR from the rolling median only when the median itself has drifted less than 0.5 ATR over the window.",
        defaultParams: {
        lookback: 40,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Median Anchor Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "stretch_percentile_fade",
        name: "Stretch Percentile Fade",
        description: "Fades closes whose median-ATR stretch ranks in the bottom 5% or top 5% of its own history.",
        defaultParams: {
        lookback: 40,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Median & Percentile Window",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
    {
        key: "window_open_anchor_reversion",
        name: "Window Open Anchor Reversion",
        description: "Fades closes stretched at least 2.5 ATR from the opening price of the bar that started the trailing window.",
        defaultParams: {
        lookback: 20,
    } as Record<string, number>,
        paramLabels: {
        lookback: "Window Open Lookback",
    } as Record<string, string>,
        metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["lookback"],
    },
        crossSymbolConfig: false,
        polymarket1sConfig: false,
    },
];
