//! Core data types for the trading engine
//!
//! These types mirror the TypeScript definitions in `types.ts` for seamless
//! interoperability between the frontend and Rust backend.
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
// ============================================================================
// Time Types
// ============================================================================
/// Unix timestamp in milliseconds (matches lightweight-charts Time type)
pub type Time = i64;
// ============================================================================
// Market Data Types
// ============================================================================
/// OHLCV (Open, High, Low, Close, Volume) candle data
///
/// Memory-optimized layout for cache efficiency with 5M+ bars
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[repr(C)]
#[allow(clippy::upper_case_acronyms)]
pub struct OHLCV {
    pub time: Time,
    pub open: f64,
    pub high: f64,
    pub low: f64,
    pub close: f64,
    pub volume: f64,
}
#[allow(dead_code)]
impl OHLCV {
    #[inline]
    #[must_use]
    pub const fn new(time: Time, open: f64, high: f64, low: f64, close: f64, volume: f64) -> Self {
        Self {
            time,
            open,
            high,
            low,
            close,
            volume,
        }
    }
    /// Typical price: (high + low + close) / 3
    #[inline]
    #[must_use]
    pub fn typical_price(&self) -> f64 {
        (self.high + self.low + self.close) / 3.0
    }
    /// HL2: (high + low) / 2
    #[inline]
    #[must_use]
    pub fn hl2(&self) -> f64 {
        (self.high + self.low) / 2.0
    }
}
// ============================================================================
// Signal Types
// ============================================================================
/// Trading signal type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SignalType {
    Buy,
    Sell,
}
/// A trading signal generated by a strategy
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signal {
    pub time: Time,
    #[serde(rename = "type")]
    pub signal_type: SignalType,
    pub price: f64,
    #[serde(rename = "barIndex", default, skip_serializing_if = "Option::is_none")]
    pub bar_index: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}
#[allow(dead_code)]
impl Signal {
    pub fn buy(time: Time, price: f64) -> Self {
        Self {
            time,
            signal_type: SignalType::Buy,
            price,
            bar_index: None,
            reason: None,
        }
    }
    pub fn sell(time: Time, price: f64) -> Self {
        Self {
            time,
            signal_type: SignalType::Sell,
            price,
            bar_index: None,
            reason: None,
        }
    }
    pub fn with_reason(mut self, reason: impl Into<String>) -> Self {
        self.reason = Some(reason.into());
        self
    }
}
// ============================================================================
// Trade Types
// ============================================================================
/// Trade direction/type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TradeType {
    Long,
    Short,
}
/// A completed trade with entry and exit information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Trade {
    pub id: u32,
    #[serde(rename = "type")]
    pub trade_type: TradeType,
    #[serde(rename = "entryTime")]
    pub entry_time: Time,
    #[serde(rename = "entryPrice")]
    pub entry_price: f64,
    #[serde(rename = "exitTime")]
    pub exit_time: Time,
    #[serde(rename = "exitPrice")]
    pub exit_price: f64,
    pub pnl: f64,
    #[serde(rename = "pnlPercent")]
    pub pnl_percent: f64,
    pub size: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fees: Option<f64>,
}
#[allow(dead_code)]
impl Trade {
    /// Check if this trade was profitable
    #[inline]
    #[must_use]
    pub const fn is_winner(&self) -> bool {
        self.pnl > 0.0
    }
    /// Get the R-multiple (return / risk)
    #[inline]
    #[must_use]
    pub fn r_multiple(&self, risk_per_share: f64) -> f64 {
        if risk_per_share == 0.0 {
            return 0.0;
        }
        self.pnl / (self.size * risk_per_share)
    }
}
// ============================================================================
// Equity Curve Point
// ============================================================================
/// A single point on the equity curve
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct EquityPoint {
    pub time: Time,
    pub value: f64,
}
// ============================================================================
// Backtest Result
// ============================================================================
/// Complete backtest results with all statistics
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BacktestResult {
    pub trades: Vec<Trade>,
    #[serde(rename = "netProfit")]
    pub net_profit: f64,
    #[serde(rename = "netProfitPercent")]
    pub net_profit_percent: f64,
    #[serde(rename = "winRate")]
    pub win_rate: f64,
    pub expectancy: f64,
    #[serde(rename = "avgTrade")]
    pub avg_trade: f64,
    #[serde(rename = "profitFactor")]
    pub profit_factor: f64,
    #[serde(rename = "maxDrawdown")]
    pub max_drawdown: f64,
    #[serde(rename = "maxDrawdownPercent")]
    pub max_drawdown_percent: f64,
    #[serde(rename = "totalTrades")]
    pub total_trades: u32,
    #[serde(rename = "winningTrades")]
    pub winning_trades: u32,
    #[serde(rename = "losingTrades")]
    pub losing_trades: u32,
    #[serde(rename = "avgWin")]
    pub avg_win: f64,
    #[serde(rename = "avgLoss")]
    pub avg_loss: f64,
    #[serde(rename = "sharpeRatio")]
    pub sharpe_ratio: f64,
    #[serde(rename = "equityCurve")]
    pub equity_curve: Vec<EquityPoint>,
    /// Internal execution metadata used by the compact fresh-entry API.
    /// It is deliberately not part of the normal backtest wire contract.
    #[serde(skip)]
    pub final_position_open: bool,
}
impl Default for BacktestResult {
    fn default() -> Self {
        Self {
            trades: Vec::new(),
            net_profit: 0.0,
            net_profit_percent: 0.0,
            win_rate: 0.0,
            expectancy: 0.0,
            avg_trade: 0.0,
            profit_factor: 0.0,
            max_drawdown: 0.0,
            max_drawdown_percent: 0.0,
            total_trades: 0,
            winning_trades: 0,
            losing_trades: 0,
            avg_win: 0.0,
            avg_loss: 0.0,
            sharpe_ratio: 0.0,
            equity_curve: Vec::new(),
            final_position_open: false,
        }
    }
}
// ============================================================================
// Strategy Parameters
// ============================================================================
/// Dynamic strategy parameters (matches TypeScript Record<string, number>)
pub type StrategyParams = HashMap<String, f64>;
/// Entry confirmation mode
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum EntryConfirmationMode {
    #[default]
    None,
    Close,
    Volume,
    Rsi,
}
/// Trade direction filter
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TradeDirection {
    #[default]
    Long,
    Short,
    Both,
}
/// Risk management mode
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum RiskMode {
    #[default]
    Simple,
    Advanced,
    Percentage,
}
/// Price used to fill a signal-generated order.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ExecutionModel {
    #[default]
    SignalClose,
    NextOpen,
    NextClose,
}
/// Complete backtest settings
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BacktestSettings {
    // ATR-based settings
    #[serde(default = "default_atr_period")]
    pub atr_period: u32,
    #[serde(default)]
    pub stop_loss_atr: f64,
    #[serde(default)]
    pub take_profit_atr: f64,
    #[serde(default)]
    pub trailing_atr: f64,
    #[serde(default)]
    pub partial_take_profit_at_r: f64,
    #[serde(default)]
    pub partial_take_profit_percent: f64,
    #[serde(default)]
    pub break_even_at_r: f64,
    #[serde(default)]
    pub time_stop_bars: u32,
    // Percentage-based risk management
    #[serde(default)]
    pub risk_mode: RiskMode,
    #[serde(default)]
    pub stop_loss_percent: f64,
    #[serde(default)]
    pub take_profit_percent: f64,
    #[serde(default)]
    pub stop_loss_enabled: bool,
    #[serde(default)]
    pub take_profit_enabled: bool,
    // Trend/regime filters
    #[serde(default)]
    pub trend_ema_period: u32,
    #[serde(default)]
    pub trend_ema_slope_bars: u32,
    #[serde(default)]
    pub atr_percent_min: f64,
    #[serde(default)]
    pub atr_percent_max: f64,
    #[serde(default = "default_adx_period")]
    pub adx_period: u32,
    #[serde(default)]
    pub adx_min: f64,
    #[serde(default)]
    pub adx_max: f64,
    // Entry confirmation
    #[serde(default)]
    pub entry_confirmation: EntryConfirmationMode,
    #[serde(default = "default_confirm_lookback")]
    pub confirm_lookback: u32,
    #[serde(default = "default_volume_sma_period")]
    pub volume_sma_period: u32,
    #[serde(default = "default_volume_multiplier")]
    pub volume_multiplier: f64,
    #[serde(default = "default_rsi_period")]
    pub rsi_period: u32,
    #[serde(default = "default_rsi_bullish")]
    pub rsi_bullish: f64,
    #[serde(default = "default_rsi_bearish")]
    pub rsi_bearish: f64,
    // Direction filter
    #[serde(default)]
    pub trade_direction: TradeDirection,
    // Signal execution policy
    #[serde(default)]
    pub execution_model: ExecutionModel,
    #[serde(default)]
    pub allow_same_bar_exit: bool,
    #[serde(default)]
    pub slippage_bps: f64,
    // Entry re-entry guard
    #[serde(default)]
    pub risk_cooldown_enabled: bool,
    #[serde(default)]
    pub risk_cooldown_bars: u32,
}
// Default value functions for serde
const fn default_atr_period() -> u32 {
    14
}
const fn default_adx_period() -> u32 {
    14
}
const fn default_confirm_lookback() -> u32 {
    1
}
const fn default_volume_sma_period() -> u32 {
    20
}
const fn default_volume_multiplier() -> f64 {
    1.0
}
const fn default_rsi_period() -> u32 {
    14
}
const fn default_rsi_bullish() -> f64 {
    55.0
}
const fn default_rsi_bearish() -> f64 {
    45.0
}
impl Default for BacktestSettings {
    fn default() -> Self {
        Self {
            atr_period: 14,
            stop_loss_atr: 0.0,
            take_profit_atr: 0.0,
            trailing_atr: 0.0,
            partial_take_profit_at_r: 0.0,
            partial_take_profit_percent: 0.0,
            break_even_at_r: 0.0,
            time_stop_bars: 0,
            risk_mode: RiskMode::Simple,
            stop_loss_percent: 0.0,
            take_profit_percent: 0.0,
            stop_loss_enabled: false,
            take_profit_enabled: false,
            trend_ema_period: 0,
            trend_ema_slope_bars: 0,
            atr_percent_min: 0.0,
            atr_percent_max: 0.0,
            adx_period: 14,
            adx_min: 0.0,
            adx_max: 0.0,
            entry_confirmation: EntryConfirmationMode::None,
            confirm_lookback: 1,
            volume_sma_period: 20,
            volume_multiplier: 1.0,
            rsi_period: 14,
            rsi_bullish: 55.0,
            rsi_bearish: 45.0,
            trade_direction: TradeDirection::Long,
            execution_model: ExecutionModel::SignalClose,
            allow_same_bar_exit: false,
            slippage_bps: 0.0,
            risk_cooldown_enabled: false,
            risk_cooldown_bars: 0,
        }
    }
}
// ============================================================================
// Trade Sizing Configuration
// ============================================================================
/// Trade sizing mode
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TradeSizingMode {
    #[default]
    Percent,
    Fixed,
    #[serde(rename = "kelly_criterion")]
    KellyCriterion,
}
/// Kelly-specific controls forwarded from the TypeScript capital settings.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AdvancedSizingConfig {
    #[serde(default)]
    pub kelly_fraction: KellyFraction,
    #[serde(default = "default_kelly_win_rate_cap")]
    pub kelly_win_rate_cap: f64,
    #[serde(default = "default_kelly_profit_factor_cap")]
    pub kelly_profit_factor_cap: f64,
}
#[derive(Debug, Clone, Copy, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum KellyFraction {
    Full,
    #[default]
    Half,
    Quarter,
}
const fn default_kelly_win_rate_cap() -> f64 {
    0.7
}
const fn default_kelly_profit_factor_cap() -> f64 {
    1.2
}
impl Default for AdvancedSizingConfig {
    fn default() -> Self {
        Self {
            kelly_fraction: KellyFraction::Half,
            kelly_win_rate_cap: default_kelly_win_rate_cap(),
            kelly_profit_factor_cap: default_kelly_profit_factor_cap(),
        }
    }
}
/// Trade sizing configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TradeSizingConfig {
    pub mode: TradeSizingMode,
    pub fixed_trade_amount: f64,
    #[serde(default)]
    pub advanced_sizing: AdvancedSizingConfig,
}
impl Default for TradeSizingConfig {
    fn default() -> Self {
        Self {
            mode: TradeSizingMode::Percent,
            fixed_trade_amount: 1000.0,
            advanced_sizing: AdvancedSizingConfig::default(),
        }
    }
}
// ============================================================================
// Walk-Forward Types
// ============================================================================
/// Parameter range for optimization
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ParameterRange {
    pub name: String,
    pub min: f64,
    pub max: f64,
    pub step: f64,
}
/// Walk-forward configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WalkForwardConfig {
    pub optimization_window: usize,
    pub test_window: usize,
    pub step_size: usize,
    pub parameter_ranges: Vec<ParameterRange>,
    #[serde(default = "default_top_n")]
    pub top_n: usize,
    #[serde(default = "default_min_trades")]
    pub min_trades: u32,
}
const fn default_top_n() -> usize {
    5
}
const fn default_min_trades() -> u32 {
    20
}
/// Single walk-forward window result
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WalkForwardWindow {
    pub window_index: usize,
    pub optimization_start: usize,
    pub optimization_end: usize,
    pub test_start: usize,
    pub test_end: usize,
    pub optimized_params: StrategyParams,
    pub in_sample_result: BacktestResult,
    pub out_of_sample_result: BacktestResult,
    pub sharpe_degradation: f64,
    pub performance_degradation_percent: f64,
}
/// Complete walk-forward analysis result
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WalkForwardResult {
    pub windows: Vec<WalkForwardWindow>,
    pub combined_oos_trades: BacktestResult,
    pub avg_in_sample_sharpe: f64,
    pub avg_out_of_sample_sharpe: f64,
    pub walk_forward_efficiency: f64,
    pub robustness_score: f64,
    pub total_windows: usize,
    pub optimization_time_ms: u64,
    pub parameter_stability: f64,
}
// ============================================================================
// Finder Types
// ============================================================================
/// Finder search mode
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum FinderMode {
    #[default]
    Grid,
    Random,
}
/// Metric for sorting finder results
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum FinderMetric {
    NetProfit,
    ProfitFactor,
    SharpeRatio,
    WinRate,
    MaxDrawdownPercent,
    Expectancy,
    AverageGain,
    TotalTrades,
    NetProfitPercent,
}
/// Finder search options
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FinderOptions {
    pub mode: FinderMode,
    pub sort_priority: Vec<FinderMetric>,
    #[serde(default)]
    pub use_advanced_sort: bool,
    #[serde(default = "default_finder_top_n")]
    pub top_n: usize,
    #[serde(default = "default_finder_steps")]
    pub steps: usize,
    #[serde(default = "default_range_percent")]
    pub range_percent: f64,
    #[serde(default = "default_max_runs")]
    pub max_runs: usize,
    #[serde(default)]
    pub trade_filter_enabled: bool,
    #[serde(default = "default_min_trades")]
    pub min_trades: u32,
    #[serde(default = "default_max_trades")]
    pub max_trades: u32,
}
const fn default_finder_top_n() -> usize {
    10
}
const fn default_finder_steps() -> usize {
    5
}
const fn default_range_percent() -> f64 {
    50.0
}
const fn default_max_runs() -> usize {
    1000
}
const fn default_max_trades() -> u32 {
    u32::MAX
}
/// Single finder result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FinderResult {
    pub key: String,
    pub name: String,
    pub params: StrategyParams,
    pub result: BacktestResult,
}
// ============================================================================
// API Request/Response Types
// ============================================================================
/// Backtest request
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BacktestRequest {
    pub data: Vec<OHLCV>,
    pub signals: Vec<Signal>,
    pub initial_capital: f64,
    pub position_size_percent: f64,
    pub commission_percent: f64,
    #[serde(default)]
    pub settings: BacktestSettings,
    #[serde(default)]
    pub sizing: TradeSizingConfig,
}
/// Single item in a batch backtest request
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BatchBacktestItem {
    pub id: String,
    #[serde(default)]
    pub signals: Vec<Signal>,
    /// Compact signal rows: time, direction (0=buy/1=sell), price, bar index (-1 when absent).
    #[serde(default)]
    pub packed_signals: Option<Vec<f64>>,
    #[serde(default)]
    pub settings: Option<BacktestSettings>,
}
/// Batch backtest request - runs multiple backtests in parallel
/// Uses shared OHLCV data to minimize network transfer
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BatchBacktestRequest {
    /// Shared OHLCV data for all backtests
    pub data: Vec<OHLCV>,
    /// List of signal sets to backtest
    pub items: Vec<BatchBacktestItem>,
    pub initial_capital: f64,
    pub position_size_percent: f64,
    pub commission_percent: f64,
    #[serde(default)]
    pub base_settings: BacktestSettings,
    #[serde(default)]
    pub sizing: TradeSizingConfig,
    /// When true, omit heavy payloads (trades, equity curve) from results
    #[serde(default)]
    pub compact: bool,
    /// Optional last candle time used by the Asset Opportunity summary route
    /// to apply endpoint selection without returning trade history.
    #[serde(default)]
    pub last_data_time: Option<Time>,
}
/// One independently priced asset in a multi-asset batch request.
///
/// Keeping the OHLCV series at the workload boundary lets the server build
/// one market index per asset while the HTTP request amortizes routing and
/// JSON overhead across many assets.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MultiAssetBatchWorkload {
    pub id: String,
    #[serde(default)]
    pub data: Vec<OHLCV>,
    /// Compact row-major OHLCV values: time, open, high, low, close, volume.
    /// Used by the multi-asset transport to avoid repeating JSON object keys.
    #[serde(default)]
    pub packed_data: Option<Vec<f64>>,
    pub items: Vec<BatchBacktestItem>,
    #[serde(default)]
    pub last_data_time: Option<Time>,
    #[serde(default)]
    pub cache_id: Option<String>,
    #[serde(default)]
    pub data_end_index: Option<usize>,
}
/// Multi-asset batch request. Each workload has its own OHLCV data and item
/// set; the execution and sizing settings are shared across workloads.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MultiAssetBatchBacktestRequest {
    pub workloads: Vec<MultiAssetBatchWorkload>,
    pub initial_capital: f64,
    pub position_size_percent: f64,
    pub commission_percent: f64,
    #[serde(default)]
    pub base_settings: BacktestSettings,
    #[serde(default)]
    pub sizing: TradeSizingConfig,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MultiAssetCacheWorkload {
    pub id: String,
    #[serde(default)]
    pub data: Vec<OHLCV>,
    #[serde(default)]
    pub packed_data: Option<Vec<f64>>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MultiAssetCacheRequest {
    pub workloads: Vec<MultiAssetCacheWorkload>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MultiAssetCacheResult {
    pub id: String,
    pub cache_id: String,
    pub bar_count: usize,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MultiAssetCacheResponse {
    pub datasets: Vec<MultiAssetCacheResult>,
}
/// Single result in a batch backtest response
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BatchBacktestResultItem {
    pub id: String,
    pub result: BacktestResult,
}
/// Batch backtest response
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BatchBacktestResponse {
    pub results: Vec<BatchBacktestResultItem>,
    pub processing_time_ms: u64,
}
/// Walk-forward request
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WalkForwardRequest {
    pub data: Vec<OHLCV>,
    pub strategy_name: String,
    pub base_params: StrategyParams,
    pub initial_capital: f64,
    pub position_size_percent: f64,
    pub commission_percent: f64,
    pub settings: BacktestSettings,
    pub config: WalkForwardConfig,
}
/// Finder request
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FinderRequest {
    pub data: Vec<OHLCV>,
    pub strategy_name: String,
    pub base_params: StrategyParams,
    pub initial_capital: f64,
    pub position_size_percent: f64,
    pub commission_percent: f64,
    pub settings: BacktestSettings,
    pub options: FinderOptions,
}
/// Progress update for WebSocket streaming
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProgressUpdate {
    pub percent: f64,
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub current_window: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_windows: Option<usize>,
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_ohlcv_typical_price() {
        let candle = OHLCV::new(1000, 100.0, 110.0, 95.0, 105.0, 1000.0);
        let expected = (110.0 + 95.0 + 105.0) / 3.0;
        assert!((candle.typical_price() - expected).abs() < 1e-10);
    }
    #[test]
    fn test_signal_creation() {
        let buy = Signal::buy(1000, 100.0).with_reason("Test signal");
        assert_eq!(buy.signal_type, SignalType::Buy);
        assert_eq!(buy.reason, Some("Test signal".to_string()));
    }
    #[test]
    fn test_trade_is_winner() {
        let trade = Trade {
            id: 1,
            trade_type: TradeType::Long,
            entry_time: 1000,
            entry_price: 100.0,
            exit_time: 2000,
            exit_price: 110.0,
            pnl: 10.0,
            pnl_percent: 10.0,
            size: 1.0,
            fees: Some(0.1),
        };
        assert!(trade.is_winner());
    }
    #[test]
    fn test_backtest_settings_default() {
        let settings = BacktestSettings::default();
        assert_eq!(settings.atr_period, 14);
        assert_eq!(settings.stop_loss_atr, 0.0);
        assert_eq!(settings.take_profit_atr, 0.0);
        assert!(!settings.stop_loss_enabled);
        assert!(!settings.take_profit_enabled);
        assert_eq!(settings.trend_ema_period, 0);
        assert_eq!(settings.adx_max, 0.0);
        assert_eq!(settings.confirm_lookback, 1);
        assert_eq!(settings.volume_multiplier, 1.0);
        assert_eq!(settings.rsi_bullish, 55.0);
        assert_eq!(settings.rsi_bearish, 45.0);
        assert_eq!(settings.trade_direction, TradeDirection::Long);
    }
    #[test]
    fn test_json_serialization() {
        let candle = OHLCV::new(1000, 100.0, 110.0, 95.0, 105.0, 1000.0);
        let json = serde_json::to_string(&candle).unwrap();
        let parsed: OHLCV = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.time, candle.time);
        assert_eq!(parsed.close, candle.close);
    }
}
