import type { EnsembleSignalRecipe } from "./settings-model";

export function slugifyEnsembleSignalRecipeName(name: string): string {
    const slug = name
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "");
    return slug || "ensemble-signal-recipe";
}

export function resolveExternalSignalSymbol(symbol: string): string | null {
    const normalized = symbol.trim().toUpperCase();
    if (normalized === "BTCUSDT") return "btc";
    if (normalized === "ETHUSDT") return "eth";
    if (normalized === "SOLUSDT") return "sol";
    if (normalized === "XRPUSDT") return "xrp";
    return null;
}

export function buildEnsembleRecipeBotEnvSnippet(
    recipe: EnsembleSignalRecipe,
    slug: string,
    botSymbol: string
): string {
    return [
        `# ${recipe.name}`,
        "# Replace <STRATEGY_FINDER_ROOT> with your local Strategies-Finder path, using forward slashes, or run the downloaded script and use the generated .bot.env file.",
        "TRADING_MODE=external_signal",
        "DRY_RUN=true",
        `EXTERNAL_SIGNAL_SYMBOL=${botSymbol}`,
        `EXTERNAL_SIGNAL_FILE=<STRATEGY_FINDER_ROOT>/signals/ensemble-bridge/${slug}.latest-entry-signal.json`,
        "EXTERNAL_SIGNAL_POLL_INTERVAL_MS=2000",
        "EXTERNAL_SIGNAL_MAX_SIGNAL_LAG_SECS=600",
        "EXTERNAL_SIGNAL_LOG_FILE=logs/external_signal.jsonl",
        `EXTERNAL_SIGNAL_REFRESH_SCRIPT=<STRATEGY_FINDER_ROOT>/signals/ensemble-bridge/${slug}.refresh.ps1`,
        "EXTERNAL_SIGNAL_REFRESH_DELAY_SECS=2",
        "EXTERNAL_SIGNAL_REFRESH_TIMEOUT_SECS=120",
        "MULTI_WALLET_NON_INTERACTIVE=true",
        "WALLET_1_STRATEGY=external_signal",
    ].join("\r\n");
}

export function buildEnsembleRecipeBridgeScript(
    recipe: EnsembleSignalRecipe,
    slug: string,
    botSymbol: string
): string {
    const recipeJson = JSON.stringify(recipe, null, 2);
    const recipeName = toPowerShellSingleQuoted(recipe.name);
    const symbol = toPowerShellSingleQuoted(recipe.symbol);
    const interval = toPowerShellSingleQuoted(recipe.interval);
    const slugLiteral = toPowerShellSingleQuoted(slug);
    const botSymbolLiteral = toPowerShellSingleQuoted(botSymbol);
    const refreshScriptBody = [
        "param(",
        "    [string]$StrategyFinderRoot = '',",
        "    [int]$Bars = 500,",
        "    [int]$FreshnessBars = 0",
        ")",
        "",
        "$ErrorActionPreference = 'Stop'",
        "",
        "function Test-StrategyFinderRoot {",
        "    param([string]$CandidatePath)",
        "    if ([string]::IsNullOrWhiteSpace($CandidatePath)) { return $false }",
        "    $resolved = Resolve-Path -LiteralPath $CandidatePath -ErrorAction SilentlyContinue",
        "    if (-not $resolved) { return $false }",
        "    $root = $resolved.Path",
        "    return (Test-Path (Join-Path $root 'package.json')) -and (Test-Path (Join-Path $root 'scripts\\export-latest-ensemble-entry-signal.ts'))",
        "}",
        "",
        "function Resolve-StrategyFinderRoot {",
        "    param([string]$ExplicitPath)",
        "    if (-not [string]::IsNullOrWhiteSpace($ExplicitPath)) {",
        "        if (Test-StrategyFinderRoot $ExplicitPath) {",
        "            return (Resolve-Path -LiteralPath $ExplicitPath).Path",
        "        }",
        "        throw ('Invalid StrategyFinderRoot: ' + $ExplicitPath)",
        "    }",
        "    if ([string]::IsNullOrWhiteSpace($PSScriptRoot)) {",
        "        throw 'PSScriptRoot is empty. Pass -StrategyFinderRoot explicitly.'",
        "    }",
        "    $signalsDir = Split-Path -Path $PSScriptRoot -Parent",
        "    if ([string]::IsNullOrWhiteSpace($signalsDir)) {",
        "        throw 'Could not resolve signals directory from ensemble bridge refresh script.'",
        "    }",
        "    $candidateRoot = Split-Path -Path $signalsDir -Parent",
        "    if (Test-StrategyFinderRoot $candidateRoot) {",
        "        return (Resolve-Path -LiteralPath $candidateRoot).Path",
        "    }",
        "    throw ('Could not resolve Strategies-Finder root from ' + $PSScriptRoot + '. Pass -StrategyFinderRoot explicitly.')",
        "}",
        "",
        `$Symbol = ${symbol}`,
        `$Interval = ${interval}`,
        `$RecipeSlug = ${slugLiteral}`,
        "",
        "$ResolvedRoot = Resolve-StrategyFinderRoot -ExplicitPath $StrategyFinderRoot",
        "$BridgeDir = Join-Path $ResolvedRoot 'signals\\ensemble-bridge'",
        "$RecipePath = Join-Path $BridgeDir ($RecipeSlug + '.recipe.json')",
        "$SignalPath = Join-Path $BridgeDir ($RecipeSlug + '.latest-entry-signal.json')",
        "",
        "$npmCommand = Get-Command npm.cmd -ErrorAction SilentlyContinue",
        "if (-not $npmCommand) {",
        "    $npmCommand = Get-Command npm -ErrorAction SilentlyContinue",
        "}",
        "if (-not $npmCommand) {",
        "    throw 'npm was not found on PATH.'",
        "}",
        "",
        "Push-Location $ResolvedRoot",
        "try {",
        "    & $npmCommand.Source run signal:export:ensemble -- --recipe-file $RecipePath --symbol $Symbol --interval $Interval --bars $Bars --freshness-bars $FreshnessBars --out $SignalPath",
        "    if ($LASTEXITCODE -ne 0) {",
        "        throw ('signal:export:ensemble exited with code ' + $LASTEXITCODE)",
        "    }",
        "}",
        "finally {",
        "    Pop-Location",
        "}",
        "",
        "Write-Host ('Signal refreshed: ' + $SignalPath)",
        "",
    ].join("\r\n");

    return [
        "param(",
        "    [string]$StrategyFinderRoot = '',",
        "    [int]$Bars = 500,",
        "    [int]$FreshnessBars = 0",
        ")",
        "",
        "$ErrorActionPreference = 'Stop'",
        "",
        `$RecipeName = ${recipeName}`,
        `$RecipeSlug = ${slugLiteral}`,
        `$Symbol = ${symbol}`,
        `$Interval = ${interval}`,
        `$BotSymbol = ${botSymbolLiteral}`,
        "",
        "function Test-StrategyFinderRoot {",
        "    param([string]$CandidatePath)",
        "    if ([string]::IsNullOrWhiteSpace($CandidatePath)) { return $false }",
        "    $resolved = Resolve-Path -LiteralPath $CandidatePath -ErrorAction SilentlyContinue",
        "    if (-not $resolved) { return $false }",
        "    $root = $resolved.Path",
        "    return (Test-Path (Join-Path $root 'package.json')) -and (Test-Path (Join-Path $root 'scripts\\export-latest-ensemble-entry-signal.ts'))",
        "}",
        "",
        "function Find-StrategyFinderRootFromSeed {",
        "    param([string]$SeedPath)",
        "    if ([string]::IsNullOrWhiteSpace($SeedPath)) { return $null }",
        "    $current = $SeedPath",
        "    while (-not [string]::IsNullOrWhiteSpace($current)) {",
        "        if (Test-StrategyFinderRoot $current) {",
        "            return (Resolve-Path -LiteralPath $current).Path",
        "        }",
        "        $parent = Split-Path -Path $current -Parent",
        "        if ([string]::IsNullOrWhiteSpace($parent) -or $parent -eq $current) {",
        "            break",
        "        }",
        "        $current = $parent",
        "    }",
        "    return $null",
        "}",
        "",
        "function Resolve-StrategyFinderRoot {",
        "    param([string]$ExplicitPath)",
        "    $candidates = @()",
        "    if (-not [string]::IsNullOrWhiteSpace($ExplicitPath)) { $candidates += $ExplicitPath }",
        "    if (-not [string]::IsNullOrWhiteSpace($env:STRATEGY_FINDER_ROOT)) { $candidates += $env:STRATEGY_FINDER_ROOT }",
        "    if (-not [string]::IsNullOrWhiteSpace($PSScriptRoot)) { $candidates += $PSScriptRoot }",
        "    $candidates += (Get-Location).Path",
        "    $userProfile = [Environment]::GetFolderPath('UserProfile')",
        "    if (-not [string]::IsNullOrWhiteSpace($userProfile)) {",
        "        $candidates += (Join-Path $userProfile 'Documents\\Repo\\Experimental\\lightweight-charts\\debug\\playground\\Strategies-Finder')",
        "        $candidates += (Join-Path $userProfile 'Documents\\Strategies-Finder')",
        "    }",
        "    foreach ($candidate in $candidates) {",
        "        $resolved = Find-StrategyFinderRootFromSeed $candidate",
        "        if (-not [string]::IsNullOrWhiteSpace($resolved)) {",
        "            return $resolved",
        "        }",
        "    }",
        "    throw 'Could not locate the Strategies-Finder repo. Run this script from the repo, pass -StrategyFinderRoot, or set STRATEGY_FINDER_ROOT.'",
        "}",
        "",
        "function Write-Utf8NoBomFile {",
        "    param(",
        "        [string]$Path,",
        "        [string]$Content",
        "    )",
        "    $encoding = New-Object System.Text.UTF8Encoding($false)",
        "    [System.IO.File]::WriteAllText($Path, $Content, $encoding)",
        "}",
        "",
        "$StrategyFinderRoot = Resolve-StrategyFinderRoot -ExplicitPath $StrategyFinderRoot",
        "$BridgeDir = Join-Path $StrategyFinderRoot 'signals\\ensemble-bridge'",
        "$RecipePath = Join-Path $BridgeDir ($RecipeSlug + '.recipe.json')",
        "$SignalPath = Join-Path $BridgeDir ($RecipeSlug + '.latest-entry-signal.json')",
        "$RefreshScriptPath = Join-Path $BridgeDir ($RecipeSlug + '.refresh.ps1')",
        "$BotEnvPath = Join-Path $BridgeDir ($RecipeSlug + '.bot.env')",
        "$SignalPathForEnv = $SignalPath -replace '\\\\', '/'",
        "$RefreshScriptPathForEnv = $RefreshScriptPath -replace '\\\\', '/'",
        "New-Item -ItemType Directory -Path $BridgeDir -Force | Out-Null",
        "",
        "$RecipeJson = @'",
        recipeJson,
        "'@",
        "",
        "Write-Utf8NoBomFile -Path $RecipePath -Content $RecipeJson",
        "",
        "$RefreshScript = @'",
        refreshScriptBody,
        "'@",
        "",
        "Write-Utf8NoBomFile -Path $RefreshScriptPath -Content $RefreshScript",
        "",
        '$BotEnv = @"',
        "TRADING_MODE=external_signal",
        "DRY_RUN=true",
        "EXTERNAL_SIGNAL_SYMBOL=$BotSymbol",
        "EXTERNAL_SIGNAL_FILE=$SignalPathForEnv",
        "EXTERNAL_SIGNAL_POLL_INTERVAL_MS=2000",
        "EXTERNAL_SIGNAL_MAX_SIGNAL_LAG_SECS=600",
        "EXTERNAL_SIGNAL_LOG_FILE=logs/external_signal.jsonl",
        "EXTERNAL_SIGNAL_REFRESH_SCRIPT=$RefreshScriptPathForEnv",
        "EXTERNAL_SIGNAL_REFRESH_DELAY_SECS=2",
        "EXTERNAL_SIGNAL_REFRESH_TIMEOUT_SECS=120",
        "MULTI_WALLET_NON_INTERACTIVE=true",
        "WALLET_1_STRATEGY=external_signal",
        '"@',
        "Write-Utf8NoBomFile -Path $BotEnvPath -Content $BotEnv",
        "",
        "& $RefreshScriptPath -StrategyFinderRoot $StrategyFinderRoot -Bars $Bars -FreshnessBars $FreshnessBars",
        "",
        "Write-Host ('Ensemble recipe bridge ready for ' + $RecipeName)",
        "Write-Host ('Signal file: ' + $SignalPath)",
        "Write-Host ('Refresh script: ' + $RefreshScriptPath)",
        "Write-Host ('Bot env snippet: ' + $BotEnvPath)",
        "",
    ].join("\r\n");
}

function toPowerShellSingleQuoted(value: string): string {
    return `'${value.replace(/'/g, "''")}'`;
}
