import { getRequiredElement } from "./dom-utils";

export const PORTFOLIO_LAB_REQUIRED_IDS = [
    "portfolioTab",
    "portfolioEmpty",
    "portfolioContent",
    "portfolioSymbolList",
    "portfolioBenchmarkSymbol",
    "portfolioAnchorSymbol",
    "portfolioLookbackBars",
    "portfolioWindowMode",
    "portfolioConsensusLagBars",
    "portfolioConsensusMinSamples",
    "portfolioUseCurrentBtn",
    "portfolioFillMajorsBtn",
    "portfolioRunBtn",
    "portfolioStatus",
    "portfolioResults",
    "portfolioSummary",
    "portfolioLiveContextSection",
    "portfolioLiveContextSummary",
    "portfolioLiveContextDetails",
    "portfolioForecastSection",
    "portfolioForecastSummary",
    "portfolioForecastDetails",
    "portfolioForecastTableBody",
    "portfolioInsightSection",
    "portfolioInsights",
    "portfolioExecutionSection",
    "portfolioExecutionSummary",
    "portfolioConsensusSection",
    "portfolioConsensusSummary",
    "portfolioConsensusTableBody",
    "portfolioBreadthMinAgree",
    "portfolioMaxOppose",
    "portfolioRunBreadthBacktestBtn",
    "portfolioRunFilterBacktestBtn",
    "portfolioRunBreadthSweepBtn",
    "portfolioRunOppositionSweepBtn",
    "portfolioBreadthSweepSection",
    "portfolioBreadthSweepTableBody",
    "portfolioOppositionSweepSection",
    "portfolioOppositionSweepTableBody",
    "portfolioRankingSection",
    "portfolioRankingSummary",
    "portfolioRankingTableBody",
    "portfolioSizingSection",
    "portfolioSizingSummary",
    "portfolioSizingTableBody",
    "portfolioMatrixSection",
    "portfolioCorrelationMatrix",
    "portfolioPairsTableBody",
    "portfolioIntervalBadge",
    "portfolioStrategyBadge",
] as const;

export function createPortfolioLabDom() {
    return {
        portfolioTab: getRequiredElement("portfolioTab"),
        portfolioEmpty: getRequiredElement("portfolioEmpty"),
        portfolioContent: getRequiredElement("portfolioContent"),
        portfolioSymbolList: getRequiredElement<HTMLTextAreaElement>("portfolioSymbolList"),
        portfolioBenchmarkSymbol: getRequiredElement<HTMLInputElement>("portfolioBenchmarkSymbol"),
        portfolioAnchorSymbol: getRequiredElement<HTMLInputElement>("portfolioAnchorSymbol"),
        portfolioLookbackBars: getRequiredElement<HTMLInputElement>("portfolioLookbackBars"),
        portfolioWindowMode: getRequiredElement<HTMLSelectElement>("portfolioWindowMode"),
        portfolioConsensusLagBars: getRequiredElement<HTMLInputElement>("portfolioConsensusLagBars"),
        portfolioConsensusMinSamples: getRequiredElement<HTMLInputElement>("portfolioConsensusMinSamples"),
        portfolioUseCurrentBtn: getRequiredElement<HTMLButtonElement>("portfolioUseCurrentBtn"),
        portfolioFillMajorsBtn: getRequiredElement<HTMLButtonElement>("portfolioFillMajorsBtn"),
        portfolioRunBtn: getRequiredElement<HTMLButtonElement>("portfolioRunBtn"),
        portfolioStatus: getRequiredElement("portfolioStatus"),
        portfolioResults: getRequiredElement("portfolioResults"),
        portfolioSummary: getRequiredElement("portfolioSummary"),
        portfolioLiveContextSection: getRequiredElement("portfolioLiveContextSection"),
        portfolioLiveContextSummary: getRequiredElement("portfolioLiveContextSummary"),
        portfolioLiveContextDetails: getRequiredElement("portfolioLiveContextDetails"),
        portfolioForecastSection: getRequiredElement("portfolioForecastSection"),
        portfolioForecastSummary: getRequiredElement("portfolioForecastSummary"),
        portfolioForecastDetails: getRequiredElement("portfolioForecastDetails"),
        portfolioForecastTableBody: getRequiredElement("portfolioForecastTableBody"),
        portfolioInsightSection: getRequiredElement("portfolioInsightSection"),
        portfolioInsights: getRequiredElement("portfolioInsights"),
        portfolioExecutionSection: getRequiredElement("portfolioExecutionSection"),
        portfolioExecutionSummary: getRequiredElement("portfolioExecutionSummary"),
        portfolioConsensusSection: getRequiredElement("portfolioConsensusSection"),
        portfolioConsensusSummary: getRequiredElement("portfolioConsensusSummary"),
        portfolioConsensusTableBody: getRequiredElement("portfolioConsensusTableBody"),
        portfolioBreadthMinAgree: getRequiredElement<HTMLInputElement>("portfolioBreadthMinAgree"),
        portfolioMaxOppose: getRequiredElement<HTMLInputElement>("portfolioMaxOppose"),
        portfolioRunBreadthBacktestBtn: getRequiredElement<HTMLButtonElement>("portfolioRunBreadthBacktestBtn"),
        portfolioRunFilterBacktestBtn: getRequiredElement<HTMLButtonElement>("portfolioRunFilterBacktestBtn"),
        portfolioRunBreadthSweepBtn: getRequiredElement<HTMLButtonElement>("portfolioRunBreadthSweepBtn"),
        portfolioRunOppositionSweepBtn: getRequiredElement<HTMLButtonElement>("portfolioRunOppositionSweepBtn"),
        portfolioBreadthSweepSection: getRequiredElement("portfolioBreadthSweepSection"),
        portfolioBreadthSweepTableBody: getRequiredElement("portfolioBreadthSweepTableBody"),
        portfolioOppositionSweepSection: getRequiredElement("portfolioOppositionSweepSection"),
        portfolioOppositionSweepTableBody: getRequiredElement("portfolioOppositionSweepTableBody"),
        portfolioRankingSection: getRequiredElement("portfolioRankingSection"),
        portfolioRankingSummary: getRequiredElement("portfolioRankingSummary"),
        portfolioRankingTableBody: getRequiredElement("portfolioRankingTableBody"),
        portfolioSizingSection: getRequiredElement("portfolioSizingSection"),
        portfolioSizingSummary: getRequiredElement("portfolioSizingSummary"),
        portfolioSizingTableBody: getRequiredElement("portfolioSizingTableBody"),
        portfolioMatrixSection: getRequiredElement("portfolioMatrixSection"),
        portfolioCorrelationMatrix: getRequiredElement("portfolioCorrelationMatrix"),
        portfolioPairsTableBody: getRequiredElement("portfolioPairsTableBody"),
        portfolioIntervalBadge: getRequiredElement("portfolioIntervalBadge"),
        portfolioStrategyBadge: getRequiredElement("portfolioStrategyBadge"),
    };
}

export type PortfolioLabDom = ReturnType<typeof createPortfolioLabDom>;
