import { getRequiredElement } from "./dom-utils";

export const ENSEMBLE_LAB_REQUIRED_IDS = [
    "ensembleTab",
    "ensembleEmpty",
    "ensembleContent",
    "ensembleTargetPicker",
    "ensembleTargetSelect",
    "ensembleTargetButton",
    "ensembleTargetMenu",
    "ensembleTargetSearch",
    "ensembleTargetList",
    "ensembleTargetPickerEmptyState",
    "ensembleTargetSummary",
    "ensembleMinSamples",
    "ensembleSymbolBadge",
    "ensembleIntervalBadge",
    "ensembleContextSearch",
    "ensembleContextFamilyFilter",
    "ensembleContextSelectAll",
    "ensembleContextSelectNone",
    "ensembleContextInvertVisible",
    "ensembleContextSelectVisible",
    "ensembleContextSelectSameFamily",
    "ensembleContextExcludeSameFamily",
    "ensembleContextSummary",
    "ensembleContextList",
    "ensembleContextHelper",
    "ensembleContextEmptyState",
    "ensembleRefreshConfigsBtn",
    "ensembleRunBtn",
    "ensembleRunPolymarketBtn",
    "ensembleLoadConflictBacktestBtn",
    "ensembleLoadBestVetoBacktestBtn",
    "ensembleSaveConflictRecipeBtn",
    "ensembleSaveBestVetoRecipeBtn",
    "ensembleStatus",
    "ensembleResults",
    "ensembleSummary",
    "ensembleCurrentContextSection",
    "ensembleCurrentContextSummary",
    "ensembleCurrentContextDetails",
    "ensembleHistoricalOddsSection",
    "ensembleHistoricalOddsSummary",
    "ensembleHistoricalOddsTableBody",
    "ensemblePolymarketSection",
    "ensemblePolymarketEmpty",
    "ensemblePolymarketStatus",
    "ensembleSignalRecipeSelect",
    "ensembleSignalRecipeDownloadScriptBtn",
    "ensembleSignalRecipeCopyEnvBtn",
    "ensembleSignalRecipeDeleteBtn",
    "ensembleSignalRecipeStatus",
    "ensemblePolymarketSummary",
    "ensemblePolymarketAgreement",
    "ensemblePolymarketTableBody",
    "ensemblePolymarketVetoSummary",
    "ensemblePolymarketVetoTableBody",
    "ensembleBuilderSection",
    "ensembleBuilderSummary",
    "ensembleBuilderTableBody",
    "ensembleDiagnosticsSection",
    "ensembleContributionSection",
    "ensembleContributionSummary",
    "ensembleContributionTableBody",
    "ensembleReplacementSection",
    "ensembleReplacementSummary",
    "ensembleReplacementTableBody",
    "ensembleRadarSection",
    "ensembleRadarContent",
] as const;

export function createEnsembleLabDom() {
    return {
        ensembleTab: getRequiredElement("ensembleTab"),
        ensembleEmpty: getRequiredElement("ensembleEmpty"),
        ensembleContent: getRequiredElement("ensembleContent"),
        ensembleTargetPicker: getRequiredElement("ensembleTargetPicker"),
        ensembleTargetSelect: getRequiredElement<HTMLSelectElement>("ensembleTargetSelect"),
        ensembleTargetButton: getRequiredElement<HTMLButtonElement>("ensembleTargetButton"),
        ensembleTargetMenu: getRequiredElement("ensembleTargetMenu"),
        ensembleTargetSearch: getRequiredElement<HTMLInputElement>("ensembleTargetSearch"),
        ensembleTargetList: getRequiredElement("ensembleTargetList"),
        ensembleTargetPickerEmptyState: getRequiredElement("ensembleTargetPickerEmptyState"),
        ensembleTargetSummary: getRequiredElement("ensembleTargetSummary"),
        ensembleMinSamples: getRequiredElement<HTMLInputElement>("ensembleMinSamples"),
        ensembleSymbolBadge: getRequiredElement("ensembleSymbolBadge"),
        ensembleIntervalBadge: getRequiredElement("ensembleIntervalBadge"),
        ensembleContextSearch: getRequiredElement<HTMLInputElement>("ensembleContextSearch"),
        ensembleContextFamilyFilter: getRequiredElement<HTMLSelectElement>("ensembleContextFamilyFilter"),
        ensembleContextSelectAll: getRequiredElement<HTMLButtonElement>("ensembleContextSelectAll"),
        ensembleContextSelectNone: getRequiredElement<HTMLButtonElement>("ensembleContextSelectNone"),
        ensembleContextInvertVisible: getRequiredElement<HTMLButtonElement>("ensembleContextInvertVisible"),
        ensembleContextSelectVisible: getRequiredElement<HTMLButtonElement>("ensembleContextSelectVisible"),
        ensembleContextSelectSameFamily: getRequiredElement<HTMLButtonElement>("ensembleContextSelectSameFamily"),
        ensembleContextExcludeSameFamily: getRequiredElement<HTMLButtonElement>("ensembleContextExcludeSameFamily"),
        ensembleContextSummary: getRequiredElement("ensembleContextSummary"),
        ensembleContextList: getRequiredElement("ensembleContextList"),
        ensembleContextHelper: getRequiredElement("ensembleContextHelper"),
        ensembleContextEmptyState: getRequiredElement("ensembleContextEmptyState"),
        ensembleRefreshConfigsBtn: getRequiredElement<HTMLButtonElement>("ensembleRefreshConfigsBtn"),
        ensembleRunBtn: getRequiredElement<HTMLButtonElement>("ensembleRunBtn"),
        ensembleRunPolymarketBtn: getRequiredElement<HTMLButtonElement>("ensembleRunPolymarketBtn"),
        ensembleLoadConflictBacktestBtn: getRequiredElement<HTMLButtonElement>("ensembleLoadConflictBacktestBtn"),
        ensembleLoadBestVetoBacktestBtn: getRequiredElement<HTMLButtonElement>("ensembleLoadBestVetoBacktestBtn"),
        ensembleSaveConflictRecipeBtn: getRequiredElement<HTMLButtonElement>("ensembleSaveConflictRecipeBtn"),
        ensembleSaveBestVetoRecipeBtn: getRequiredElement<HTMLButtonElement>("ensembleSaveBestVetoRecipeBtn"),
        ensembleStatus: getRequiredElement("ensembleStatus"),
        ensembleResults: getRequiredElement("ensembleResults"),
        ensembleSummary: getRequiredElement("ensembleSummary"),
        ensembleCurrentContextSection: getRequiredElement("ensembleCurrentContextSection"),
        ensembleCurrentContextSummary: getRequiredElement("ensembleCurrentContextSummary"),
        ensembleCurrentContextDetails: getRequiredElement("ensembleCurrentContextDetails"),
        ensembleHistoricalOddsSection: getRequiredElement("ensembleHistoricalOddsSection"),
        ensembleHistoricalOddsSummary: getRequiredElement("ensembleHistoricalOddsSummary"),
        ensembleHistoricalOddsTableBody: getRequiredElement("ensembleHistoricalOddsTableBody"),
        ensemblePolymarketSection: getRequiredElement("ensemblePolymarketSection"),
        ensemblePolymarketEmpty: getRequiredElement("ensemblePolymarketEmpty"),
        ensemblePolymarketStatus: getRequiredElement("ensemblePolymarketStatus"),
        ensembleSignalRecipeSelect: getRequiredElement<HTMLSelectElement>("ensembleSignalRecipeSelect"),
        ensembleSignalRecipeDownloadScriptBtn: getRequiredElement<HTMLButtonElement>("ensembleSignalRecipeDownloadScriptBtn"),
        ensembleSignalRecipeCopyEnvBtn: getRequiredElement<HTMLButtonElement>("ensembleSignalRecipeCopyEnvBtn"),
        ensembleSignalRecipeDeleteBtn: getRequiredElement<HTMLButtonElement>("ensembleSignalRecipeDeleteBtn"),
        ensembleSignalRecipeStatus: getRequiredElement("ensembleSignalRecipeStatus"),
        ensemblePolymarketSummary: getRequiredElement("ensemblePolymarketSummary"),
        ensemblePolymarketAgreement: getRequiredElement("ensemblePolymarketAgreement"),
        ensemblePolymarketTableBody: getRequiredElement("ensemblePolymarketTableBody"),
        ensemblePolymarketVetoSummary: getRequiredElement("ensemblePolymarketVetoSummary"),
        ensemblePolymarketVetoTableBody: getRequiredElement("ensemblePolymarketVetoTableBody"),
        ensembleBuilderSection: getRequiredElement("ensembleBuilderSection"),
        ensembleBuilderSummary: getRequiredElement("ensembleBuilderSummary"),
        ensembleBuilderTableBody: getRequiredElement("ensembleBuilderTableBody"),
        ensembleDiagnosticsSection: getRequiredElement<HTMLDetailsElement>("ensembleDiagnosticsSection"),
        ensembleContributionSection: getRequiredElement("ensembleContributionSection"),
        ensembleContributionSummary: getRequiredElement("ensembleContributionSummary"),
        ensembleContributionTableBody: getRequiredElement("ensembleContributionTableBody"),
        ensembleReplacementSection: getRequiredElement("ensembleReplacementSection"),
        ensembleReplacementSummary: getRequiredElement("ensembleReplacementSummary"),
        ensembleReplacementTableBody: getRequiredElement("ensembleReplacementTableBody"),
        ensembleRadarSection: getRequiredElement("ensembleRadarSection"),
        ensembleRadarContent: getRequiredElement("ensembleRadarContent"),
    };
}

export type EnsembleLabDom = ReturnType<typeof createEnsembleLabDom>;
