/**
 * Server-safe in-sample candidate search for the Asset Opportunity scope.
 *
 * This leaf replaces the browser `runFinderExecution` in the server path so the
 * server runs a lean IS loop without the browser's strategy-plan/UI-callback
 * machinery (polymarket interception, confirmation filters, quick funnel, live
 * UI updates). It is NOT a bundle-safety workaround: the browser runner is
 * already safe for the Vite config bundle — its `finder-runner` import is
 * type-only and the backtest-engine modules do not reach `lightweight-charts` —
 * and `tests/vite-config-bundle.spec.ts` locks that invariant.
 *
 * This leaf reaches only server-safe modules (matching
 * `finder-runner-universe.ts`'s import hygiene): `../backtest-executor`,
 * `./finder-runner-core`, `./exit-strategy-param-prefix`, and
 * `./finder-manager-logic`.
 *
 * The function is a minimal IS search: it generates candidate params from the
 * injected param-space generator, executes each on the supplied historical
 * data, ranks them by the same sort priority, and returns the bounded top-K
 * result set. OOS validation is NOT done here — it is done by the caller
 * (Asset Opportunity server job) via the extracted candidate-OOS leaf.
 *
 * Determinism: the caller injects a deterministic per-asset seed through
 * `options.randomSeed`; the param-space generator consumes it unchanged, so
 * the same seed + same inputs produce the same candidate ordering.
 */

import type {
    BacktestResult,
    BacktestSettings,
    OHLCVData,
    Signal,
    StrategyParams,
} from "../../types/strategies";
import type { CapitalSettings } from "../../types/backtest";
import type { FinderOptions, FinderResult } from "../../types/finder";
import type { FinderSelectedStrategy } from "../finder-runner";
import type { CrossSymbolDataFetcher } from "../../cross-symbol-runtime";
import { resolveCapitalSettingsFromRaw } from "../../backtest-capital-settings";
import {
    createPreparedFinderStrategy,
    finderAssetSearchRequiresFullAnalytics,
    type FinderPreparedDataCache,
    normalizeFinderCandidateParamSets,
} from "../finder-runner-core";
import { withExitStrategyBaseParams, splitExitStrategyParams } from "../exit-strategy-param-prefix";
import { FinderResultRanker } from "../finder-result-ranker";
import { buildSelectionResult } from "../endpoint";
import { matchesFinderTradeCountFilter } from "../finder-manager-logic";
import { runAssetCandidateBacktest } from "../finder-asset-candidate-execution";

const ASSET_IS_SEARCH_YIELD_EVERY_RUNS = 256;
const ASSET_IS_SEARCH_YIELD_MIN_MS = 1000;

export interface ServerAssetIsSearchInput {
    ohlcvData: OHLCVData[];
    symbol: string;
    interval: string;
    options: FinderOptions;
    settings: BacktestSettings;
    capitalSettings: CapitalSettings;
    selectedStrategy: FinderSelectedStrategy;
    exitStrategyCandidates?: FinderSelectedStrategy[];
    generateParamSets: (defaultParams: StrategyParams, options: FinderOptions) => StrategyParams[];
    useRustEnginePreference?: boolean;
    dataFetcher?: CrossSymbolDataFetcher;
    isCancelled: () => boolean;
    yieldControl: () => Promise<void>;
    /**
     * When true, retain each candidate's generated signals and return them via
     * `signalsByCandidate` so the caller can run fresh-entry detection without
     * re-executing the top-K candidates. Only enable when the caller has proven
     * its recheck window is identical to this search's `ohlcvData`; the
     * retention is bounded by (param sets x signals) for one asset-strategy
     * pass and released once the caller finishes the asset.
     */
    retainSignals?: boolean;
}

export interface ServerAssetIsSearchOutput {
    results: FinderResult[];
    totalCandidatesEvaluated: number;
    candidateEvaluationsAttempted: number;
    candidateEvaluationsCompleted: number;
    candidateEvaluationFailures: number;
    /**
     * Parallel to `results` (same order): the signals generated by each
     * returned candidate. Present only when `retainSignals` was requested.
     */
    signalsByCandidate?: Signal[][];
    timingsMs: {
        total: number;
        parameterGeneration: number;
        backtest: number;
        yielding: number;
    };
    engineUsage: {
        rustAttemptedRuns: number;
        rustCompletedRuns: number;
        rustFallbackRuns: number;
        typescriptCompletedRuns: number;
        typescriptReasons: Array<{ reason: string; runs: number }>;
    };
}

/**
 * Run the in-sample search for one asset. Returns the top-N candidates
 * (N = `options.topN`) sorted by `options.sortPriority`.
 *
 * Mirrors the browser `runFinderExecution` candidate loop but uses
 * `executeBacktest` directly so the module stays server-safe. The caller
 * reserves the application candle and slices the historical window BEFORE
 * calling this function; the data passed here is the historical search data.
 */
export async function runServerAssetIsSearch(
    input: ServerAssetIsSearchInput,
): Promise<ServerAssetIsSearchOutput> {
    const { options, settings, capitalSettings, selectedStrategy } = input;
    const totalStartedAt = performance.now();
    const requiresFullAnalytics = finderAssetSearchRequiresFullAnalytics(options.sortPriority);
    if (selectedStrategy.strategy.crossSymbolConfig && !input.dataFetcher) {
        throw new Error(
            `Cross-symbol strategy "${selectedStrategy.name}" requires secondary asset data for Asset Opportunity.`,
        );
    }
    const preResolvedCapital = resolveCapitalSettingsFromRaw(
        capitalSettings as unknown as Record<string, unknown>,
    );
    const preparedDataCache: FinderPreparedDataCache = new WeakMap();
    let currentBacktestSettings = settings;
    const preparedStrategy = createPreparedFinderStrategy(
        selectedStrategy.key,
        selectedStrategy.strategy,
        preparedDataCache,
        () => currentBacktestSettings,
    );

    // Build the same base params the current-chart path uses.
    const parameterGenerationStartedAt = performance.now();
    const entryDefaults = selectedStrategy.strategy.defaultParams;
    const generated = input.generateParamSets(entryDefaults, options);
    const normalized = normalizeFinderCandidateParamSets(selectedStrategy.strategy, generated);
    const paramSets = normalized.length > 0
        ? normalized
        : [{ ...entryDefaults }];
    const parameterGenerationMs = performance.now() - parameterGenerationStartedAt;

    // Bounded top-K accumulation, mirroring the browser single-timeframe path
    // (FinderResultRanker). Keeping only the best `topN` candidates live means
    // the retained `results` set — and, when `retainSignals` is on, the
    // retained signal arrays — stay bounded by `topN` instead of by
    // `maxRuns` (up to 1,000 per asset pass). The ranker's comparator is
    // `compareFinderResults` with strict ordering, so the retained set is
    // identical to a full sort + slice; ties keep insertion order.
    const topKRanker = new FinderResultRanker(
        Math.max(1, options.topN),
        options.sortPriority,
        // Signals are keyed by candidate object identity; drop them when the
        // candidate falls out of the running top-K so the map cannot grow to
        // one entry per evaluated candidate.
        (evicted) => {
            signalsByResult.delete(evicted);
        },
    );
    // Keyed by candidate object identity so the signals survive the final
    // sort + top-N slice without an index bookkeeping pass. Bounded by the
    // ranker's eviction hook above.
    const signalsByResult = new Map<FinderResult, Signal[]>();
    let candidateEvaluationsAttempted = 0;
    let candidateEvaluationsCompleted = 0;
    let candidateEvaluationFailures = 0;
    let backtestMs = 0;
    let yieldingMs = 0;
    let evaluationsSinceYield = 0;
    let lastYieldAt = performance.now();
    let rustAttemptedRuns = 0;
    let rustCompletedRuns = 0;
    let rustFallbackRuns = 0;
    let typescriptCompletedRuns = 0;
    const typescriptReasonCounts = new Map<string, number>();

    for (let index = 0; index < paramSets.length; index++) {
        if (input.isCancelled()) break;
        candidateEvaluationsAttempted += 1;
        const entryParams = paramSets[index]!;

        // Exit Strategy Override: sample one exit strategy + param set per
        // entry candidate (deterministic via the seeded random in the caller).
        let exitStrategy: FinderSelectedStrategy | undefined;
        let exitParams: StrategyParams | undefined;
        if (input.exitStrategyCandidates && input.exitStrategyCandidates.length > 0) {
            // Deterministic sampling: pick by candidate index modulo the exit
            // candidate count. This mirrors the seeded `exitRandom` behavior of
            // the current-chart path without requiring a random source.
            const candidateIndex = index % input.exitStrategyCandidates.length;
            exitStrategy = input.exitStrategyCandidates[candidateIndex];
            const exitDefaults = exitStrategy.strategy.defaultParams;
            const exitGenerated = input.generateParamSets(exitDefaults, options);
            const exitNormalized = normalizeFinderCandidateParamSets(exitStrategy.strategy, exitGenerated);
            exitParams = exitNormalized.length > 0
                ? exitNormalized[index % exitNormalized.length]
                : { ...exitDefaults };
        }

        const combinedParams = exitParams
            ? withExitStrategyBaseParams(entryParams, exitParams)
            : entryParams;
        const candidateStartedAt = performance.now();
        try {
            // Shared candidate execution (risk overrides, exit override
            // injection, executor settings, and the compact endpoint-selection
            // / trade-history option matrix) lives in
            // `finder-asset-candidate-execution.ts`, kept in parity with the
            // browser runner's `executeAssetCandidate`.
            const output = await runAssetCandidateBacktest({
                data: input.ohlcvData,
                symbol: input.symbol,
                interval: input.interval,
                strategy: preparedStrategy,
                strategyKey: selectedStrategy.key,
                strategyParams: entryParams,
                riskOverrideParams: combinedParams,
                settings,
                capitalSettings,
                options,
                ...(exitStrategy
                    ? { exitOverride: { key: exitStrategy.key, params: exitParams ?? {} } }
                    : {}),
                ...(input.dataFetcher ? { dataFetcher: input.dataFetcher } : {}),
                useRustEnginePreference: input.useRustEnginePreference,
                // The caller has already supplied the historical closed
                // window. Keep its array identity stable so prepared Finder
                // data and executor-side caches can be reused per asset.
                closedCandleDataOverride: input.ohlcvData,
                needs: {
                    compact: true,
                    trades: false,
                    fullAnalytics: requiresFullAnalytics,
                    // Compact endpoint-adjusted selection scalars unless the
                    // resolved trade direction is "combined" (which retains
                    // trades instead) — the prior explicit branch, now
                    // centralized in the shared helper.
                    endpointSelection: "auto",
                },
            });
            // Keep the prepared-strategy settings provider aligned with the
            // settings the run actually used (risk overrides + exit override).
            currentBacktestSettings = output.backtestSettings;
            backtestMs += performance.now() - candidateStartedAt;
            candidateEvaluationsCompleted += 1;
            if (output.engineDiagnostics?.rustAttempted) rustAttemptedRuns += 1;
            if (output.engineUsed === "rust") rustCompletedRuns += 1;
            else {
                typescriptCompletedRuns += 1;
                const reason = output.engineDiagnostics?.typescriptReason ?? "TypeScript execution reason unavailable";
                typescriptReasonCounts.set(reason, (typescriptReasonCounts.get(reason) ?? 0) + 1);
                if (output.engineDiagnostics?.rustAttempted) rustFallbackRuns += 1;
            }

            const result: BacktestResult = output.result;
            const selection = output.endpointSelection ?? buildSelectionResult(
                result,
                input.ohlcvData[input.ohlcvData.length - 1]?.time ?? null,
                preResolvedCapital.initialCapital,
            );
            // The current-chart path builds a FinderResult through
            // `enrichFinderCandidate` (endpoint adjustment + selection result).
            // Keep the same endpoint-adjusted selection semantics here so
            // historical ranking and grading use the same capital-aware view.
            const candidate: FinderResult = {
                key: selectedStrategy.key,
                name: selectedStrategy.name,
                params: exitStrategy
                    ? splitExitStrategyParams(combinedParams).entryParams
                    : entryParams,
                ...(exitStrategy
                    ? {
                        exitStrategyKey: exitStrategy.key,
                        exitStrategyParams: exitParams ?? {},
                    }
                    : {}),
                result,
                selectionResult: selection.result,
                endpointAdjusted: selection.adjusted,
                endpointRemovedTrades: selection.removedTrades,
            };
            if (!matchesFinderTradeCountFilter(candidate.selectionResult.totalTrades, options)) {
                continue;
            }
            // Attach signals only when the candidate is actually retained:
            // a rejected candidate's signals would otherwise linger in the
            // map until the end of the asset pass. Evictions delete below.
            const retained = topKRanker.offer(candidate);
            if (input.retainSignals === true && retained) {
                signalsByResult.set(candidate, output.signals);
            }
        } catch {
            backtestMs += performance.now() - candidateStartedAt;
            candidateEvaluationFailures += 1;
            // Skip failed candidates; the caller counts failures in diagnostics.
            continue;
        }

        evaluationsSinceYield += 1;
        const now = performance.now();
        if (
            evaluationsSinceYield >= ASSET_IS_SEARCH_YIELD_EVERY_RUNS
            || now - lastYieldAt >= ASSET_IS_SEARCH_YIELD_MIN_MS
        ) {
            evaluationsSinceYield = 0;
            lastYieldAt = now;
            const yieldingStartedAt = performance.now();
            await input.yieldControl();
            yieldingMs += performance.now() - yieldingStartedAt;
        }
    }

    const topN = Math.max(1, options.topN);
    const topK = topKRanker.toSortedArray(topN);
    return {
        results: topK,
        totalCandidatesEvaluated: paramSets.length,
        candidateEvaluationsAttempted,
        candidateEvaluationsCompleted,
        candidateEvaluationFailures,
        ...(input.retainSignals === true
            ? { signalsByCandidate: topK.map((candidate) => signalsByResult.get(candidate) ?? []) }
            : {}),
        timingsMs: {
            total: performance.now() - totalStartedAt,
            parameterGeneration: parameterGenerationMs,
            backtest: backtestMs,
            yielding: yieldingMs,
        },
        engineUsage: {
            rustAttemptedRuns,
            rustCompletedRuns,
            rustFallbackRuns,
            typescriptCompletedRuns,
            typescriptReasons: [...typescriptReasonCounts.entries()]
                .map(([reason, runs]) => ({ reason, runs }))
                .sort((a, b) => b.runs - a.runs || a.reason.localeCompare(b.reason)),
        },
    };
}
