/**
 * Server-safe in-sample candidate search for the Asset Opportunity scope.
 *
 * This leaf replaces the browser-bound `runFinderExecution` call in the server
 * path. The browser path pulls `lightweight-charts` transitively via
 * `../strategies/index` through `finder-runner.ts`, which is ESM-only and
 * cannot be bundled into the Vite config. This leaf reaches only
 * server-safe modules (matching `finder-runner-universe.ts`'s import hygiene):
 * `../backtest-executor`, `./finder-runner-core`, `./exit-strategy-param-prefix`,
 * and `./finder-manager-logic`.
 *
 * The function is a minimal IS search: it generates candidate params from the
 * injected param-space generator, executes each on the supplied historical
 * data, ranks them by the same sort priority, and returns the bounded top-K
 * result set. OOS validation is NOT done here — it is done by the caller
 * (Asset Opportunity server job) via the extracted candidate-OOS leaf.
 *
 * Determinism: the caller injects a deterministic per-asset seed through
 * `options.randomSeed`; the param-space generator consumes it unchanged, so
 * the same seed + same inputs produce the same candidate ordering.
 */

import type {
    BacktestResult,
    BacktestSettings,
    OHLCVData,
    Signal,
    StrategyParams,
} from "../../types/strategies";
import type { CapitalSettings } from "../../types/backtest";
import type { FinderOptions, FinderResult } from "../../types/finder";
import type { FinderSelectedStrategy } from "../finder-runner";
import type { CrossSymbolDataFetcher } from "../../cross-symbol-runtime";
import {
    executeBacktest,
    resolveExecutorBacktestSettings,
} from "../../backtest-executor";
import { resolveCapitalSettingsFromRaw } from "../../backtest-capital-settings";
import {
    createPreparedFinderStrategy,
    finderAssetSearchRequiresFullAnalytics,
    type FinderPreparedDataCache,
    normalizeFinderCandidateParamSets,
    resolveFinderRiskOverrides,
} from "../finder-runner-core";
import { withExitStrategyBaseParams, splitExitStrategyParams } from "../exit-strategy-param-prefix";
import { sanitizeBacktestSettingsForRust } from "../../rust-settings-sanitizer";
import { sortFinderResults } from "../finder-engine";
import { buildSelectionResult } from "../endpoint";

const ASSET_IS_SEARCH_YIELD_EVERY_RUNS = 256;
const ASSET_IS_SEARCH_YIELD_MIN_MS = 1000;

export interface ServerAssetIsSearchInput {
    ohlcvData: OHLCVData[];
    symbol: string;
    interval: string;
    options: FinderOptions;
    settings: BacktestSettings;
    capitalSettings: CapitalSettings;
    selectedStrategy: FinderSelectedStrategy;
    exitStrategyCandidates?: FinderSelectedStrategy[];
    generateParamSets: (defaultParams: StrategyParams, options: FinderOptions) => StrategyParams[];
    useRustEnginePreference?: boolean;
    dataFetcher?: CrossSymbolDataFetcher;
    isCancelled: () => boolean;
    yieldControl: () => Promise<void>;
    /**
     * When true, retain each candidate's generated signals and return them via
     * `signalsByCandidate` so the caller can run fresh-entry detection without
     * re-executing the top-K candidates. Only enable when the caller has proven
     * its recheck window is identical to this search's `ohlcvData`; the
     * retention is bounded by (param sets x signals) for one asset-strategy
     * pass and released once the caller finishes the asset.
     */
    retainSignals?: boolean;
}

export interface ServerAssetIsSearchOutput {
    results: FinderResult[];
    totalCandidatesEvaluated: number;
    candidateEvaluationsAttempted: number;
    candidateEvaluationsCompleted: number;
    candidateEvaluationFailures: number;
    /**
     * Parallel to `results` (same order): the signals generated by each
     * returned candidate. Present only when `retainSignals` was requested.
     */
    signalsByCandidate?: Signal[][];
    timingsMs: {
        total: number;
        parameterGeneration: number;
        backtest: number;
        yielding: number;
    };
    engineUsage: {
        rustAttemptedRuns: number;
        rustCompletedRuns: number;
        rustFallbackRuns: number;
        typescriptCompletedRuns: number;
        typescriptReasons: Array<{ reason: string; runs: number }>;
    };
}

/**
 * Run the in-sample search for one asset. Returns the top-N candidates
 * (N = `options.topN`) sorted by `options.sortPriority`.
 *
 * Mirrors the browser `runFinderExecution` candidate loop but uses
 * `executeBacktest` directly so the module stays server-safe. The caller
 * reserves the application candle and slices the historical window BEFORE
 * calling this function; the data passed here is the historical search data.
 */
export async function runServerAssetIsSearch(
    input: ServerAssetIsSearchInput,
): Promise<ServerAssetIsSearchOutput> {
    const { options, settings, capitalSettings, selectedStrategy } = input;
    const totalStartedAt = performance.now();
    const requiresFullAnalytics = finderAssetSearchRequiresFullAnalytics(options.sortPriority);
    if (selectedStrategy.strategy.crossSymbolConfig && !input.dataFetcher) {
        throw new Error(
            `Cross-symbol strategy "${selectedStrategy.name}" requires secondary asset data for Asset Opportunity.`,
        );
    }
    const rustSettings = sanitizeBacktestSettingsForRust(settings);
    const preResolvedCapital = resolveCapitalSettingsFromRaw(
        capitalSettings as unknown as Record<string, unknown>,
    );
    const preparedDataCache: FinderPreparedDataCache = new WeakMap();
    let currentBacktestSettings = settings;
    const preparedStrategy = createPreparedFinderStrategy(
        selectedStrategy.key,
        selectedStrategy.strategy,
        preparedDataCache,
        () => currentBacktestSettings,
    );

    // Build the same base params the current-chart path uses.
    const parameterGenerationStartedAt = performance.now();
    const entryDefaults = selectedStrategy.strategy.defaultParams;
    const generated = input.generateParamSets(entryDefaults, options);
    const normalized = normalizeFinderCandidateParamSets(selectedStrategy.strategy, generated);
    const paramSets = normalized.length > 0
        ? normalized
        : [{ ...entryDefaults }];
    const parameterGenerationMs = performance.now() - parameterGenerationStartedAt;

    const results: FinderResult[] = [];
    // Keyed by candidate object identity so the signals survive the final
    // sort + top-N slice without an index bookkeeping pass.
    const signalsByResult = new Map<FinderResult, Signal[]>();
    let candidateEvaluationsAttempted = 0;
    let candidateEvaluationsCompleted = 0;
    let candidateEvaluationFailures = 0;
    let backtestMs = 0;
    let yieldingMs = 0;
    let evaluationsSinceYield = 0;
    let lastYieldAt = performance.now();
    let rustAttemptedRuns = 0;
    let rustCompletedRuns = 0;
    let rustFallbackRuns = 0;
    let typescriptCompletedRuns = 0;
    const typescriptReasonCounts = new Map<string, number>();

    for (let index = 0; index < paramSets.length; index++) {
        if (input.isCancelled()) break;
        candidateEvaluationsAttempted += 1;
        const entryParams = paramSets[index]!;

        // Exit Strategy Override: sample one exit strategy + param set per
        // entry candidate (deterministic via the seeded random in the caller).
        let exitStrategy: FinderSelectedStrategy | undefined;
        let exitParams: StrategyParams | undefined;
        if (input.exitStrategyCandidates && input.exitStrategyCandidates.length > 0) {
            // Deterministic sampling: pick by candidate index modulo the exit
            // candidate count. This mirrors the seeded `exitRandom` behavior of
            // the current-chart path without requiring a random source.
            const candidateIndex = index % input.exitStrategyCandidates.length;
            exitStrategy = input.exitStrategyCandidates[candidateIndex];
            const exitDefaults = exitStrategy.strategy.defaultParams;
            const exitGenerated = input.generateParamSets(exitDefaults, options);
            const exitNormalized = normalizeFinderCandidateParamSets(exitStrategy.strategy, exitGenerated);
            exitParams = exitNormalized.length > 0
                ? exitNormalized[index % exitNormalized.length]
                : { ...exitDefaults };
        }

        const combinedParams = exitParams
            ? withExitStrategyBaseParams(entryParams, exitParams)
            : entryParams;
        const { backtestSettings: riskAdjustedSettings } = resolveFinderRiskOverrides(
            settings,
            rustSettings,
            combinedParams,
            options,
        );
        const backtestSettings: BacktestSettings = exitStrategy
            ? {
                ...riskAdjustedSettings,
                disableSignalExits: true,
                exitStrategyOverrideEnabled: true,
                exitStrategyKey: exitStrategy.key,
                exitStrategyParams: { ...(exitParams ?? {}) },
            }
            : riskAdjustedSettings;

        const preResolvedSettings = resolveExecutorBacktestSettings(
            { ...(backtestSettings as Record<string, unknown>), interval: input.interval } as BacktestSettings,
            input.interval,
        );
        currentBacktestSettings = backtestSettings;

        const candidateStartedAt = performance.now();
        try {
            const output = await executeBacktest({
                ohlcvData: input.ohlcvData,
                interval: input.interval,
                primarySymbol: input.symbol,
                strategyKey: selectedStrategy.key,
                strategy: preparedStrategy,
                strategyParams: entryParams,
                backtestSettings,
                capitalSettings,
                // The caller has already supplied the historical closed
                // window. Keep its array identity stable so prepared Finder
                // data and executor-side caches can be reused per asset.
                closedCandleDataOverride: input.ohlcvData,
                preResolvedSettings,
                preResolvedCapital,
                context: {
                    blockRange: null,
                    annotatePolymarket: false,
                    engineMode: "auto",
                    nowSec: Math.floor(Date.now() / 1000),
                    useRustEnginePreference: input.useRustEnginePreference,
                },
                ...(input.dataFetcher ? { dataFetcher: input.dataFetcher } : {}),
                backtestRunOptions: {
                    includeAdvancedAnalytics: false,
                    includeSharpeRatio: requiresFullAnalytics,
                    omitEquityCurve: true,
                    skipDrawdown: !requiresFullAnalytics,
                    skipResultPostProcessing: true,
                },
            });
            backtestMs += performance.now() - candidateStartedAt;
            candidateEvaluationsCompleted += 1;
            if (output.engineDiagnostics?.rustAttempted) rustAttemptedRuns += 1;
            if (output.engineUsed === "rust") rustCompletedRuns += 1;
            else {
                typescriptCompletedRuns += 1;
                const reason = output.engineDiagnostics?.typescriptReason ?? "TypeScript execution reason unavailable";
                typescriptReasonCounts.set(reason, (typescriptReasonCounts.get(reason) ?? 0) + 1);
                if (output.engineDiagnostics?.rustAttempted) rustFallbackRuns += 1;
            }

            const result: BacktestResult = output.result;
            const selection = buildSelectionResult(
                result,
                input.ohlcvData[input.ohlcvData.length - 1]?.time ?? null,
                preResolvedCapital.initialCapital,
            );
            // The current-chart path builds a FinderResult through
            // `enrichFinderCandidate` (endpoint adjustment + selection result).
            // Keep the same endpoint-adjusted selection semantics here so
            // historical ranking and grading use the same capital-aware view.
            const candidate: FinderResult = {
                key: selectedStrategy.key,
                name: selectedStrategy.name,
                params: exitStrategy
                    ? splitExitStrategyParams(combinedParams).entryParams
                    : entryParams,
                ...(exitStrategy
                    ? {
                        exitStrategyKey: exitStrategy.key,
                        exitStrategyParams: exitParams ?? {},
                    }
                    : {}),
                result,
                selectionResult: selection.result,
                endpointAdjusted: selection.adjusted,
                endpointRemovedTrades: selection.removedTrades,
            };
            results.push(candidate);
            if (input.retainSignals === true) {
                signalsByResult.set(candidate, output.signals);
            }
        } catch {
            backtestMs += performance.now() - candidateStartedAt;
            candidateEvaluationFailures += 1;
            // Skip failed candidates; the caller counts failures in diagnostics.
            continue;
        }

        evaluationsSinceYield += 1;
        const now = performance.now();
        if (
            evaluationsSinceYield >= ASSET_IS_SEARCH_YIELD_EVERY_RUNS
            || now - lastYieldAt >= ASSET_IS_SEARCH_YIELD_MIN_MS
        ) {
            evaluationsSinceYield = 0;
            lastYieldAt = now;
            const yieldingStartedAt = performance.now();
            await input.yieldControl();
            yieldingMs += performance.now() - yieldingStartedAt;
        }
    }

    const sorted = sortFinderResults(results, options.sortPriority);
    const topN = Math.max(1, options.topN);
    const topK = sorted.slice(0, topN);
    return {
        results: topK,
        totalCandidatesEvaluated: paramSets.length,
        candidateEvaluationsAttempted,
        candidateEvaluationsCompleted,
        candidateEvaluationFailures,
        ...(input.retainSignals === true
            ? { signalsByCandidate: topK.map((candidate) => signalsByResult.get(candidate) ?? []) }
            : {}),
        timingsMs: {
            total: performance.now() - totalStartedAt,
            parameterGeneration: parameterGenerationMs,
            backtest: backtestMs,
            yielding: yieldingMs,
        },
        engineUsage: {
            rustAttemptedRuns,
            rustCompletedRuns,
            rustFallbackRuns,
            typescriptCompletedRuns,
            typescriptReasons: [...typescriptReasonCounts.entries()]
                .map(([reason, runs]) => ({ reason, runs }))
                .sort((a, b) => b.runs - a.runs || a.reason.localeCompare(b.reason)),
        },
    };
}
