/**
 * Alert Service - thin API client for the Cloudflare Worker alert system.
 * Worker URL is stored in localStorage under 'alert_worker_url'.
 */

import {
    buildStreamId,
    parseConfigNameFromStreamId,
} from "./alert-stream-id";
import {
    readAlertWorkerToken,
    readAlertWorkerUrl,
    writeAlertWorkerToken,
    writeAlertWorkerUrl,
} from "./alert-storage";
import type { OHLCVData } from "./types/strategies";
import { debugLogger } from "./debug-logger";
import {
    createFetchTimeoutSignal,
    readJsonOrText,
    extractApiError,
    isAbortError,
} from "./dataProviders/fetch-helpers";

export const ALERT_WORKER_URL_CHANGED_EVENT = 'alert-worker-url-changed';
const API_FETCH_TIMEOUT_MS = 10_000;
/**
 * Cap on stream ids sent per `/api/subscriptions/states` request. Must be ≤ the
 * worker's MAX_BATCH (100) — the worker hard-truncates past that with one D1
 * `?` per IN value. Also bounds the N-parallel fallback path used when the
 * batched endpoint is unavailable on an older deployed worker.
 */

export interface AlertWorkerHealth {
    ok: boolean;
    error?: string;
    service?: string;
    now?: string;
    supportedStrategyKeys?: string[];
    supportedStrategyCount?: number;
    strategyManifestFingerprint?: string;
}

// Types

export interface AlertSubscription {
    id: number;
    stream_id: string;
    enabled: number;
    symbol: string;
    interval: string;
    strategy_key: string;
    strategy_params_json: string;
    backtest_settings_json: string;
    freshness_bars: number;
    notify_telegram: number;
    notify_exit: number;
    candle_limit: number;
    last_processed_closed_candle_time: number;
    last_run_at: string | null;
    last_status: string | null;
    created_at: string;
    updated_at: string;
}

export interface AlertSubscriptionUpsert {
    streamId?: string;
    symbol?: string;
    interval?: string;
    strategyKey?: string;
    configName?: string;
    strategyParams?: Record<string, number>;
    backtestSettings?: unknown;
    freshnessBars?: number;
    notifyTelegram?: boolean;
    notifyExit?: boolean;
    enabled?: boolean;
    candleLimit?: number;
}

export interface AlertSignalRecord {
    id: number;
    stream_id: string;
    symbol: string;
    interval: string;
    strategy_key: string;
    direction: 'long' | 'short';
    signal_time: number;
    signal_price: number;
    signal_reason: string | null;
    payload_json: string;
    created_at: string;
}

export interface RunNowResult {
    streamId: string;
    status: string;
    closedCandleTimeSec?: number;
    result?: Record<string, unknown>;
}

export interface AlertEvaluatedTradeContext {
    entryTimeSec: number;
    entryPrice: number;
    exitReason: string | null;
    isOpen: boolean;
    takeProfitPrice: number | null;
    stopLossPrice: number | null;
    takeProfitPercent: number | null;
    stopLossPercent: number | null;
}

export interface AlertEvaluatedEntrySignal {
    direction: 'long' | 'short';
    signalTimeSec: number;
    signalPrice: number;
    entryPrice?: number | null;
    signalAgeBars: number;
    isFresh: boolean;
    fingerprint: string;
}

export interface AlertSubscriptionState {
    ok: boolean;
    streamId: string;
    symbol: string;
    interval: string;
    strategyKey: string;
    evaluatedAt: string;
    closedCandleTimeSec: number | null;
    reason: string | null;
    latestClose?: number | null;
    latestTrade: AlertEvaluatedTradeContext | null;
    latestEntry: AlertEvaluatedEntrySignal | null;
}


/**
 * Build deterministic stream id. Keeps legacy format when no configName is provided.
 */
export function buildAlertStreamId(
    symbol: string,
    interval: string,
    strategyKey: string,
    configName?: string
): string {
    return buildStreamId(symbol, interval, strategyKey, configName);
}

/**
 * Parse optional configuration name from stream id generated by buildAlertStreamId.
 */
export function parseAlertConfigNameFromStreamId(streamId: string): string | null {
    return parseConfigNameFromStreamId(streamId);
}

// Helpers

function getWorkerUrl(): string {
    return readAlertWorkerUrl();
}

function getWorkerToken(): string {
    return readAlertWorkerToken()
        || ((import.meta as ImportMeta & { env?: { VITE_ALERT_WORKER_TOKEN?: string } }).env?.VITE_ALERT_WORKER_TOKEN ?? '');
}

function setWorkerUrl(url: string): void {
    const prev = getWorkerUrl();
    const normalized = writeAlertWorkerUrl(url);

    if (prev !== normalized && typeof window !== 'undefined' && typeof window.dispatchEvent === 'function' && typeof CustomEvent !== 'undefined') {
        window.dispatchEvent(new CustomEvent(ALERT_WORKER_URL_CHANGED_EVENT, { detail: { url: normalized } }));
    }
}

function setWorkerToken(token: string): void {
    writeAlertWorkerToken(token);
}

function requireUrl(): string {
    const url = getWorkerUrl();
    if (!url) throw new Error('Worker URL not configured. Set it in the Alerts tab.');
    return url;
}

function truncateText(value: string, maxLen = 320): string {
    const trimmed = value.trim();
    if (trimmed.length <= maxLen) return trimmed;
    return `${trimmed.slice(0, Math.max(0, maxLen - 3))}...`;
}

async function fetchWithTimeout(input: string, options?: RequestInit): Promise<Response> {
    const timeout = createFetchTimeoutSignal(options?.signal ?? undefined, API_FETCH_TIMEOUT_MS);
    try {
        return await fetch(input, { ...options, signal: timeout.signal });
    } catch (error) {
        // createFetchTimeoutSignal aborts on timeout; distinguish a real timeout
        // from a caller-initiated abort so the error message stays informative.
        const callerAborted = options?.signal?.aborted === true;
        if (!callerAborted && isAbortError(error)) {
            throw new Error(`Request timed out after ${API_FETCH_TIMEOUT_MS}ms.`);
        }
        throw error;
    } finally {
        timeout.cleanup();
    }
}

async function apiFetch<T>(path: string, options?: RequestInit): Promise<T> {
    const base = requireUrl();
    const token = getWorkerToken();
    const res = await fetchWithTimeout(`${base}${path}`, {
        ...options,
        headers: {
            'content-type': 'application/json',
            ...(token ? { authorization: `Bearer ${token}` } : {}),
            ...(options?.headers ?? {}),
        },
    });
    const body = await readJsonOrText(res);

    if (!res.ok) {
        const message = extractApiError(body.json)
            ?? (body.text ? truncateText(body.text) : null)
            ?? `HTTP ${res.status}`;
        throw new Error(message);
    }

    if (body.json !== null) return body.json as T;
    throw new Error(`Unexpected non-JSON response (HTTP ${res.status}).`);
}

// Public API

export const alertService = {
    getWorkerUrl,
    getWorkerToken,
    setWorkerUrl,
    setWorkerToken,

    /** Test worker connectivity */
    async healthCheck(): Promise<AlertWorkerHealth> {
        try {
            const base = requireUrl();
            const res = await fetchWithTimeout(`${base}/health`);
            const body = await readJsonOrText(res);
            if (!res.ok) {
                return {
                    ok: false,
                    error: extractApiError(body.json)
                        ?? (body.text ? truncateText(body.text) : `HTTP ${res.status}`),
                };
            }
            const json = body.json as Record<string, unknown> | null;
            const supportedStrategyKeys = Array.isArray(json?.supportedStrategyKeys)
                ? json.supportedStrategyKeys.filter((value): value is string => typeof value === 'string' && value.trim().length > 0)
                : undefined;

            return {
                ok: !!json?.ok,
                service: typeof json?.service === 'string' ? json.service : undefined,
                now: typeof json?.now === 'string' ? json.now : undefined,
                supportedStrategyKeys,
                supportedStrategyCount: typeof json?.supportedStrategyCount === 'number' ? json.supportedStrategyCount : undefined,
                strategyManifestFingerprint: typeof json?.strategyManifestFingerprint === 'string'
                    ? json.strategyManifestFingerprint
                    : undefined,
            };
        } catch (err) {
            return { ok: false, error: err instanceof Error ? err.message : String(err) };
        }
    },

    /** List all subscriptions */
    async listSubscriptions(): Promise<AlertSubscription[]> {
        const data = await apiFetch<{ ok: boolean; items: AlertSubscription[] }>('/api/subscriptions');
        return data.items ?? [];
    },


    /** Create or update a subscription */
    async upsertSubscription(payload: AlertSubscriptionUpsert): Promise<{
        ok: boolean;
        streamId: string;
        subscription: AlertSubscription;
    }> {
        return apiFetch('/api/subscriptions/upsert', {
            method: 'POST',
            body: JSON.stringify(payload),
        });
    },

    /** Disable a subscription (soft-delete) */
    async disableSubscription(streamId: string): Promise<void> {
        try {
            await apiFetch('/api/subscriptions/delete', {
                method: 'POST',
                body: JSON.stringify({ streamId }),
            });
        } catch (error) {
            // Backward compatibility for workers that do not expose /delete yet.
            debugLogger.warn('alert.disableSubscription.fallback', { streamId, error: String(error) });
            await apiFetch('/api/subscriptions/upsert', {
                method: 'POST',
                body: JSON.stringify({ streamId, enabled: false }),
            });
        }
    },

    /**
    async deleteSubscription(streamId: string, hardDelete = true): Promise<void> {
        try {
            await apiFetch('/api/subscriptions/delete', {
                method: 'POST',
                body: JSON.stringify({ streamId, hardDelete }),
            });
        } catch {
            await this.disableSubscription(streamId);
        }
    },

    /** Trigger immediate evaluation for a subscription */
    async runNow(streamId: string, force = false): Promise<RunNowResult> {
        const data = await apiFetch<{ ok: boolean; run?: RunNowResult } & Partial<RunNowResult>>('/api/subscriptions/run-now', {
            method: 'POST',
            body: JSON.stringify({ streamId, force }),
        });

        return data.run ?? {
            streamId: data.streamId ?? streamId,
            status: data.status ?? 'unknown',
            closedCandleTimeSec: data.closedCandleTimeSec,
            result: data.result,
        };
    },

    /** Trigger immediate subscription evaluation using caller-supplied candles. */
    async runWithCandles(streamId: string, candles: OHLCVData[], force = false): Promise<RunNowResult> {
        const data = await apiFetch<{ ok: boolean; run?: RunNowResult } & Partial<RunNowResult>>('/api/subscriptions/run-with-candles', {
            method: 'POST',
            body: JSON.stringify({ streamId, candles, force }),
        });

        return data.run ?? {
            streamId: data.streamId ?? streamId,
            status: data.status ?? 'unknown',
            closedCandleTimeSec: data.closedCandleTimeSec,
            result: data.result,
        };
    },

    /** Get signal history for a stream */
    async getSignalHistory(streamId: string, limit = 20): Promise<AlertSignalRecord[]> {
        const data = await apiFetch<{ ok: boolean; signals?: AlertSignalRecord[]; items?: AlertSignalRecord[] }>(
            `/api/stream/signals?streamId=${encodeURIComponent(streamId)}&limit=${limit}`
        );
        return data.items ?? data.signals ?? [];
    },

    /**
     * Read-only worker-side state for a subscription.
     * This endpoint evaluates current worker market data without mutating subscription state.
     */
    async getSubscriptionState(streamId: string): Promise<AlertSubscriptionState> {
        const data = await apiFetch<{ ok: boolean; state?: AlertSubscriptionState; item?: AlertSubscriptionState }>(
            `/api/subscriptions/state?streamId=${encodeURIComponent(streamId)}`
        );

        const state = data.state ?? data.item;
        if (!state) {
            throw new Error('Subscription state response missing payload.');
        }
        return state;
    },


};
