import { getOptionalElement, getRequiredElement } from "./dom-utils";

export const UI_EVENT_HANDLER_REQUIRED_IDS = [
    "symbolSelector",
    "symbolDropdown",
    "themeToggle",
    "strategySelect",
    "strategyTabs",
    "panelContent",
    "runBacktest",
    "clearTradesBtn",
    "togglePanel",
    "strategyPanel",
    "zoomInTool",
    "zoomOutTool",
    "fitTool",
    "riskSettingsToggle",
    "riskSettings",
    "tradeFilterSettingsToggle",
    "tradeFilterSettings",
    "riskMode",
    "takeProfitMode",
    "takeProfitShrinkageSettingsRow",
    "takeProfitMfeLookbackTrades",
    "takeProfitMfePercentile",
    "takeProfitShrinkageStrength",
    "riskAdvanced",
    "tradeDirection",
    "flipAfterConsecutiveLosses",
    "flipCooldownTrades",
    "minTradesBeforeFirstFlip",
    "tradeFilterMode",
    "htfBiasEmaPeriod",
    "executionTrendEmaPeriod",
    "confirmLookback",
    "trendPersistenceWindow",
    "trendPersistenceMinBars",
    "trendSlopeLookback",
    "trendSlopeMinPercent",
    "volumeSmaPeriod",
    "volumeMultiplier",
    "confirmRsiPeriod",
    "confirmRsiBullish",
    "confirmRsiBearish",
    "strategyTimeframeToggle",
    "strategyTimeframeMinutes",
    "finderTradesToggle",
    "finderTradeFilters",
    "fixedTradeToggle",
    "initialCapitalGroup",
    "fixedTradeGroup",
    "tradeSizingModeGroup",
    "positionSizeGroup",
    "initialCapital",
    "tradeSizingMode",
    "fixedTradeAmount",
    "positionSize",
    "panelResizeHandle",
] as const;

export function createUiEventHandlersDom() {
    return {
        symbolSelector: getRequiredElement("symbolSelector"),
        symbolDropdown: getRequiredElement("symbolDropdown"),
        symbolSearchInput: getOptionalElement<HTMLInputElement>("symbolSearchInput"),
        symbolSearchResults: getOptionalElement("symbolSearchResults"),
        symbolSearchSpinner: getOptionalElement("symbolSearchSpinner"),
        symbolSearchClear: getOptionalElement("symbolSearchClear"),
        symbolSearchLoading: getOptionalElement("symbolSearchLoading"),
        symbolSearchEmpty: getOptionalElement("symbolSearchEmpty"),
        localSp500Select: getOptionalElement<HTMLSelectElement>("localSp500Select"),
        mockModelSelect: getOptionalElement<HTMLSelectElement>("mockModelSelect"),
        mockBarsInput: getOptionalElement<HTMLInputElement>("mockBarsInput"),
        chartModeToggle: getOptionalElement<HTMLButtonElement>("chartModeToggle"),
        chartModeLabel: getOptionalElement("chartModeLabel"),
        timeframeMinutesInput: getOptionalElement<HTMLInputElement>("timeframeMinutesInput"),
        timeframeMinutesApply: getOptionalElement("timeframeMinutesApply"),
        visibleCandlesInput: getOptionalElement<HTMLInputElement>("visibleCandlesInput"),
        visibleCandlesApply: getOptionalElement("visibleCandlesApply"),
        themeToggle: getRequiredElement("themeToggle"),
        strategySelect: getRequiredElement<HTMLSelectElement>("strategySelect"),
        strategyTabs: getRequiredElement("strategyTabs"),
        panelContent: getRequiredElement("panelContent"),
        runBacktest: getRequiredElement("runBacktest"),
        clearTradesBtn: getRequiredElement("clearTradesBtn"),
        togglePanel: getRequiredElement("togglePanel"),
        strategyPanel: getRequiredElement("strategyPanel"),
        zoomInTool: getRequiredElement("zoomInTool"),
        zoomOutTool: getRequiredElement("zoomOutTool"),
        fitTool: getRequiredElement("fitTool"),
        screenshotTool: getOptionalElement("screenshotTool"),
        copyChartBtn: getOptionalElement("copyChartBtn"),
        riskSettingsToggle: getRequiredElement<HTMLInputElement>("riskSettingsToggle"),
        riskSettings: getRequiredElement("riskSettings"),
        tradeFilterSettingsToggle: getRequiredElement<HTMLInputElement>("tradeFilterSettingsToggle"),
        tradeFilterSettings: getRequiredElement("tradeFilterSettings"),
        riskMode: getRequiredElement<HTMLSelectElement>("riskMode"),
        takeProfitMode: getRequiredElement<HTMLSelectElement>("takeProfitMode"),
        takeProfitShrinkageSettingsRow: getRequiredElement("takeProfitShrinkageSettingsRow"),
        takeProfitMfeLookbackTrades: getRequiredElement<HTMLInputElement>("takeProfitMfeLookbackTrades"),
        takeProfitMfePercentile: getRequiredElement<HTMLInputElement>("takeProfitMfePercentile"),
        takeProfitShrinkageStrength: getRequiredElement<HTMLInputElement>("takeProfitShrinkageStrength"),
        riskSimpleAdvanced: getOptionalElement("riskSimpleAdvanced"),
        riskPercentage: getOptionalElement("riskPercentage"),
        riskAdvanced: getRequiredElement("riskAdvanced"),
        tradeDirection: getRequiredElement<HTMLSelectElement>("tradeDirection"),
        flipLossStreakSettingsRow: getOptionalElement("flipLossStreakSettingsRow"),
        flipAfterConsecutiveLosses: getRequiredElement<HTMLInputElement>("flipAfterConsecutiveLosses"),
        flipCooldownTrades: getRequiredElement<HTMLInputElement>("flipCooldownTrades"),
        minTradesBeforeFirstFlip: getRequiredElement<HTMLInputElement>("minTradesBeforeFirstFlip"),
        tradeFilterMode: getRequiredElement<HTMLSelectElement>("tradeFilterMode"),
        htfBiasEmaPeriod: getRequiredElement<HTMLInputElement>("htfBiasEmaPeriod"),
        executionTrendEmaPeriod: getRequiredElement<HTMLInputElement>("executionTrendEmaPeriod"),
        confirmLookback: getRequiredElement<HTMLInputElement>("confirmLookback"),
        trendPersistenceWindow: getRequiredElement<HTMLInputElement>("trendPersistenceWindow"),
        trendPersistenceMinBars: getRequiredElement<HTMLInputElement>("trendPersistenceMinBars"),
        trendSlopeLookback: getRequiredElement<HTMLInputElement>("trendSlopeLookback"),
        trendSlopeMinPercent: getRequiredElement<HTMLInputElement>("trendSlopeMinPercent"),
        volumeSmaPeriod: getRequiredElement<HTMLInputElement>("volumeSmaPeriod"),
        volumeMultiplier: getRequiredElement<HTMLInputElement>("volumeMultiplier"),
        confirmRsiPeriod: getRequiredElement<HTMLInputElement>("confirmRsiPeriod"),
        confirmRsiBullish: getRequiredElement<HTMLInputElement>("confirmRsiBullish"),
        confirmRsiBearish: getRequiredElement<HTMLInputElement>("confirmRsiBearish"),
        strategyTimeframeToggle: getRequiredElement<HTMLInputElement>("strategyTimeframeToggle"),
        strategyTimeframeMinutes: getRequiredElement<HTMLInputElement>("strategyTimeframeMinutes"),
        strategyTimeframeMinutesGroup: getOptionalElement("strategyTimeframeMinutesGroup"),
        twoHourCloseParity: getOptionalElement<HTMLSelectElement>("twoHourCloseParity"),
        finderTradesToggle: getRequiredElement<HTMLInputElement>("finderTradesToggle"),
        finderTradeFilters: getRequiredElement("finderTradeFilters"),
        fixedTradeToggle: getRequiredElement<HTMLInputElement>("fixedTradeToggle"),
        initialCapitalGroup: getRequiredElement("initialCapitalGroup"),
        fixedTradeGroup: getRequiredElement("fixedTradeGroup"),
        tradeSizingModeGroup: getRequiredElement("tradeSizingModeGroup"),
        positionSizeGroup: getRequiredElement("positionSizeGroup"),
        initialCapital: getRequiredElement<HTMLInputElement>("initialCapital"),
        tradeSizingMode: getRequiredElement<HTMLSelectElement>("tradeSizingMode"),
        fixedTradeAmount: getRequiredElement<HTMLInputElement>("fixedTradeAmount"),
        positionSize: getRequiredElement<HTMLInputElement>("positionSize"),
        panelResizeHandle: getRequiredElement("panelResizeHandle"),
    };
}

export type UiEventHandlersDom = ReturnType<typeof createUiEventHandlersDom>;

export function createStrategyPanelDom() {
    return {
        togglePanel: getRequiredElement("togglePanel"),
        strategyPanel: getRequiredElement("strategyPanel"),
        strategyTabs: getRequiredElement("strategyTabs"),
        panelContent: getRequiredElement("panelContent"),
        panelResizeHandle: getRequiredElement("panelResizeHandle"),
    };
}

export type StrategyPanelDom = ReturnType<typeof createStrategyPanelDom>;

export const SETTINGS_WORKSPACE_REQUIRED_IDS = [
    "settingsTab",
    "strategyWorkspaceHeader",
    "strategyWorkspaceSections",
    "strategyMetaName",
    "strategyMetaDescription",
    "strategyMetaKey",
    "strategyParamCount",
] as const;

export function createSettingsWorkspaceDom() {
    return {
        settingsTab: getRequiredElement("settingsTab"),
        strategyWorkspaceHeader: getRequiredElement("strategyWorkspaceHeader"),
        strategyWorkspaceSections: getRequiredElement("strategyWorkspaceSections"),
        strategyMetaName: getRequiredElement("strategyMetaName"),
        strategyMetaDescription: getRequiredElement("strategyMetaDescription"),
        strategyMetaKey: getRequiredElement("strategyMetaKey"),
        strategyParamCount: getRequiredElement("strategyParamCount"),
    };
}

export type SettingsWorkspaceDom = ReturnType<typeof createSettingsWorkspaceDom>;

export const UI_MANAGER_REQUIRED_IDS = [
    "symbolDataSource",
    "symbolPrice",
    "symbolChange",
    "ohlcOpen",
    "ohlcHigh",
    "ohlcLow",
    "ohlcClose",
    "ohlcVolume",
    "ohlcChange",
    "ohlcChangeValue",
    "lastBacktestResult",
    "tradeBadge",
    "strategySelect",
    "timeframeCustom",
    "timeframeMinutesInput",
    "indicatorsPanel",
    "strategyStatus",
] as const;

export function createUiManagerDom() {
    return {
        symbolDataSource: getRequiredElement("symbolDataSource"),
        symbolPrice: getRequiredElement("symbolPrice"),
        symbolChange: getRequiredElement("symbolChange"),
        ohlcOpen: getRequiredElement("ohlcOpen"),
        ohlcHigh: getRequiredElement("ohlcHigh"),
        ohlcLow: getRequiredElement("ohlcLow"),
        ohlcClose: getRequiredElement("ohlcClose"),
        ohlcVolume: getRequiredElement("ohlcVolume"),
        ohlcChange: getRequiredElement("ohlcChange"),
        ohlcChangeValue: getRequiredElement("ohlcChangeValue"),
        lastBacktestResult: getRequiredElement("lastBacktestResult"),
        tradeBadge: getRequiredElement("tradeBadge"),
        strategySelect: getRequiredElement<HTMLSelectElement>("strategySelect"),
        timeframeCustom: getRequiredElement("timeframeCustom"),
        timeframeMinutesInput: getRequiredElement<HTMLInputElement>("timeframeMinutesInput"),
        indicatorsPanel: getRequiredElement("indicatorsPanel"),
        strategyStatus: getRequiredElement("strategyStatus"),
    };
}

export type UiManagerDom = ReturnType<typeof createUiManagerDom>;

export const RESULTS_RENDERER_REQUIRED_IDS = [
    "netProfitCard",
    "netProfitPctCard",
    "entryLevelsBody",
    "parityComparePanel",
    "parityCompareGrid",
    "parityCompareHint",
    "postEntryPathContainer",
    "postEntryPathHint",
    "snapshotProfileContainer",
    "exitReasonContainer",
    "edgeAnalysisContainer",
] as const;

export function createResultsRendererDom() {
    return {
        netProfitCard: getRequiredElement("netProfitCard"),
        netProfitPctCard: getRequiredElement("netProfitPctCard"),
        entryLevelsBody: getRequiredElement("entryLevelsBody"),
        parityComparePanel: getRequiredElement("parityComparePanel"),
        parityCompareGrid: getRequiredElement("parityCompareGrid"),
        parityCompareHint: getRequiredElement("parityCompareHint"),
        postEntryPathContainer: getRequiredElement("postEntryPathContainer"),
        postEntryPathHint: getRequiredElement("postEntryPathHint"),
        snapshotProfileContainer: getRequiredElement("snapshotProfileContainer"),
        exitReasonContainer: getRequiredElement("exitReasonContainer"),
        edgeAnalysisContainer: getRequiredElement("edgeAnalysisContainer"),
    };
}

export type ResultsRendererDom = ReturnType<typeof createResultsRendererDom>;

export const TRADES_RENDERER_REQUIRED_IDS = [
    "tradesList",
    "tradesTotalPnL",
    "tradesWinRate",
] as const;

export function createTradesRendererDom() {
    return {
        tradesList: getRequiredElement("tradesList"),
        tradesTotalPnL: getRequiredElement("tradesTotalPnL"),
        tradesWinRate: getRequiredElement("tradesWinRate"),
    };
}

export type TradesRendererDom = ReturnType<typeof createTradesRendererDom>;

export const SETTINGS_MANAGER_REQUIRED_IDS = [
    "strategySelect",
    "settingsTab",
    "riskMode",
    "takeProfitMode",
    "tradeFilterMode",
    "tradeDirection",
    "twoHourCloseParity",
] as const;

export function createSettingsManagerDom() {
    return {
        strategySelect: getRequiredElement<HTMLSelectElement>("strategySelect"),
        settingsTab: getRequiredElement("settingsTab"),
        riskMode: getRequiredElement("riskMode"),
        takeProfitMode: getRequiredElement("takeProfitMode"),
        tradeFilterMode: getRequiredElement("tradeFilterMode"),
        tradeDirection: getRequiredElement("tradeDirection"),
        twoHourCloseParity: getOptionalElement("twoHourCloseParity"),
    };
}

export type SettingsManagerDom = ReturnType<typeof createSettingsManagerDom>;



export const PORTFOLIO_LAB_REQUIRED_IDS = [
    "portfolioTab",
    "portfolioEmpty",
    "portfolioContent",
    "portfolioSymbolList",
    "portfolioBenchmarkSymbol",
    "portfolioAnchorSymbol",
    "portfolioLookbackBars",
    "portfolioWindowMode",
    "portfolioConsensusLagBars",
    "portfolioConsensusMinSamples",
    "portfolioUseCurrentBtn",
    "portfolioFillMajorsBtn",
    "portfolioRunBtn",
    "portfolioStatus",
    "portfolioResults",
    "portfolioSummary",
    "portfolioLiveContextSection",
    "portfolioLiveContextSummary",
    "portfolioLiveContextDetails",
    "portfolioForecastSection",
    "portfolioForecastSummary",
    "portfolioForecastDetails",
    "portfolioForecastTableBody",
    "portfolioInsightSection",
    "portfolioInsights",
    "portfolioExecutionSection",
    "portfolioExecutionSummary",
    "portfolioConsensusSection",
    "portfolioConsensusSummary",
    "portfolioConsensusTableBody",
    "portfolioBreadthMinAgree",
    "portfolioMaxOppose",
    "portfolioRunBreadthBacktestBtn",
    "portfolioRunFilterBacktestBtn",
    "portfolioRunBreadthSweepBtn",
    "portfolioRunOppositionSweepBtn",
    "portfolioBreadthSweepSection",
    "portfolioBreadthSweepTableBody",
    "portfolioOppositionSweepSection",
    "portfolioOppositionSweepTableBody",
    "portfolioRankingSection",
    "portfolioRankingSummary",
    "portfolioRankingTableBody",
    "portfolioSizingSection",
    "portfolioSizingSummary",
    "portfolioSizingTableBody",
    "portfolioMatrixSection",
    "portfolioCorrelationMatrix",
    "portfolioPairsTableBody",
    "portfolioIntervalBadge",
    "portfolioStrategyBadge",
] as const;

export function createPortfolioLabDom() {
    return {
        portfolioTab: getRequiredElement("portfolioTab"),
        portfolioEmpty: getRequiredElement("portfolioEmpty"),
        portfolioContent: getRequiredElement("portfolioContent"),
        portfolioSymbolList: getRequiredElement<HTMLTextAreaElement>("portfolioSymbolList"),
        portfolioBenchmarkSymbol: getRequiredElement<HTMLInputElement>("portfolioBenchmarkSymbol"),
        portfolioAnchorSymbol: getRequiredElement<HTMLInputElement>("portfolioAnchorSymbol"),
        portfolioLookbackBars: getRequiredElement<HTMLInputElement>("portfolioLookbackBars"),
        portfolioWindowMode: getRequiredElement<HTMLSelectElement>("portfolioWindowMode"),
        portfolioConsensusLagBars: getRequiredElement<HTMLInputElement>("portfolioConsensusLagBars"),
        portfolioConsensusMinSamples: getRequiredElement<HTMLInputElement>("portfolioConsensusMinSamples"),
        portfolioUseCurrentBtn: getRequiredElement<HTMLButtonElement>("portfolioUseCurrentBtn"),
        portfolioFillMajorsBtn: getRequiredElement<HTMLButtonElement>("portfolioFillMajorsBtn"),
        portfolioRunBtn: getRequiredElement<HTMLButtonElement>("portfolioRunBtn"),
        portfolioStatus: getRequiredElement("portfolioStatus"),
        portfolioResults: getRequiredElement("portfolioResults"),
        portfolioSummary: getRequiredElement("portfolioSummary"),
        portfolioLiveContextSection: getRequiredElement("portfolioLiveContextSection"),
        portfolioLiveContextSummary: getRequiredElement("portfolioLiveContextSummary"),
        portfolioLiveContextDetails: getRequiredElement("portfolioLiveContextDetails"),
        portfolioForecastSection: getRequiredElement("portfolioForecastSection"),
        portfolioForecastSummary: getRequiredElement("portfolioForecastSummary"),
        portfolioForecastDetails: getRequiredElement("portfolioForecastDetails"),
        portfolioForecastTableBody: getRequiredElement("portfolioForecastTableBody"),
        portfolioInsightSection: getRequiredElement("portfolioInsightSection"),
        portfolioInsights: getRequiredElement("portfolioInsights"),
        portfolioExecutionSection: getRequiredElement("portfolioExecutionSection"),
        portfolioExecutionSummary: getRequiredElement("portfolioExecutionSummary"),
        portfolioConsensusSection: getRequiredElement("portfolioConsensusSection"),
        portfolioConsensusSummary: getRequiredElement("portfolioConsensusSummary"),
        portfolioConsensusTableBody: getRequiredElement("portfolioConsensusTableBody"),
        portfolioBreadthMinAgree: getRequiredElement<HTMLInputElement>("portfolioBreadthMinAgree"),
        portfolioMaxOppose: getRequiredElement<HTMLInputElement>("portfolioMaxOppose"),
        portfolioRunBreadthBacktestBtn: getRequiredElement<HTMLButtonElement>("portfolioRunBreadthBacktestBtn"),
        portfolioRunFilterBacktestBtn: getRequiredElement<HTMLButtonElement>("portfolioRunFilterBacktestBtn"),
        portfolioRunBreadthSweepBtn: getRequiredElement<HTMLButtonElement>("portfolioRunBreadthSweepBtn"),
        portfolioRunOppositionSweepBtn: getRequiredElement<HTMLButtonElement>("portfolioRunOppositionSweepBtn"),
        portfolioBreadthSweepSection: getRequiredElement("portfolioBreadthSweepSection"),
        portfolioBreadthSweepTableBody: getRequiredElement("portfolioBreadthSweepTableBody"),
        portfolioOppositionSweepSection: getRequiredElement("portfolioOppositionSweepSection"),
        portfolioOppositionSweepTableBody: getRequiredElement("portfolioOppositionSweepTableBody"),
        portfolioRankingSection: getRequiredElement("portfolioRankingSection"),
        portfolioRankingSummary: getRequiredElement("portfolioRankingSummary"),
        portfolioRankingTableBody: getRequiredElement("portfolioRankingTableBody"),
        portfolioSizingSection: getRequiredElement("portfolioSizingSection"),
        portfolioSizingSummary: getRequiredElement("portfolioSizingSummary"),
        portfolioSizingTableBody: getRequiredElement("portfolioSizingTableBody"),
        portfolioMatrixSection: getRequiredElement("portfolioMatrixSection"),
        portfolioCorrelationMatrix: getRequiredElement("portfolioCorrelationMatrix"),
        portfolioPairsTableBody: getRequiredElement("portfolioPairsTableBody"),
        portfolioIntervalBadge: getRequiredElement("portfolioIntervalBadge"),
        portfolioStrategyBadge: getRequiredElement("portfolioStrategyBadge"),
    };
}

export type PortfolioLabDom = ReturnType<typeof createPortfolioLabDom>;

export const FINDER_MANAGER_REQUIRED_IDS = [
    "runFinder",
    "finderCopyTopResults",
    "finderSaveSeedAudit",
    "finderList",
    "finderStrategiesToggleAll",
    "finderStrategySearch",
    "finderStrategySelectAll",
    "finderStrategySelectNone",
    "finderStrategyInvertVisible",
    "finderStrategySelectVisible",
    "finderStrategySummary",
    "finderSort",
    "finderSortSecondary",
    "finderAdvancedToggle",
    "finderSimpleSort",
    "finderSortList",
    "finderMultiTimeframeToggle",
    "finderMultiTimeframeAdd",
    "finderMultiTimeframeCustomAdd",
    "finderMultiTimeframeCustom",
    "finderMultiTimeframeSelected",
    "finderComboToggle",
    "finderComboPrimarySelect",
    "finderComboSettings",
    "finderFreezeRiskManagementToggle",
    "finderMultiTimeframeSelect",
    "finderMultiTimeframeNote",
    "finderMultiTimeframeSettings",
    "finderStrategyList",
    "finderMode",
    "finderTopN",
    "finderSteps",
    "finderRobustSeed",
    "finderRange",
    "finderMaxRuns",
    "finderTradesToggle",
    "finderTradesMin",
    "finderTradesMax",
] as const;

export function createFinderManagerDom() {
    return {
        runFinder: getRequiredElement<HTMLButtonElement>("runFinder"),
        finderCopyTopResults: getRequiredElement<HTMLButtonElement>("finderCopyTopResults"),
        finderSaveSeedAudit: getRequiredElement<HTMLButtonElement>("finderSaveSeedAudit"),
        finderList: getRequiredElement("finderList"),
        finderStrategiesToggleAll: getRequiredElement<HTMLInputElement>("finderStrategiesToggleAll"),
        finderStrategySearch: getRequiredElement<HTMLInputElement>("finderStrategySearch"),
        finderStrategySelectAll: getRequiredElement<HTMLButtonElement>("finderStrategySelectAll"),
        finderStrategySelectNone: getRequiredElement<HTMLButtonElement>("finderStrategySelectNone"),
        finderStrategyInvertVisible: getRequiredElement<HTMLButtonElement>("finderStrategyInvertVisible"),
        finderStrategySelectVisible: getRequiredElement<HTMLButtonElement>("finderStrategySelectVisible"),
        finderStrategySummary: getRequiredElement("finderStrategySummary"),
        finderSort: getRequiredElement<HTMLSelectElement>("finderSort"),
        finderSortSecondary: getRequiredElement<HTMLSelectElement>("finderSortSecondary"),
        finderAdvancedToggle: getRequiredElement<HTMLInputElement>("finderAdvancedToggle"),
        finderSimpleSort: getRequiredElement("finderSimpleSort"),
        finderSortList: getRequiredElement("finderSortList"),
        finderMultiTimeframeToggle: getRequiredElement<HTMLInputElement>("finderMultiTimeframeToggle"),
        finderMultiTimeframeAdd: getRequiredElement<HTMLButtonElement>("finderMultiTimeframeAdd"),
        finderMultiTimeframeCustomAdd: getRequiredElement<HTMLButtonElement>("finderMultiTimeframeCustomAdd"),
        finderMultiTimeframeCustom: getRequiredElement<HTMLInputElement>("finderMultiTimeframeCustom"),
        finderMultiTimeframeSelected: getRequiredElement("finderMultiTimeframeSelected"),
        finderComboToggle: getRequiredElement<HTMLInputElement>("finderComboToggle"),
        finderComboPrimarySelect: getRequiredElement<HTMLSelectElement>("finderComboPrimarySelect"),
        finderComboSettings: getRequiredElement("finderComboSettings"),
        finderFreezeRiskManagementToggle: getRequiredElement<HTMLInputElement>("finderFreezeRiskManagementToggle"),
        finderMultiTimeframeSelect: getRequiredElement<HTMLSelectElement>("finderMultiTimeframeSelect"),
        finderMultiTimeframeNote: getRequiredElement("finderMultiTimeframeNote"),
        finderMultiTimeframeSettings: getRequiredElement("finderMultiTimeframeSettings"),
        finderStrategyList: getRequiredElement("finderStrategyList"),
        finderMode: getRequiredElement<HTMLSelectElement>("finderMode"),
        finderTopN: getRequiredElement<HTMLInputElement>("finderTopN"),
        finderSteps: getRequiredElement<HTMLInputElement>("finderSteps"),
        finderRobustSeed: getRequiredElement<HTMLInputElement>("finderRobustSeed"),
        finderRange: getRequiredElement<HTMLInputElement>("finderRange"),
        finderMaxRuns: getRequiredElement<HTMLInputElement>("finderMaxRuns"),
        finderTradesToggle: getRequiredElement<HTMLInputElement>("finderTradesToggle"),
        finderTradesMin: getRequiredElement<HTMLInputElement>("finderTradesMin"),
        finderTradesMax: getRequiredElement<HTMLInputElement>("finderTradesMax"),
    };
}

export type FinderManagerDom = ReturnType<typeof createFinderManagerDom>;

export const PAIR_COMBINER_BRIDGE_REQUIRED_IDS = [
    "combinerPrimarySelect",
    "combinerSecondarySelect",
    "combinerMode",
] as const;

export function createPairCombinerBridgeDom() {
    return {
        combinerPrimarySelect: getRequiredElement<HTMLSelectElement>("combinerPrimarySelect"),
        combinerSecondarySelect: getRequiredElement<HTMLSelectElement>("combinerSecondarySelect"),
        combinerMode: getRequiredElement<HTMLSelectElement>("combinerMode"),
    };
}

export type PairCombinerBridgeDom = ReturnType<typeof createPairCombinerBridgeDom>;

export function createSettingsHandlersDom() {
    return {
        resetSettingsBtn: getOptionalElement<HTMLButtonElement>("resetSettingsBtn"),
        saveConfigBtn: getOptionalElement<HTMLButtonElement>("saveConfigBtn"),
        configNameInput: getOptionalElement<HTMLInputElement>("configNameInput"),
        loadConfigBtn: getOptionalElement<HTMLButtonElement>("loadConfigBtn"),
        configSelect: getOptionalElement<HTMLSelectElement>("configSelect"),
        deleteConfigBtn: getOptionalElement<HTMLButtonElement>("deleteConfigBtn"),
        generateShareLinkBtn: getOptionalElement<HTMLButtonElement>("generateShareLinkBtn"),
        copyShareLinkBtn: getOptionalElement<HTMLButtonElement>("copyShareLinkBtn"),
        shareConfigLinkInput: getOptionalElement<HTMLInputElement>("shareConfigLinkInput"),
        loadShareLinkBtn: getOptionalElement<HTMLButtonElement>("loadShareLinkBtn"),
        shareConfigImportInput: getOptionalElement<HTMLInputElement>("shareConfigImportInput"),
        runCombinedStrategyBtn: getOptionalElement<HTMLButtonElement>("runCombinedStrategyBtn"),
        combinerPrimarySelect: getOptionalElement<HTMLSelectElement>("combinerPrimarySelect"),
        combinerSecondarySelect: getOptionalElement<HTMLSelectElement>("combinerSecondarySelect"),
        combinerMode: getOptionalElement<HTMLSelectElement>("combinerMode"),
        useRustEngineToggle: getOptionalElement<HTMLInputElement>("useRustEngineToggle"),
        runBacktest: getOptionalElement<HTMLButtonElement>("runBacktest"),
    };
}

export type SettingsHandlersDom = ReturnType<typeof createSettingsHandlersDom>;

export const WALK_FORWARD_SERVICE_REQUIRED_IDS = [
    "wf-opt-window",
    "wf-test-window",
    "wf-step-size",
    "wf-min-trades",
    "wf-auto-suggest",
    "wf-validation-seeds",
    "wf-validation-min-passes",
    "wf-validation-max-dd",
    "wf-validation-panel",
    "wf-permutation-count",
    "wf-permutation-seed",
    "wf-permutation-metric",
    "wf-permutation-btn",
    "wf-permutation-spinner",
    "wf-permutation-panel",
    "wf-top-n",
    "wf-summary-panel",
    "wf-window-table-body",
    "wf-robustness-gauge",
    "wf-robustness-score",
    "wf-robustness-desc",
    "wf-run-btn",
    "wf-quick-btn",
    "wf-validate-btn",
    "wf-cancel-btn",
    "wf-spinner",
    "wf-quick-spinner",
    "wf-validate-spinner",
    "wf-status",
] as const;

export function createWalkForwardServiceDom() {
    return {
        wfOptWindow: getRequiredElement<HTMLInputElement>("wf-opt-window"),
        wfTestWindow: getRequiredElement<HTMLInputElement>("wf-test-window"),
        wfStepSize: getRequiredElement<HTMLInputElement>("wf-step-size"),
        wfMinTrades: getRequiredElement<HTMLInputElement>("wf-min-trades"),
        wfAutoSuggest: getRequiredElement<HTMLInputElement>("wf-auto-suggest"),
        wfValidationSeeds: getRequiredElement<HTMLInputElement>("wf-validation-seeds"),
        wfValidationMinPasses: getRequiredElement<HTMLInputElement>("wf-validation-min-passes"),
        wfValidationMaxDd: getRequiredElement<HTMLInputElement>("wf-validation-max-dd"),
        wfValidationPanel: getRequiredElement("wf-validation-panel"),
        wfPermutationCount: getRequiredElement<HTMLInputElement>("wf-permutation-count"),
        wfPermutationSeed: getRequiredElement<HTMLInputElement>("wf-permutation-seed"),
        wfPermutationMetric: getRequiredElement<HTMLSelectElement>("wf-permutation-metric"),
        wfPermutationBtn: getRequiredElement<HTMLButtonElement>("wf-permutation-btn"),
        wfPermutationSpinner: getRequiredElement("wf-permutation-spinner"),
        wfPermutationPanel: getRequiredElement("wf-permutation-panel"),
        wfTopN: getRequiredElement<HTMLInputElement>("wf-top-n"),
        wfSummaryPanel: getRequiredElement("wf-summary-panel"),
        wfWindowTableBody: getRequiredElement("wf-window-table-body"),
        wfRobustnessGauge: getRequiredElement("wf-robustness-gauge"),
        wfRobustnessScore: getRequiredElement("wf-robustness-score"),
        wfRobustnessDesc: getRequiredElement("wf-robustness-desc"),
        wfRunBtn: getRequiredElement<HTMLButtonElement>("wf-run-btn"),
        wfQuickBtn: getRequiredElement<HTMLButtonElement>("wf-quick-btn"),
        wfValidateBtn: getRequiredElement<HTMLButtonElement>("wf-validate-btn"),
        wfCancelBtn: getRequiredElement<HTMLButtonElement>("wf-cancel-btn"),
        wfSpinner: getRequiredElement("wf-spinner"),
        wfQuickSpinner: getRequiredElement("wf-quick-spinner"),
        wfValidateSpinner: getRequiredElement("wf-validate-spinner"),
        wfStatus: getRequiredElement("wf-status"),
    };
}

export type WalkForwardServiceDom = ReturnType<typeof createWalkForwardServiceDom>;

export const PARAMETER_AUDIT_REQUIRED_IDS = [
    "parameterAuditSource",
    "parameterAuditSavedConfigGroup",
    "parameterAuditSavedConfig",
    "parameterAuditRun",
    "parameterAuditProgress",
    "parameterAuditProgressFill",
    "parameterAuditProgressText",
    "parameterAuditStatus",
    "parameterAuditSourceSummary",
    "parameterAuditIncludedParams",
    "parameterAuditEvidence",
    "parameterAuditSummary",
    "parameterAuditEmpty",
    "parameterAuditTableBody",
] as const;

export function createParameterAuditDom() {
    return {
        parameterAuditSource: getRequiredElement<HTMLSelectElement>("parameterAuditSource"),
        parameterAuditSavedConfigGroup: getRequiredElement("parameterAuditSavedConfigGroup"),
        parameterAuditSavedConfig: getRequiredElement<HTMLSelectElement>("parameterAuditSavedConfig"),
        parameterAuditRun: getRequiredElement<HTMLButtonElement>("parameterAuditRun"),
        parameterAuditProgress: getRequiredElement("parameterAuditProgress"),
        parameterAuditProgressFill: getRequiredElement("parameterAuditProgressFill"),
        parameterAuditProgressText: getRequiredElement("parameterAuditProgressText"),
        parameterAuditStatus: getRequiredElement("parameterAuditStatus"),
        parameterAuditSourceSummary: getRequiredElement("parameterAuditSourceSummary"),
        parameterAuditIncludedParams: getRequiredElement("parameterAuditIncludedParams"),
        parameterAuditEvidence: getRequiredElement("parameterAuditEvidence"),
        parameterAuditSummary: getRequiredElement("parameterAuditSummary"),
        parameterAuditEmpty: getRequiredElement("parameterAuditEmpty"),
        parameterAuditTableBody: getRequiredElement("parameterAuditTableBody"),
    };
}

export type ParameterAuditDom = ReturnType<typeof createParameterAuditDom>;

export const ENSEMBLE_LAB_REQUIRED_IDS = [
    "ensembleTab",
    "ensembleEmpty",
    "ensembleContent",
    "ensembleTargetPicker",
    "ensembleTargetSelect",
    "ensembleTargetButton",
    "ensembleTargetMenu",
    "ensembleTargetSearch",
    "ensembleTargetList",
    "ensembleTargetPickerEmptyState",
    "ensembleTargetSummary",
    "ensembleMinSamples",
    "ensembleSymbolBadge",
    "ensembleIntervalBadge",
    "ensembleContextSearch",
    "ensembleContextFamilyFilter",
    "ensembleContextSelectAll",
    "ensembleContextSelectNone",
    "ensembleContextInvertVisible",
    "ensembleContextSelectVisible",
    "ensembleContextSelectSameFamily",
    "ensembleContextExcludeSameFamily",
    "ensembleContextSummary",
    "ensembleContextList",
    "ensembleContextHelper",
    "ensembleContextEmptyState",
    "ensembleRefreshConfigsBtn",
    "ensembleRunBtn",
    "ensembleStatus",
    "ensembleResults",
    "ensembleSummary",
    "ensembleCurrentContextSection",
    "ensembleCurrentContextSummary",
    "ensembleCurrentContextDetails",
    "ensembleHistoricalOddsSection",
    "ensembleHistoricalOddsSummary",
    "ensembleHistoricalOddsTableBody",
    "ensembleBuilderSection",
    "ensembleBuilderSummary",
    "ensembleBuilderTableBody",
    "ensembleDiagnosticsSection",
    "ensembleContributionSection",
    "ensembleContributionSummary",
    "ensembleContributionTableBody",
    "ensembleReplacementSection",
    "ensembleReplacementSummary",
    "ensembleReplacementTableBody",
    "ensembleRadarSection",
    "ensembleRadarContent",
] as const;

export function createEnsembleLabDom() {
    return {
        ensembleTab: getRequiredElement("ensembleTab"),
        ensembleEmpty: getRequiredElement("ensembleEmpty"),
        ensembleContent: getRequiredElement("ensembleContent"),
        ensembleTargetPicker: getRequiredElement("ensembleTargetPicker"),
        ensembleTargetSelect: getRequiredElement<HTMLSelectElement>("ensembleTargetSelect"),
        ensembleTargetButton: getRequiredElement<HTMLButtonElement>("ensembleTargetButton"),
        ensembleTargetMenu: getRequiredElement("ensembleTargetMenu"),
        ensembleTargetSearch: getRequiredElement<HTMLInputElement>("ensembleTargetSearch"),
        ensembleTargetList: getRequiredElement("ensembleTargetList"),
        ensembleTargetPickerEmptyState: getRequiredElement("ensembleTargetPickerEmptyState"),
        ensembleTargetSummary: getRequiredElement("ensembleTargetSummary"),
        ensembleMinSamples: getRequiredElement<HTMLInputElement>("ensembleMinSamples"),
        ensembleSymbolBadge: getRequiredElement("ensembleSymbolBadge"),
        ensembleIntervalBadge: getRequiredElement("ensembleIntervalBadge"),
        ensembleContextSearch: getRequiredElement<HTMLInputElement>("ensembleContextSearch"),
        ensembleContextFamilyFilter: getRequiredElement<HTMLSelectElement>("ensembleContextFamilyFilter"),
        ensembleContextSelectAll: getRequiredElement<HTMLButtonElement>("ensembleContextSelectAll"),
        ensembleContextSelectNone: getRequiredElement<HTMLButtonElement>("ensembleContextSelectNone"),
        ensembleContextInvertVisible: getRequiredElement<HTMLButtonElement>("ensembleContextInvertVisible"),
        ensembleContextSelectVisible: getRequiredElement<HTMLButtonElement>("ensembleContextSelectVisible"),
        ensembleContextSelectSameFamily: getRequiredElement<HTMLButtonElement>("ensembleContextSelectSameFamily"),
        ensembleContextExcludeSameFamily: getRequiredElement<HTMLButtonElement>("ensembleContextExcludeSameFamily"),
        ensembleContextSummary: getRequiredElement("ensembleContextSummary"),
        ensembleContextList: getRequiredElement("ensembleContextList"),
        ensembleContextHelper: getRequiredElement("ensembleContextHelper"),
        ensembleContextEmptyState: getRequiredElement("ensembleContextEmptyState"),
        ensembleRefreshConfigsBtn: getRequiredElement<HTMLButtonElement>("ensembleRefreshConfigsBtn"),
        ensembleRunBtn: getRequiredElement<HTMLButtonElement>("ensembleRunBtn"),
        ensembleStatus: getRequiredElement("ensembleStatus"),
        ensembleResults: getRequiredElement("ensembleResults"),
        ensembleSummary: getRequiredElement("ensembleSummary"),
        ensembleCurrentContextSection: getRequiredElement("ensembleCurrentContextSection"),
        ensembleCurrentContextSummary: getRequiredElement("ensembleCurrentContextSummary"),
        ensembleCurrentContextDetails: getRequiredElement("ensembleCurrentContextDetails"),
        ensembleHistoricalOddsSection: getRequiredElement("ensembleHistoricalOddsSection"),
        ensembleHistoricalOddsSummary: getRequiredElement("ensembleHistoricalOddsSummary"),
        ensembleHistoricalOddsTableBody: getRequiredElement("ensembleHistoricalOddsTableBody"),
        ensembleBuilderSection: getRequiredElement("ensembleBuilderSection"),
        ensembleBuilderSummary: getRequiredElement("ensembleBuilderSummary"),
        ensembleBuilderTableBody: getRequiredElement("ensembleBuilderTableBody"),
        ensembleDiagnosticsSection: getRequiredElement<HTMLDetailsElement>("ensembleDiagnosticsSection"),
        ensembleContributionSection: getRequiredElement("ensembleContributionSection"),
        ensembleContributionSummary: getRequiredElement("ensembleContributionSummary"),
        ensembleContributionTableBody: getRequiredElement("ensembleContributionTableBody"),
        ensembleReplacementSection: getRequiredElement("ensembleReplacementSection"),
        ensembleReplacementSummary: getRequiredElement("ensembleReplacementSummary"),
        ensembleReplacementTableBody: getRequiredElement("ensembleReplacementTableBody"),
        ensembleRadarSection: getRequiredElement("ensembleRadarSection"),
        ensembleRadarContent: getRequiredElement("ensembleRadarContent"),
    };
}

export type EnsembleLabDom = ReturnType<typeof createEnsembleLabDom>;
