import { getRequiredElement } from "./dom-utils";

export const POLYMARKET_PANEL_REQUIRED_IDS = [
    // Existing fillability analysis
    "polymarketTab",
    "polymarketBridgeConfig",
    "polymarketBridgeDownloadScript",
    "polymarketBridgeCopyEnv",
    "polymarketBridgeStatus",
    "polymarketEntryPriceCents",
    "polymarketScope",
    "polymarketPriceNote",
    "polymarketEmpty",
    "polymarketSupport",
    "polymarketContent",
    "polymarketEligibleTrades",
    "polymarketEnrichedTrades",
    "polymarketFilledTrades",
    "polymarketFillRate",
    "polymarketFilledWinRate",
    "polymarketStatus",
    "polymarketTableBody",
    // Deployability analysis
    "deployabilityEmpty",
    "deployabilitySupport",
    "deployabilityContent",
    "deployabilityVerdict",
    "deployabilityVerdictBadge",
    "deployabilityVerdictText",
    "deployWinRate",
    "deployWins",
    "deployLosses",
    "deployScoredTrades",
    "deployCoverage",
    "deployWilsonLB",
    "deployAlwaysYes",
    "deployAlwaysNo",
    "deployDeltaYes",
    "deployDeltaNo",
    "deployBlockHint",
    "deployBlocksBody",
    "deployLongShortBody",
    "deployEntryBucketsBody",
    "deployShuffleHint",
    "deployShuffleSims",
    "deployShuffleObserved",
    "deployShuffleExceed",
    "deployShufflePValue",
    "deployShuffleMean",
    "deployShuffleP95",
    "deployFillHint",
    "deployFillScored",
    "deployFillWins",
    "deployFillLosses",
    "deployFillWinRate",
    "deployFillWilsonLB",
    "deployFillRate",
    "deployFillBestBaselineLabel",
    "deployFillBestBaseline",
    "deployFillDeltaBaselineLabel",
    "deployFillDeltaBaseline",
    "deployFillBreakEven",
    "deployFillEdgeBreakEven",
] as const;

export function createPolymarketPanelDom() {
    return {
        // Existing fillability analysis
        polymarketTab: getRequiredElement("polymarketTab"),
        polymarketBridgeConfig: getRequiredElement<HTMLSelectElement>("polymarketBridgeConfig"),
        polymarketBridgeDownloadScript: getRequiredElement<HTMLButtonElement>("polymarketBridgeDownloadScript"),
        polymarketBridgeCopyEnv: getRequiredElement<HTMLButtonElement>("polymarketBridgeCopyEnv"),
        polymarketBridgeStatus: getRequiredElement("polymarketBridgeStatus"),
        polymarketEntryPriceCents: getRequiredElement<HTMLInputElement>("polymarketEntryPriceCents"),
        polymarketScope: getRequiredElement<HTMLSelectElement>("polymarketScope"),
        polymarketPriceNote: getRequiredElement("polymarketPriceNote"),
        polymarketEmpty: getRequiredElement("polymarketEmpty"),
        polymarketSupport: getRequiredElement("polymarketSupport"),
        polymarketContent: getRequiredElement("polymarketContent"),
        polymarketEligibleTrades: getRequiredElement("polymarketEligibleTrades"),
        polymarketEnrichedTrades: getRequiredElement("polymarketEnrichedTrades"),
        polymarketFilledTrades: getRequiredElement("polymarketFilledTrades"),
        polymarketFillRate: getRequiredElement("polymarketFillRate"),
        polymarketFilledWinRate: getRequiredElement("polymarketFilledWinRate"),
        polymarketStatus: getRequiredElement("polymarketStatus"),
        polymarketTableBody: getRequiredElement("polymarketTableBody"),
        // Deployability analysis
        deployabilityEmpty: getRequiredElement("deployabilityEmpty"),
        deployabilitySupport: getRequiredElement("deployabilitySupport"),
        deployabilityContent: getRequiredElement("deployabilityContent"),
        deployabilityVerdict: getRequiredElement("deployabilityVerdict"),
        deployabilityVerdictBadge: getRequiredElement("deployabilityVerdictBadge"),
        deployabilityVerdictText: getRequiredElement("deployabilityVerdictText"),
        deployWinRate: getRequiredElement("deployWinRate"),
        deployWins: getRequiredElement("deployWins"),
        deployLosses: getRequiredElement("deployLosses"),
        deployScoredTrades: getRequiredElement("deployScoredTrades"),
        deployCoverage: getRequiredElement("deployCoverage"),
        deployWilsonLB: getRequiredElement("deployWilsonLB"),
        deployAlwaysYes: getRequiredElement("deployAlwaysYes"),
        deployAlwaysNo: getRequiredElement("deployAlwaysNo"),
        deployDeltaYes: getRequiredElement("deployDeltaYes"),
        deployDeltaNo: getRequiredElement("deployDeltaNo"),
        deployBlockHint: getRequiredElement("deployBlockHint"),
        deployBlocksBody: getRequiredElement("deployBlocksBody"),
        deployLongShortBody: getRequiredElement("deployLongShortBody"),
        deployEntryBucketsBody: getRequiredElement("deployEntryBucketsBody"),
        deployShuffleHint: getRequiredElement("deployShuffleHint"),
        deployShuffleSims: getRequiredElement("deployShuffleSims"),
        deployShuffleObserved: getRequiredElement("deployShuffleObserved"),
        deployShuffleExceed: getRequiredElement("deployShuffleExceed"),
        deployShufflePValue: getRequiredElement("deployShufflePValue"),
        deployShuffleMean: getRequiredElement("deployShuffleMean"),
        deployShuffleP95: getRequiredElement("deployShuffleP95"),
        deployFillHint: getRequiredElement("deployFillHint"),
        deployFillScored: getRequiredElement("deployFillScored"),
        deployFillWins: getRequiredElement("deployFillWins"),
        deployFillLosses: getRequiredElement("deployFillLosses"),
        deployFillWinRate: getRequiredElement("deployFillWinRate"),
        deployFillWilsonLB: getRequiredElement("deployFillWilsonLB"),
        deployFillRate: getRequiredElement("deployFillRate"),
        deployFillBestBaselineLabel: getRequiredElement("deployFillBestBaselineLabel"),
        deployFillBestBaseline: getRequiredElement("deployFillBestBaseline"),
        deployFillDeltaBaselineLabel: getRequiredElement("deployFillDeltaBaselineLabel"),
        deployFillDeltaBaseline: getRequiredElement("deployFillDeltaBaseline"),
        deployFillBreakEven: getRequiredElement("deployFillBreakEven"),
        deployFillEdgeBreakEven: getRequiredElement("deployFillEdgeBreakEven"),
    };
}

export type PolymarketPanelDom = ReturnType<typeof createPolymarketPanelDom>;
