export {
    type QuickViewPolymarketSummary,
    type QuickViewPolymarketPayoutSummary,
    type QuickViewPolymarketExecutionGap,
    type QuickViewPolymarketExitReasonSummary,
    type QuickViewPolymarketExpectancySummary,
    type QuickViewPolymarketExitReasonWinRates,
    summarizePolymarketStreaks,
    summarizeRecentPolymarketForm,
    summarizePolymarketExitReasonWinRates,
    summarizePolymarketExpectancyAfterTakeProfit,
    computePolymarketBestBaselineWinRate,
    countDistinctPolymarketOutcomeRows,
    getQuickViewDiagnosticSections,
    summarizePolymarketPayoutDiagnostics,
    summarizePolymarketExecutionGap,
    quickViewManager,
} from "./quick-view/quick-view-service";
