import { getRequiredElement } from "./dom-utils";

export const SELECTION_RULES_REQUIRED_IDS = [
    "selectionRulesSection",
    "selectionRulesFolderSelect",
    "selectionRulesHorizonSelect",
    "selectionRulesFolderMeta",
    "selectionRulesSelectAll",
    "selectionRulesSelectNone",
    "selectionRulesInvert",
    "selectionRulesRuleList",
    "selectionRulesSelectionSummary",
    "selectionRulesRefreshBtn",
    "selectionRulesRunBtn",
    "selectionRulesStopBtn",
    "selectionRulesStatus",
    "selectionRulesProgress",
    "selectionRulesProgressFill",
    "selectionRulesProgressText",
    "selectionRulesResults",
    "selectionRulesEmpty",
    "selectionRulesDetail",
    "selectionRulesDetailTitle",
    "selectionRulesDetailHideBtn",
    "selectionRulesDetailLatest",
    "selectionRulesDetailHistorySummary",
    "selectionRulesDetailHistory",
    "selectionRulesDetailLoadOlderBtn",
    "selectionRulesDetailPerformance",
    "selectionRulesDetailStatus",
    "selectionRulesReport",
    "selectionRulesCopyBtn",
    "selectionRulesDiagnostics",
    "selectionRulesCopyDiagnosticsBtn",
] as const;

export function createSelectionRulesDom() {
    return {
        selectionRulesSection: getRequiredElement<HTMLElement>("selectionRulesSection"),
        selectionRulesFolderSelect: getRequiredElement<HTMLSelectElement>("selectionRulesFolderSelect"),
        selectionRulesHorizonSelect: getRequiredElement<HTMLInputElement>("selectionRulesHorizonSelect"),
        selectionRulesFolderMeta: getRequiredElement<HTMLDivElement>("selectionRulesFolderMeta"),
        selectionRulesSelectAll: getRequiredElement<HTMLButtonElement>("selectionRulesSelectAll"),
        selectionRulesSelectNone: getRequiredElement<HTMLButtonElement>("selectionRulesSelectNone"),
        selectionRulesInvert: getRequiredElement<HTMLButtonElement>("selectionRulesInvert"),
        selectionRulesRuleList: getRequiredElement<HTMLDivElement>("selectionRulesRuleList"),
        selectionRulesSelectionSummary: getRequiredElement<HTMLSpanElement>("selectionRulesSelectionSummary"),
        selectionRulesRefreshBtn: getRequiredElement<HTMLButtonElement>("selectionRulesRefreshBtn"),
        selectionRulesRunBtn: getRequiredElement<HTMLButtonElement>("selectionRulesRunBtn"),
        selectionRulesStopBtn: getRequiredElement<HTMLButtonElement>("selectionRulesStopBtn"),
        selectionRulesStatus: getRequiredElement<HTMLDivElement>("selectionRulesStatus"),
        selectionRulesProgress: getRequiredElement<HTMLDivElement>("selectionRulesProgress"),
        selectionRulesProgressFill: getRequiredElement<HTMLProgressElement>("selectionRulesProgressFill"),
        selectionRulesProgressText: getRequiredElement<HTMLDivElement>("selectionRulesProgressText"),
        selectionRulesResults: getRequiredElement<HTMLTableSectionElement>("selectionRulesResults"),
        selectionRulesEmpty: getRequiredElement<HTMLDivElement>("selectionRulesEmpty"),
        selectionRulesDetail: getRequiredElement<HTMLDivElement>("selectionRulesDetail"),
        selectionRulesDetailTitle: getRequiredElement<HTMLHeadingElement>("selectionRulesDetailTitle"),
        selectionRulesDetailHideBtn: getRequiredElement<HTMLButtonElement>("selectionRulesDetailHideBtn"),
        selectionRulesDetailLatest: getRequiredElement<HTMLDivElement>("selectionRulesDetailLatest"),
        selectionRulesDetailHistorySummary: getRequiredElement<HTMLSpanElement>("selectionRulesDetailHistorySummary"),
        selectionRulesDetailHistory: getRequiredElement<HTMLTableSectionElement>("selectionRulesDetailHistory"),
        selectionRulesDetailLoadOlderBtn: getRequiredElement<HTMLButtonElement>("selectionRulesDetailLoadOlderBtn"),
        selectionRulesDetailPerformance: getRequiredElement<HTMLTableSectionElement>("selectionRulesDetailPerformance"),
        selectionRulesDetailStatus: getRequiredElement<HTMLDivElement>("selectionRulesDetailStatus"),
        selectionRulesReport: getRequiredElement<HTMLPreElement>("selectionRulesReport"),
        selectionRulesCopyBtn: getRequiredElement<HTMLButtonElement>("selectionRulesCopyBtn"),
        selectionRulesDiagnostics: getRequiredElement<HTMLPreElement>("selectionRulesDiagnostics"),
        selectionRulesCopyDiagnosticsBtn: getRequiredElement<HTMLButtonElement>("selectionRulesCopyDiagnosticsBtn"),
    };
}

export type SelectionRulesDom = ReturnType<typeof createSelectionRulesDom>;
