import { Strategy, OHLCVData, StrategyParams } from "../../types/strategies";
import { createBuySignal, createSellSignal, createSignalLoop, ensureCleanData } from "../strategy-helpers";
import { buildCloseLocationSeries, extractBarMetricSeries } from "./price-action-frequency-core";

function normalizeMicroGapRejectionParams(params: StrategyParams): StrategyParams {
    return {
        ...params,
        min_gap_pct: Math.max(0, Number(params.min_gap_pct ?? 0.001)),
        rejection_close_loc: Math.max(0, Math.min(1, Number(params.rejection_close_loc ?? 0.25)))
    };
}

export const micro_gap_rejection: Strategy = {
    name: "Micro Gap Rejection",
    description: "Gaps generated by eager market-open orders that immediately fail to hold their direction trap the most impatient participants.",
    defaultParams: {
        min_gap_pct: 0.001,
        rejection_close_loc: 0.25
    },
    paramLabels: {
        min_gap_pct: "Minimum Gap %",
        rejection_close_loc: "Rejection Close Location"
    },
    normalizeParams: normalizeMicroGapRejectionParams,
    execute: (data: OHLCVData[], params: StrategyParams) => {
        const cleanData = ensureCleanData(data);
        const p = normalizeMicroGapRejectionParams(params);
        if (cleanData.length < 2) return [];

        const gapPctSeries = extractBarMetricSeries(cleanData, 'gapPct');
        const closeLocSeries = buildCloseLocationSeries(cleanData);

        return createSignalLoop(cleanData, [], (i) => {
            if (i < 1) return null;
            
            const gapPct = gapPctSeries[i];
            const closeLoc = closeLocSeries[i];
            const minGap = p.min_gap_pct as number;
            const rejLoc = p.rejection_close_loc as number;

            if (gapPct < -minGap && closeLoc > (1.0 - rejLoc)) {
                return createBuySignal(cleanData, i, `Gap down > ${minGap} rejected at closeLoc > ${1.0 - rejLoc}`);
            }
            if (gapPct > minGap && closeLoc < rejLoc) {
                return createSellSignal(cleanData, i, `Gap up > ${minGap} rejected at closeLoc < ${rejLoc}`);
            }
            return null;
        });
    },
    metadata: {
        role: "entry",
        direction: "both",
        walkForwardParams: ["min_gap_pct", "rejection_close_loc"]
    }
};
