import { getRequiredElement } from "../dom-utils";

export const ASSET_OPPORTUNITY_EXPLORER_REQUIRED_IDS = [
    "explorerRunSelect",
    "explorerHorizonSelect",
    "explorerTopKInput",
    "explorerMetricSelect",
    "explorerSpacingSelect",
    "explorerRefreshBtn",
    "explorerStatus",
    "explorerMeta",
    "explorerEmpty",
    "explorerHeatmapSection",
    "explorerHeatmapWrap",
    "explorerHeatmapCanvas",
    "explorerHeatmapReadout",
    "explorerHeatmapLegend",
    "explorerRangeStart",
    "explorerRangeEnd",
    "explorerRangeApplyBtn",
    "explorerRunNotice",
    "explorerDetail",
    "explorerDetailTitle",
    "explorerDetailSummary",
    "explorerHistogram",
    "explorerDetailTable",
    "explorerDetailRows",
    "explorerDetailLoadOlderBtn",
    "explorerDetailCloseBtn",
    "explorerDetailStatus",
] as const;

export function createAssetOpportunityExplorerDom() {
    return {
        explorerRunSelect: getRequiredElement<HTMLSelectElement>("explorerRunSelect"),
        explorerHorizonSelect: getRequiredElement<HTMLSelectElement>("explorerHorizonSelect"),
        explorerTopKInput: getRequiredElement<HTMLInputElement>("explorerTopKInput"),
        explorerMetricSelect: getRequiredElement<HTMLSelectElement>("explorerMetricSelect"),
        explorerSpacingSelect: getRequiredElement<HTMLSelectElement>("explorerSpacingSelect"),
        explorerRefreshBtn: getRequiredElement<HTMLButtonElement>("explorerRefreshBtn"),
        explorerStatus: getRequiredElement<HTMLDivElement>("explorerStatus"),
        explorerMeta: getRequiredElement<HTMLDivElement>("explorerMeta"),
        explorerEmpty: getRequiredElement<HTMLDivElement>("explorerEmpty"),
        explorerHeatmapSection: getRequiredElement<HTMLDivElement>("explorerHeatmapSection"),
        explorerHeatmapWrap: getRequiredElement<HTMLDivElement>("explorerHeatmapWrap"),
        explorerHeatmapCanvas: getRequiredElement<HTMLCanvasElement>("explorerHeatmapCanvas"),
        explorerHeatmapReadout: getRequiredElement<HTMLDivElement>("explorerHeatmapReadout"),
        explorerHeatmapLegend: getRequiredElement<HTMLDivElement>("explorerHeatmapLegend"),
        explorerRangeStart: getRequiredElement<HTMLInputElement>("explorerRangeStart"),
        explorerRangeEnd: getRequiredElement<HTMLInputElement>("explorerRangeEnd"),
        explorerRangeApplyBtn: getRequiredElement<HTMLButtonElement>("explorerRangeApplyBtn"),
        explorerRunNotice: getRequiredElement<HTMLDivElement>("explorerRunNotice"),
        explorerDetail: getRequiredElement<HTMLDivElement>("explorerDetail"),
        explorerDetailTitle: getRequiredElement<HTMLHeadingElement>("explorerDetailTitle"),
        explorerDetailSummary: getRequiredElement<HTMLDivElement>("explorerDetailSummary"),
        explorerHistogram: getRequiredElement<HTMLDivElement>("explorerHistogram"),
        explorerDetailTable: getRequiredElement<HTMLTableElement>("explorerDetailTable"),
        explorerDetailRows: getRequiredElement<HTMLTableSectionElement>("explorerDetailRows"),
        explorerDetailLoadOlderBtn: getRequiredElement<HTMLButtonElement>("explorerDetailLoadOlderBtn"),
        explorerDetailCloseBtn: getRequiredElement<HTMLButtonElement>("explorerDetailCloseBtn"),
        explorerDetailStatus: getRequiredElement<HTMLDivElement>("explorerDetailStatus"),
    };
}

export type AssetOpportunityExplorerDom = ReturnType<typeof createAssetOpportunityExplorerDom>;
