import { getRequiredElement } from "../dom-utils";

export const FINDER_MANAGER_REQUIRED_IDS = [
    "finderScope",
    "runFinder",
    "stopFinder",
    "finderCopyTopResults",
    "finderList",
    "finderChartSortSection",
    "finderUniverseSortSection",
    "finderUniverseSort",
    "finderUniverseSortSecondary",
    "finderStrategiesToggleAll",
    "finderStrategySearch",
    "finderStrategyActions",
    "finderStrategySelectAll",
    "finderStrategySelectNone",
    "finderStrategyInvertVisible",
    "finderStrategySelectVisible",
    "finderStrategySummary",
    "finderSort",
    "finderSortSecondary",
    "finderAdvancedToggle",
    "finderSimpleSort",
    "finderSortList",
    "finderFreezeRiskManagementToggle",
    "finderStrategyList",
    "finderMode",
    "finderModeRow",
    "finderTopN",
    "finderSteps",
    "finderStepsRow",
    "finderRange",
    "finderMaxRuns",
    "finderUniverseSectionHeader",
    "finderUniverseSection",
    "finderUniverseUseCurrent",
    "finderUniverseUseCurrentMajors",
    "finderUniverseClear",
    "finderUniverseSymbols",
    "finderUniverseSummary",
    "finderUniverseMinActiveSymbols",
    "finderUniverseMinTotalTrades",
    "finderUniverseMinProfitableActiveRatio",
    "finderPolymarketSection",
    "finderTradeFilterSection",
    "finderTradesToggle",
    "finderTradeFilters",
    "finderTradesMin",
    "finderTradesMax",
    "finderPolymarketToggle",
    "finderPolymarketSettings",
    "finderPolymarketRankMode",
    "finderPolymarketMinScored",
    "finderPolymarketLockOffset",
    "finderPolymarketAfterTakeProfitOnly",
] as const;

export function createFinderManagerDom() {
    return {
        finderScope: getRequiredElement<HTMLSelectElement>("finderScope"),
        runFinder: getRequiredElement<HTMLButtonElement>("runFinder"),
        stopFinder: getRequiredElement<HTMLButtonElement>("stopFinder"),
        finderCopyTopResults: getRequiredElement<HTMLButtonElement>("finderCopyTopResults"),
        finderList: getRequiredElement("finderList"),
        finderChartSortSection: getRequiredElement("finderChartSortSection"),
        finderUniverseSortSection: getRequiredElement("finderUniverseSortSection"),
        finderUniverseSort: getRequiredElement<HTMLSelectElement>("finderUniverseSort"),
        finderUniverseSortSecondary: getRequiredElement<HTMLSelectElement>("finderUniverseSortSecondary"),
        finderStrategiesToggleAll: getRequiredElement<HTMLInputElement>("finderStrategiesToggleAll"),
        finderStrategySearch: getRequiredElement<HTMLInputElement>("finderStrategySearch"),
        finderStrategyActions: getRequiredElement("finderStrategyActions"),
        finderStrategySelectAll: getRequiredElement<HTMLButtonElement>("finderStrategySelectAll"),
        finderStrategySelectNone: getRequiredElement<HTMLButtonElement>("finderStrategySelectNone"),
        finderStrategyInvertVisible: getRequiredElement<HTMLButtonElement>("finderStrategyInvertVisible"),
        finderStrategySelectVisible: getRequiredElement<HTMLButtonElement>("finderStrategySelectVisible"),
        finderStrategySummary: getRequiredElement("finderStrategySummary"),
        finderSort: getRequiredElement<HTMLSelectElement>("finderSort"),
        finderSortSecondary: getRequiredElement<HTMLSelectElement>("finderSortSecondary"),
        finderAdvancedToggle: getRequiredElement<HTMLInputElement>("finderAdvancedToggle"),
        finderSimpleSort: getRequiredElement("finderSimpleSort"),
        finderSortList: getRequiredElement("finderSortList"),
        finderFreezeRiskManagementToggle: getRequiredElement<HTMLInputElement>("finderFreezeRiskManagementToggle"),
        finderStrategyList: getRequiredElement("finderStrategyList"),
        finderMode: getRequiredElement<HTMLSelectElement>("finderMode"),
        finderModeRow: getRequiredElement("finderModeRow"),
        finderTopN: getRequiredElement<HTMLInputElement>("finderTopN"),
        finderSteps: getRequiredElement<HTMLInputElement>("finderSteps"),
        finderStepsRow: getRequiredElement("finderStepsRow"),
        finderRange: getRequiredElement<HTMLInputElement>("finderRange"),
        finderMaxRuns: getRequiredElement<HTMLInputElement>("finderMaxRuns"),
        finderUniverseSectionHeader: getRequiredElement("finderUniverseSectionHeader"),
        finderUniverseSection: getRequiredElement("finderUniverseSection"),
        finderUniverseUseCurrent: getRequiredElement<HTMLButtonElement>("finderUniverseUseCurrent"),
        finderUniverseUseCurrentMajors: getRequiredElement<HTMLButtonElement>("finderUniverseUseCurrentMajors"),
        finderUniverseClear: getRequiredElement<HTMLButtonElement>("finderUniverseClear"),
        finderUniverseSymbols: getRequiredElement<HTMLTextAreaElement>("finderUniverseSymbols"),
        finderUniverseSummary: getRequiredElement("finderUniverseSummary"),
        finderUniverseMinActiveSymbols: getRequiredElement<HTMLInputElement>("finderUniverseMinActiveSymbols"),
        finderUniverseMinTotalTrades: getRequiredElement<HTMLInputElement>("finderUniverseMinTotalTrades"),
        finderUniverseMinProfitableActiveRatio: getRequiredElement<HTMLInputElement>("finderUniverseMinProfitableActiveRatio"),
        finderPolymarketSection: getRequiredElement("finderPolymarketSection"),
        finderTradeFilterSection: getRequiredElement("finderTradeFilterSection"),
        finderTradesToggle: getRequiredElement<HTMLInputElement>("finderTradesToggle"),
        finderTradeFilters: getRequiredElement("finderTradeFilters"),
        finderTradesMin: getRequiredElement<HTMLInputElement>("finderTradesMin"),
        finderTradesMax: getRequiredElement<HTMLInputElement>("finderTradesMax"),
        finderPolymarketToggle: getRequiredElement<HTMLInputElement>("finderPolymarketToggle"),
        finderPolymarketSettings: getRequiredElement("finderPolymarketSettings"),
        finderPolymarketRankMode: getRequiredElement<HTMLSelectElement>("finderPolymarketRankMode"),
        finderPolymarketMinScored: getRequiredElement<HTMLInputElement>("finderPolymarketMinScored"),
        finderPolymarketLockOffset: getRequiredElement<HTMLInputElement>("finderPolymarketLockOffset"),
        finderPolymarketAfterTakeProfitOnly: getRequiredElement<HTMLInputElement>("finderPolymarketAfterTakeProfitOnly"),
    };
}

export type FinderManagerDom = ReturnType<typeof createFinderManagerDom>;
