import { getRequiredElement } from "../dom-utils";

export const FINDER_MANAGER_REQUIRED_IDS = [
    "runFinder",
    "stopFinder",
    "finderCopyTopResults",
    "finderList",
    "finderStrategiesToggleAll",
    "finderStrategySearch",
    "finderStrategySelectAll",
    "finderStrategySelectNone",
    "finderStrategyInvertVisible",
    "finderStrategySelectVisible",
    "finderStrategySummary",
    "finderSort",
    "finderSortSecondary",
    "finderAdvancedToggle",
    "finderSimpleSort",
    "finderSortList",
    "finderMultiTimeframeToggle",
    "finderMultiTimeframeAdd",
    "finderMultiTimeframeCustomAdd",
    "finderMultiTimeframeCustom",
    "finderMultiTimeframeSelected",
    "finderComboToggle",
    "finderComboPrimarySelect",
    "finderComboSettings",
    "finderFreezeRiskManagementToggle",
    "finderMultiTimeframeSelect",
    "finderMultiTimeframeNote",
    "finderMultiTimeframeSettings",
    "finderStrategyList",
    "finderMode",
    "finderTopN",
    "finderSteps",
    "finderRange",
    "finderMaxRuns",
    "finderTradesToggle",
    "finderTradesMin",
    "finderTradesMax",
    "finderPolymarketToggle",
    "finderPolymarketSettings",
    "finderPolymarketRankMode",
    "finderPolymarketMinScored",
    "finderPolymarketLockOffset",
    "finderPolymarketAfterTakeProfitOnly",
] as const;

export function createFinderManagerDom() {
    return {
        runFinder: getRequiredElement<HTMLButtonElement>("runFinder"),
        stopFinder: getRequiredElement<HTMLButtonElement>("stopFinder"),
        finderCopyTopResults: getRequiredElement<HTMLButtonElement>("finderCopyTopResults"),
        finderList: getRequiredElement("finderList"),
        finderStrategiesToggleAll: getRequiredElement<HTMLInputElement>("finderStrategiesToggleAll"),
        finderStrategySearch: getRequiredElement<HTMLInputElement>("finderStrategySearch"),
        finderStrategySelectAll: getRequiredElement<HTMLButtonElement>("finderStrategySelectAll"),
        finderStrategySelectNone: getRequiredElement<HTMLButtonElement>("finderStrategySelectNone"),
        finderStrategyInvertVisible: getRequiredElement<HTMLButtonElement>("finderStrategyInvertVisible"),
        finderStrategySelectVisible: getRequiredElement<HTMLButtonElement>("finderStrategySelectVisible"),
        finderStrategySummary: getRequiredElement("finderStrategySummary"),
        finderSort: getRequiredElement<HTMLSelectElement>("finderSort"),
        finderSortSecondary: getRequiredElement<HTMLSelectElement>("finderSortSecondary"),
        finderAdvancedToggle: getRequiredElement<HTMLInputElement>("finderAdvancedToggle"),
        finderSimpleSort: getRequiredElement("finderSimpleSort"),
        finderSortList: getRequiredElement("finderSortList"),
        finderMultiTimeframeToggle: getRequiredElement<HTMLInputElement>("finderMultiTimeframeToggle"),
        finderMultiTimeframeAdd: getRequiredElement<HTMLButtonElement>("finderMultiTimeframeAdd"),
        finderMultiTimeframeCustomAdd: getRequiredElement<HTMLButtonElement>("finderMultiTimeframeCustomAdd"),
        finderMultiTimeframeCustom: getRequiredElement<HTMLInputElement>("finderMultiTimeframeCustom"),
        finderMultiTimeframeSelected: getRequiredElement("finderMultiTimeframeSelected"),
        finderComboToggle: getRequiredElement<HTMLInputElement>("finderComboToggle"),
        finderComboPrimarySelect: getRequiredElement<HTMLSelectElement>("finderComboPrimarySelect"),
        finderComboSettings: getRequiredElement("finderComboSettings"),
        finderFreezeRiskManagementToggle: getRequiredElement<HTMLInputElement>("finderFreezeRiskManagementToggle"),
        finderMultiTimeframeSelect: getRequiredElement<HTMLSelectElement>("finderMultiTimeframeSelect"),
        finderMultiTimeframeNote: getRequiredElement("finderMultiTimeframeNote"),
        finderMultiTimeframeSettings: getRequiredElement("finderMultiTimeframeSettings"),
        finderStrategyList: getRequiredElement("finderStrategyList"),
        finderMode: getRequiredElement<HTMLSelectElement>("finderMode"),
        finderTopN: getRequiredElement<HTMLInputElement>("finderTopN"),
        finderSteps: getRequiredElement<HTMLInputElement>("finderSteps"),
        finderRange: getRequiredElement<HTMLInputElement>("finderRange"),
        finderMaxRuns: getRequiredElement<HTMLInputElement>("finderMaxRuns"),
        finderTradesToggle: getRequiredElement<HTMLInputElement>("finderTradesToggle"),
        finderTradesMin: getRequiredElement<HTMLInputElement>("finderTradesMin"),
        finderTradesMax: getRequiredElement<HTMLInputElement>("finderTradesMax"),
        finderPolymarketToggle: getRequiredElement<HTMLInputElement>("finderPolymarketToggle"),
        finderPolymarketSettings: getRequiredElement("finderPolymarketSettings"),
        finderPolymarketRankMode: getRequiredElement<HTMLSelectElement>("finderPolymarketRankMode"),
        finderPolymarketMinScored: getRequiredElement<HTMLInputElement>("finderPolymarketMinScored"),
        finderPolymarketLockOffset: getRequiredElement<HTMLInputElement>("finderPolymarketLockOffset"),
        finderPolymarketAfterTakeProfitOnly: getRequiredElement<HTMLInputElement>("finderPolymarketAfterTakeProfitOnly"),
    };
}

export type FinderManagerDom = ReturnType<typeof createFinderManagerDom>;
