import type { Strategy } from "../types/strategies";

// AUTO-GENERATED by `npm run strategies:sync-manifest`.
// Do not manually edit strategy imports or `strategyManifest` entries.

import { entropy_ratio_regime_alignment } from "./lib/entropy_ratio_regime_alignment";
import { adx_skewness_drift } from "./lib/adx_skewness_drift";
import { wick_responsive_boundary } from "./lib/wick_responsive_boundary";
import { wick_responsive_boundary_retest } from "./lib/wick_responsive_boundary_retest";
import { poly_5m_pivot_breakout_entry } from "./lib/poly_5m_pivot_breakout_entry";
import { true_range_ratio_pop_chase } from "./lib/true_range_ratio_pop_chase";
import { probability_boundary_eigen_shift } from "./lib/probability_boundary_eigen_shift";
import { volume_divergent_roc_reversion } from "./lib/volume_divergent_roc_reversion";
import { wick_imbalance_decay_fade } from "./lib/wick_imbalance_decay_fade";
import { velocity_percentile_phi_snap } from "./lib/velocity_percentile_phi_snap";
import { autocorrelation_phi_decay } from "./lib/autocorrelation_phi_decay";
import { ichimoku_conversion_base_cross } from "./lib/ichimoku_conversion_base_cross";
import { close_acceptance_streak_reversion } from "./lib/close_acceptance_streak_reversion";
import { entropy_acceleration_transition } from "./lib/entropy_acceleration_transition";
import { body_concentration_entropy_squeeze } from "./lib/body_concentration_entropy_squeeze";
import { close_acceptance_volume_conviction } from "./lib/close_acceptance_volume_conviction";
import { euphoria_volume_phi_divergence } from "./lib/euphoria_volume_phi_divergence";
import { panic_skewness_phi_trap } from "./lib/panic_skewness_phi_trap";
import { weighted_typical_phi_dislocation } from "./lib/weighted_typical_phi_dislocation";
import { volume_zscore_phi_compression } from "./lib/volume_zscore_phi_compression";
import { initiative_autocorrelation_phi_fade } from "./lib/initiative_autocorrelation_phi_fade";
import { range_clustering_momentum } from "./lib/range_clustering_momentum";
import { pivot_midpoint_anchor_fade } from "./lib/pivot_midpoint_anchor_fade";
import { volatility_percentile_reversal } from "./lib/volatility_percentile_reversal";
import { efficiency_phi_micro_streak } from "./lib/efficiency_phi_micro_streak";
import { body_proportion_phi_implosion } from "./lib/body_proportion_phi_implosion";
import { volume_thrust_phi_correlation } from "./lib/volume_thrust_phi_correlation";
import { midpoint_gravity_fade } from "./lib/midpoint_gravity_fade";
import { volume_exhaustion_decay } from "./lib/volume_exhaustion_decay";
import { limit_wall_liquidity_vacuum } from "./lib/limit_wall_liquidity_vacuum";
import { autocorrelation_momentum_divergence } from "./lib/autocorrelation_momentum_divergence";
import { velocity_reversal_shock } from "./lib/velocity_reversal_shock";
import { true_range_skewness_initiation } from "./lib/true_range_skewness_initiation";
import { body_proportion_entropy_ignition } from "./lib/body_proportion_entropy_ignition";
import { return_skewness_exhaustion_fade } from "./lib/return_skewness_exhaustion_fade";
import { volume_weighted_entropy_ignition } from "./lib/volume_weighted_entropy_ignition";
import { poc_liquidity_rejection_fade } from "./lib/poc_liquidity_rejection_fade";
import { initiative_crossing_frequency_chop } from "./lib/initiative_crossing_frequency_chop";
import { relative_strength_mean_reversion } from "./lib/relative_strength_mean_reversion";
import { cross_pressure_initiative_inversion } from "./lib/cross_pressure_initiative_inversion";
import { dominance_handoff_exhaustion } from "./lib/dominance_handoff_exhaustion";
import { close_location_correlation_break } from "./lib/close_location_correlation_break";
import { correlation_range_fragmentation } from "./lib/correlation_range_fragmentation";
import { correlation_flash_gamma_trigger } from "./lib/correlation_flash_gamma_trigger";
import { volatility_ratio_overextension } from "./lib/volatility_ratio_overextension";
import { rolling_vwap_center } from "./lib/rolling_vwap_center";
import { initiative_pressure_side } from "./lib/initiative_pressure_side";
import { decay_momentum_alignment } from "./lib/decay_momentum_alignment";
import { initiative_pressure_gated_median } from "./lib/initiative_pressure_gated_median";
import { roc_percentile_regime } from "./lib/roc_percentile_regime";
import { accumulation_persistence_streak_gate } from "./lib/accumulation_persistence_streak_gate";
import { keltner_halfband_acceptance } from "./lib/keltner_halfband_acceptance";
import { kurtosis_distribution_alignment } from "./lib/kurtosis_distribution_alignment";
import { mfi_median_participation_alignment } from "./lib/mfi_median_participation_alignment";
import { skewness_distribution_alignment } from "./lib/skewness_distribution_alignment";
import { bollinger_tail_reversion } from "./lib/bollinger_tail_reversion";
import { consecutive_streak_reversion } from "./lib/consecutive_streak_reversion";
import { donchian_extreme_rejection_fade } from "./lib/donchian_extreme_rejection_fade";
import { efficiency_ratio_peak_fade } from "./lib/efficiency_ratio_peak_fade";
import { extreme_zscore_tail_fade } from "./lib/extreme_zscore_tail_fade";
import { gap_displacement_reversal_fade } from "./lib/gap_displacement_reversal_fade";
import { keltner_extension_reversal } from "./lib/keltner_extension_reversal";
import { overextended_rsi_structural_fade } from "./lib/overextended_rsi_structural_fade";
import { typical_price_deviation_fade } from "./lib/typical_price_deviation_fade";
import { volume_blowoff_reversion } from "./lib/volume_blowoff_reversion";
import { cmf_momentum_vector_alignment } from "./lib/cmf_momentum_vector_alignment";
import { decaying_boundary_momentum_capture } from "./lib/decaying_boundary_momentum_capture";
import { hvn_value_migration_rebound } from "./lib/hvn_value_migration_rebound";
import { initiative_pressure_accumulation_streak } from "./lib/initiative_pressure_accumulation_streak";
import { kurtosis_tail_persistence_alignment } from "./lib/kurtosis_tail_persistence_alignment";
import { low_entropy_ordered_breakout } from "./lib/low_entropy_ordered_breakout";
import { low_volatility_efficiency_lead } from "./lib/low_volatility_efficiency_lead";
import { skewness_divergence_regime_anchor } from "./lib/skewness_divergence_regime_anchor";
import { typical_price_acceleration_anchor } from "./lib/typical_price_acceleration_anchor";
import { volume_autocorrelation_participation_gate } from "./lib/volume_autocorrelation_participation_gate";
import { adx_gated_median_alignment } from "./lib/adx_gated_median_alignment";
import { close_percentile_alignment } from "./lib/close_percentile_alignment";
import { cmf_median_alignment } from "./lib/cmf_median_alignment";
import { donchian_midpoint_alignment } from "./lib/donchian_midpoint_alignment";
import { efficiency_gated_median_alignment } from "./lib/efficiency_gated_median_alignment";
import { keltner_midpoint_alignment } from "./lib/keltner_midpoint_alignment";
import { rolling_mean_alignment } from "./lib/rolling_mean_alignment";
import { rolling_median_alignment } from "./lib/rolling_median_alignment";
import { trailing_range_position_alignment } from "./lib/trailing_range_position_alignment";
import { volatility_regime_median_alignment } from "./lib/volatility_regime_median_alignment";
import { atr_gated_median_alignment } from "./lib/atr_gated_median_alignment";
import { autocorrelation_gated_median_alignment } from "./lib/autocorrelation_gated_median_alignment";
import { close_location_median_alignment } from "./lib/close_location_median_alignment";
import { momentum_percentile_alignment } from "./lib/momentum_percentile_alignment";
import { parabolic_sar_anchor_alignment } from "./lib/parabolic_sar_anchor_alignment";
import { rolling_gap_zscore_alignment } from "./lib/rolling_gap_zscore_alignment";
import { trailing_hilo_midpoint_alignment } from "./lib/trailing_hilo_midpoint_alignment";
import { typical_price_percentile_alignment } from "./lib/typical_price_percentile_alignment";
import { volume_percentile_gated_median_alignment } from "./lib/volume_percentile_gated_median_alignment";
import { weighted_close_median_alignment } from "./lib/weighted_close_median_alignment";
import { directional_index_regime_alignment } from "./lib/directional_index_regime_alignment";
import { displacement_gap_zone_alignment } from "./lib/displacement_gap_zone_alignment";
import { distribution_rank_state_alignment } from "./lib/distribution_rank_state_alignment";
import { keltner_midpoint_volatility_gated_alignment } from "./lib/keltner_midpoint_volatility_gated_alignment";
import { mfi_accumulation_zone_alignment } from "./lib/mfi_accumulation_zone_alignment";
import { range_extreme_acceptance_persistence } from "./lib/range_extreme_acceptance_persistence";
import { rolling_median_velocity_alignment } from "./lib/rolling_median_velocity_alignment";
import { rolling_poc_displacement_alignment } from "./lib/rolling_poc_displacement_alignment";
import { typical_price_zscore_alignment } from "./lib/typical_price_zscore_alignment";
import { typical_price_percentile_gap_exit_hybrid } from "./lib/typical_price_percentile_gap_exit_hybrid";
import { initiative_pressure_low_volatility_exit_hybrid } from "./lib/initiative_pressure_low_volatility_exit_hybrid";

export interface StrategyManifestEntry {
    key: string;
    strategy: Strategy;
    assets?: string[];
}

export const strategyManifest: readonly StrategyManifestEntry[] = [
    { key: "entropy_ratio_regime_alignment", strategy: entropy_ratio_regime_alignment },
    { key: "adx_skewness_drift", strategy: adx_skewness_drift },
    { key: "wick_responsive_boundary", strategy: wick_responsive_boundary },
    { key: "wick_responsive_boundary_retest", strategy: wick_responsive_boundary_retest },
    { key: "poly_5m_pivot_breakout_entry", strategy: poly_5m_pivot_breakout_entry },
    { key: "true_range_ratio_pop_chase", strategy: true_range_ratio_pop_chase },
    { key: "probability_boundary_eigen_shift", strategy: probability_boundary_eigen_shift },
    { key: "volume_divergent_roc_reversion", strategy: volume_divergent_roc_reversion },
    { key: "wick_imbalance_decay_fade", strategy: wick_imbalance_decay_fade },
    { key: "velocity_percentile_phi_snap", strategy: velocity_percentile_phi_snap },
    { key: "autocorrelation_phi_decay", strategy: autocorrelation_phi_decay },
    { key: "ichimoku_conversion_base_cross", strategy: ichimoku_conversion_base_cross },
    { key: "close_acceptance_streak_reversion", strategy: close_acceptance_streak_reversion },
    { key: "entropy_acceleration_transition", strategy: entropy_acceleration_transition },
    { key: "body_concentration_entropy_squeeze", strategy: body_concentration_entropy_squeeze },
    { key: "close_acceptance_volume_conviction", strategy: close_acceptance_volume_conviction },
    { key: "euphoria_volume_phi_divergence", strategy: euphoria_volume_phi_divergence },
    { key: "panic_skewness_phi_trap", strategy: panic_skewness_phi_trap },
    { key: "weighted_typical_phi_dislocation", strategy: weighted_typical_phi_dislocation },
    { key: "volume_zscore_phi_compression", strategy: volume_zscore_phi_compression },
    { key: "initiative_autocorrelation_phi_fade", strategy: initiative_autocorrelation_phi_fade },
    { key: "range_clustering_momentum", strategy: range_clustering_momentum },
    { key: "pivot_midpoint_anchor_fade", strategy: pivot_midpoint_anchor_fade },
    { key: "volatility_percentile_reversal", strategy: volatility_percentile_reversal },
    { key: "efficiency_phi_micro_streak", strategy: efficiency_phi_micro_streak },
    { key: "body_proportion_phi_implosion", strategy: body_proportion_phi_implosion },
    { key: "volume_thrust_phi_correlation", strategy: volume_thrust_phi_correlation },
    { key: "midpoint_gravity_fade", strategy: midpoint_gravity_fade },
    { key: "volume_exhaustion_decay", strategy: volume_exhaustion_decay },
    { key: "limit_wall_liquidity_vacuum", strategy: limit_wall_liquidity_vacuum },
    { key: "autocorrelation_momentum_divergence", strategy: autocorrelation_momentum_divergence },
    { key: "velocity_reversal_shock", strategy: velocity_reversal_shock },
    { key: "true_range_skewness_initiation", strategy: true_range_skewness_initiation },
    { key: "body_proportion_entropy_ignition", strategy: body_proportion_entropy_ignition },
    { key: "return_skewness_exhaustion_fade", strategy: return_skewness_exhaustion_fade },
    { key: "volume_weighted_entropy_ignition", strategy: volume_weighted_entropy_ignition },
    { key: "poc_liquidity_rejection_fade", strategy: poc_liquidity_rejection_fade },
    { key: "initiative_crossing_frequency_chop", strategy: initiative_crossing_frequency_chop },
    { key: "relative_strength_mean_reversion", strategy: relative_strength_mean_reversion },
    { key: "cross_pressure_initiative_inversion", strategy: cross_pressure_initiative_inversion },
    { key: "dominance_handoff_exhaustion", strategy: dominance_handoff_exhaustion },
    { key: "close_location_correlation_break", strategy: close_location_correlation_break },
    { key: "correlation_range_fragmentation", strategy: correlation_range_fragmentation },
    { key: "correlation_flash_gamma_trigger", strategy: correlation_flash_gamma_trigger },
    { key: "volatility_ratio_overextension", strategy: volatility_ratio_overextension },
    { key: "rolling_vwap_center", strategy: rolling_vwap_center },
    { key: "initiative_pressure_side", strategy: initiative_pressure_side },
    { key: "decay_momentum_alignment", strategy: decay_momentum_alignment },
    { key: "initiative_pressure_gated_median", strategy: initiative_pressure_gated_median },
    { key: "roc_percentile_regime", strategy: roc_percentile_regime },
    { key: "accumulation_persistence_streak_gate", strategy: accumulation_persistence_streak_gate },
    { key: "keltner_halfband_acceptance", strategy: keltner_halfband_acceptance },
    { key: "kurtosis_distribution_alignment", strategy: kurtosis_distribution_alignment },
    { key: "mfi_median_participation_alignment", strategy: mfi_median_participation_alignment },
    { key: "skewness_distribution_alignment", strategy: skewness_distribution_alignment },
    { key: "bollinger_tail_reversion", strategy: bollinger_tail_reversion },
    { key: "consecutive_streak_reversion", strategy: consecutive_streak_reversion },
    { key: "donchian_extreme_rejection_fade", strategy: donchian_extreme_rejection_fade },
    { key: "efficiency_ratio_peak_fade", strategy: efficiency_ratio_peak_fade },
    { key: "extreme_zscore_tail_fade", strategy: extreme_zscore_tail_fade },
    { key: "gap_displacement_reversal_fade", strategy: gap_displacement_reversal_fade },
    { key: "keltner_extension_reversal", strategy: keltner_extension_reversal },
    { key: "overextended_rsi_structural_fade", strategy: overextended_rsi_structural_fade },
    { key: "typical_price_deviation_fade", strategy: typical_price_deviation_fade },
    { key: "volume_blowoff_reversion", strategy: volume_blowoff_reversion },
    { key: "cmf_momentum_vector_alignment", strategy: cmf_momentum_vector_alignment },
    { key: "decaying_boundary_momentum_capture", strategy: decaying_boundary_momentum_capture },
    { key: "hvn_value_migration_rebound", strategy: hvn_value_migration_rebound },
    { key: "initiative_pressure_accumulation_streak", strategy: initiative_pressure_accumulation_streak },
    { key: "kurtosis_tail_persistence_alignment", strategy: kurtosis_tail_persistence_alignment },
    { key: "low_entropy_ordered_breakout", strategy: low_entropy_ordered_breakout },
    { key: "low_volatility_efficiency_lead", strategy: low_volatility_efficiency_lead },
    { key: "skewness_divergence_regime_anchor", strategy: skewness_divergence_regime_anchor },
    { key: "typical_price_acceleration_anchor", strategy: typical_price_acceleration_anchor },
    { key: "volume_autocorrelation_participation_gate", strategy: volume_autocorrelation_participation_gate },
    { key: "adx_gated_median_alignment", strategy: adx_gated_median_alignment },
    { key: "close_percentile_alignment", strategy: close_percentile_alignment },
    { key: "cmf_median_alignment", strategy: cmf_median_alignment },
    { key: "donchian_midpoint_alignment", strategy: donchian_midpoint_alignment },
    { key: "efficiency_gated_median_alignment", strategy: efficiency_gated_median_alignment },
    { key: "keltner_midpoint_alignment", strategy: keltner_midpoint_alignment },
    { key: "rolling_mean_alignment", strategy: rolling_mean_alignment },
    { key: "rolling_median_alignment", strategy: rolling_median_alignment },
    { key: "trailing_range_position_alignment", strategy: trailing_range_position_alignment },
    { key: "volatility_regime_median_alignment", strategy: volatility_regime_median_alignment },
    { key: "atr_gated_median_alignment", strategy: atr_gated_median_alignment },
    { key: "autocorrelation_gated_median_alignment", strategy: autocorrelation_gated_median_alignment },
    { key: "close_location_median_alignment", strategy: close_location_median_alignment },
    { key: "momentum_percentile_alignment", strategy: momentum_percentile_alignment },
    { key: "parabolic_sar_anchor_alignment", strategy: parabolic_sar_anchor_alignment },
    { key: "rolling_gap_zscore_alignment", strategy: rolling_gap_zscore_alignment },
    { key: "trailing_hilo_midpoint_alignment", strategy: trailing_hilo_midpoint_alignment },
    { key: "typical_price_percentile_alignment", strategy: typical_price_percentile_alignment },
    { key: "volume_percentile_gated_median_alignment", strategy: volume_percentile_gated_median_alignment },
    { key: "weighted_close_median_alignment", strategy: weighted_close_median_alignment },
    { key: "directional_index_regime_alignment", strategy: directional_index_regime_alignment },
    { key: "displacement_gap_zone_alignment", strategy: displacement_gap_zone_alignment },
    { key: "distribution_rank_state_alignment", strategy: distribution_rank_state_alignment },
    { key: "keltner_midpoint_volatility_gated_alignment", strategy: keltner_midpoint_volatility_gated_alignment },
    { key: "mfi_accumulation_zone_alignment", strategy: mfi_accumulation_zone_alignment },
    { key: "range_extreme_acceptance_persistence", strategy: range_extreme_acceptance_persistence },
    { key: "rolling_median_velocity_alignment", strategy: rolling_median_velocity_alignment },
    { key: "rolling_poc_displacement_alignment", strategy: rolling_poc_displacement_alignment },
    { key: "typical_price_zscore_alignment", strategy: typical_price_zscore_alignment },
    { key: "typical_price_percentile_gap_exit_hybrid", strategy: typical_price_percentile_gap_exit_hybrid },
    { key: "initiative_pressure_low_volatility_exit_hybrid", strategy: initiative_pressure_low_volatility_exit_hybrid },
];

export function createStrategiesRecordFromManifest(
    manifest: readonly StrategyManifestEntry[] = strategyManifest
): Record<string, Strategy> {
    const strategies: Record<string, Strategy> = {};

    for (const entry of manifest) {
        if (entry.key in strategies) {
            throw new Error(`Duplicate strategy key in manifest: ${entry.key}`);
        }
        strategies[entry.key] = entry.strategy;
    }

    return strategies;
}
