import type { Strategy } from "../types/strategies";

// AUTO-GENERATED by `npm run strategies:sync-manifest`.
// Do not manually edit strategy imports or `strategyManifest` entries.

import { entropy_ratio_regime_alignment } from "./lib/entropy_ratio_regime_alignment";
import { adx_skewness_drift } from "./lib/adx_skewness_drift";
import { wick_responsive_boundary } from "./lib/wick_responsive_boundary";
import { wick_responsive_boundary_retest } from "./lib/wick_responsive_boundary_retest";
import { poly_5m_pivot_breakout_entry } from "./lib/poly_5m_pivot_breakout_entry";
import { true_range_ratio_pop_chase } from "./lib/true_range_ratio_pop_chase";
import { probability_boundary_eigen_shift } from "./lib/probability_boundary_eigen_shift";
import { volume_divergent_roc_reversion } from "./lib/volume_divergent_roc_reversion";
import { wick_imbalance_decay_fade } from "./lib/wick_imbalance_decay_fade";
import { velocity_percentile_phi_snap } from "./lib/velocity_percentile_phi_snap";
import { autocorrelation_phi_decay } from "./lib/autocorrelation_phi_decay";
import { ichimoku_conversion_base_cross } from "./lib/ichimoku_conversion_base_cross";
import { close_acceptance_streak_reversion } from "./lib/close_acceptance_streak_reversion";
import { entropy_acceleration_transition } from "./lib/entropy_acceleration_transition";
import { body_concentration_entropy_squeeze } from "./lib/body_concentration_entropy_squeeze";
import { close_acceptance_volume_conviction } from "./lib/close_acceptance_volume_conviction";
import { euphoria_volume_phi_divergence } from "./lib/euphoria_volume_phi_divergence";
import { panic_skewness_phi_trap } from "./lib/panic_skewness_phi_trap";
import { weighted_typical_phi_dislocation } from "./lib/weighted_typical_phi_dislocation";
import { volume_zscore_phi_compression } from "./lib/volume_zscore_phi_compression";
import { initiative_autocorrelation_phi_fade } from "./lib/initiative_autocorrelation_phi_fade";
import { range_clustering_momentum } from "./lib/range_clustering_momentum";
import { pivot_midpoint_anchor_fade } from "./lib/pivot_midpoint_anchor_fade";
import { volatility_percentile_reversal } from "./lib/volatility_percentile_reversal";
import { efficiency_phi_micro_streak } from "./lib/efficiency_phi_micro_streak";
import { body_proportion_phi_implosion } from "./lib/body_proportion_phi_implosion";
import { volume_thrust_phi_correlation } from "./lib/volume_thrust_phi_correlation";
import { apathy_streak_reversal } from "./lib/apathy_streak_reversal";
import { boredom_sweep_fade } from "./lib/boredom_sweep_fade";
import { fomo_choke_fade } from "./lib/fomo_choke_fade";
import { initiative_capitulation_trap } from "./lib/initiative_capitulation_trap";
import { micro_gap_rejection } from "./lib/micro_gap_rejection";
import { midpoint_gravity_fade } from "./lib/midpoint_gravity_fade";
import { return_skewness_capitulation } from "./lib/return_skewness_capitulation";
import { roc_whipsaw_trap } from "./lib/roc_whipsaw_trap";
import { toxic_flow_decoupling } from "./lib/toxic_flow_decoupling";
import { volume_exhaustion_decay } from "./lib/volume_exhaustion_decay";

export interface StrategyManifestEntry {
    key: string;
    strategy: Strategy;
    assets?: string[];
}

export const strategyManifest: readonly StrategyManifestEntry[] = [
    { key: "entropy_ratio_regime_alignment", strategy: entropy_ratio_regime_alignment },
    { key: "adx_skewness_drift", strategy: adx_skewness_drift },
    { key: "wick_responsive_boundary", strategy: wick_responsive_boundary },
    { key: "wick_responsive_boundary_retest", strategy: wick_responsive_boundary_retest },
    { key: "poly_5m_pivot_breakout_entry", strategy: poly_5m_pivot_breakout_entry },
    { key: "true_range_ratio_pop_chase", strategy: true_range_ratio_pop_chase },
    { key: "probability_boundary_eigen_shift", strategy: probability_boundary_eigen_shift },
    { key: "volume_divergent_roc_reversion", strategy: volume_divergent_roc_reversion },
    { key: "wick_imbalance_decay_fade", strategy: wick_imbalance_decay_fade },
    { key: "velocity_percentile_phi_snap", strategy: velocity_percentile_phi_snap },
    { key: "autocorrelation_phi_decay", strategy: autocorrelation_phi_decay },
    { key: "ichimoku_conversion_base_cross", strategy: ichimoku_conversion_base_cross },
    { key: "close_acceptance_streak_reversion", strategy: close_acceptance_streak_reversion },
    { key: "entropy_acceleration_transition", strategy: entropy_acceleration_transition },
    { key: "body_concentration_entropy_squeeze", strategy: body_concentration_entropy_squeeze },
    { key: "close_acceptance_volume_conviction", strategy: close_acceptance_volume_conviction },
    { key: "euphoria_volume_phi_divergence", strategy: euphoria_volume_phi_divergence },
    { key: "panic_skewness_phi_trap", strategy: panic_skewness_phi_trap },
    { key: "weighted_typical_phi_dislocation", strategy: weighted_typical_phi_dislocation },
    { key: "volume_zscore_phi_compression", strategy: volume_zscore_phi_compression },
    { key: "initiative_autocorrelation_phi_fade", strategy: initiative_autocorrelation_phi_fade },
    { key: "range_clustering_momentum", strategy: range_clustering_momentum },
    { key: "pivot_midpoint_anchor_fade", strategy: pivot_midpoint_anchor_fade },
    { key: "volatility_percentile_reversal", strategy: volatility_percentile_reversal },
    { key: "efficiency_phi_micro_streak", strategy: efficiency_phi_micro_streak },
    { key: "body_proportion_phi_implosion", strategy: body_proportion_phi_implosion },
    { key: "volume_thrust_phi_correlation", strategy: volume_thrust_phi_correlation },
    { key: "apathy_streak_reversal", strategy: apathy_streak_reversal },
    { key: "boredom_sweep_fade", strategy: boredom_sweep_fade },
    { key: "fomo_choke_fade", strategy: fomo_choke_fade },
    { key: "initiative_capitulation_trap", strategy: initiative_capitulation_trap },
    { key: "micro_gap_rejection", strategy: micro_gap_rejection },
    { key: "midpoint_gravity_fade", strategy: midpoint_gravity_fade },
    { key: "return_skewness_capitulation", strategy: return_skewness_capitulation },
    { key: "roc_whipsaw_trap", strategy: roc_whipsaw_trap },
    { key: "toxic_flow_decoupling", strategy: toxic_flow_decoupling },
    { key: "volume_exhaustion_decay", strategy: volume_exhaustion_decay },
];

export function createStrategiesRecordFromManifest(
    manifest: readonly StrategyManifestEntry[] = strategyManifest
): Record<string, Strategy> {
    const strategies: Record<string, Strategy> = {};

    for (const entry of manifest) {
        if (entry.key in strategies) {
            throw new Error(`Duplicate strategy key in manifest: ${entry.key}`);
        }
        strategies[entry.key] = entry.strategy;
    }

    return strategies;
}
