import type { Strategy } from "../types/strategies";

// AUTO-GENERATED by `npm run strategies:sync-manifest`.
// Do not manually edit strategy imports or `strategyManifest` entries.

import { keltner_channel_streak_squeeze } from "./lib/keltner_channel_streak_squeeze";
import { fractal_wick_barrier_engulfing } from "./lib/fractal_wick_barrier_engulfing";
import { median_deviation_streak } from "./lib/median_deviation_streak";
import { median_deviation_streak_v7 } from "./lib/median_deviation_streak_v7";
import { skew_entropy_polarization_entry } from "./lib/skew_entropy_polarization_entry";
import { entropy_ratio_regime_alignment } from "./lib/entropy_ratio_regime_alignment";
import { pattern_regime_alignment } from "./lib/pattern_regime_alignment";
import { value_area_median_shift } from "./lib/value_area_median_shift";
import { supertrend_friction_pinch } from "./lib/supertrend_friction_pinch";
import { candle_pattern_persistence_score } from "./lib/candle-pattern-persistence-score";
import { candle_pattern_persistence_score_stoch_mid } from "./lib/candle-pattern-persistence-score-stoch-mid";
import { candle_pattern_persistence_score_median_deviation_streak } from "./lib/candle-pattern-persistence-score-median-deviation-streak";
import { efficiency_ratio_pinch_trigger } from "./lib/efficiency_ratio_pinch_trigger";
import { dead_zone_efficiency_breakout } from "./lib/dead_zone_efficiency_breakout";
import { fractal_volatility_pinch_impulse } from "./lib/fractal_volatility_pinch_impulse";
import { crossing_persistence_event_regime } from "./lib/crossing_persistence_event_regime";
import { efficiency_pinch_roc_breakout } from "./lib/efficiency_pinch_roc_breakout";
import { cumulative_decay_regime_filter } from "./lib/cumulative_decay_regime_filter";
import { skewness_deadzone_break } from "./lib/skewness_deadzone_break";
import { crossing_churn_suppression } from "./lib/crossing_churn_suppression";
import { vwap_zscore_reversion } from "./lib/vwap_zscore_reversion";
import { supertrend_churn_resilience } from "./lib/supertrend_churn_resilience";
import { adx_skewness_drift } from "./lib/adx_skewness_drift";
import { macd_signal_pinch_explosion } from "./lib/macd_signal_pinch_explosion";
import { bollinger_skewness_ride } from "./lib/bollinger_skewness_ride";
import { supertrend_distance_zscore } from "./lib/supertrend_distance_zscore";
import { rsi_volatility_pinch_pop } from "./lib/rsi_volatility_pinch_pop";
import { volume_profile_poc_median_shift } from "./lib/volume_profile_poc_median_shift";
import { absorptive_wick_volume_spike } from "./lib/absorptive_wick_volume_spike";
import { noisy_wick_fade_reversion } from "./lib/noisy_wick_fade_reversion";
import { micro_shock_retrace_scalp } from "./lib/micro_shock_retrace_scalp";
import { keltner_pinch_momentum_break } from "./lib/keltner_pinch_momentum_break";
import { percentile_rank_deadzone_launch } from "./lib/percentile_rank_deadzone_launch";
import { zscore_kurtosis_regime } from "./lib/zscore_kurtosis_regime";
import { zscore_false_break } from "./lib/zscore_false_break";
import { close_percentile_range_entry } from "./lib/close_percentile_range_entry";
import { wick_responsive_boundary } from "./lib/wick_responsive_boundary";
import { wick_responsive_boundary_retest } from "./lib/wick_responsive_boundary_retest";
import { poly_5m_pivot_breakout_entry } from "./lib/poly_5m_pivot_breakout_entry";
import { true_range_ratio_pop_chase } from "./lib/true_range_ratio_pop_chase";
import { probability_boundary_eigen_shift } from "./lib/probability_boundary_eigen_shift";
import { volume_divergent_roc_reversion } from "./lib/volume_divergent_roc_reversion";
import { wick_imbalance_decay_fade } from "./lib/wick_imbalance_decay_fade";
import { velocity_percentile_phi_snap } from "./lib/velocity_percentile_phi_snap";
import { autocorrelation_phi_decay } from "./lib/autocorrelation_phi_decay";
import { ichimoku_conversion_base_cross } from "./lib/ichimoku_conversion_base_cross";
import { acceptance_decay_conviction_reversal } from "./lib/acceptance_decay_conviction_reversal";
import { body_direction_rhythmic_cycle_break } from "./lib/body_direction_rhythmic_cycle_break";
import { dual_timeframe_initiative_pressure_divergence } from "./lib/dual_timeframe_initiative_pressure_divergence";
import { efficiency_acceptance_dealer_conviction } from "./lib/efficiency_acceptance_dealer_conviction";
import { initiative_acceptance_correlation_collapse } from "./lib/initiative_acceptance_correlation_collapse";
import { initiative_crossing_dealer_commitment } from "./lib/initiative_crossing_dealer_commitment";
import { midpoint_deviation_dual_timeframe_fade } from "./lib/midpoint_deviation_dual_timeframe_fade";
import { range_skewness_dealer_inflection } from "./lib/range_skewness_dealer_inflection";
import { span_acceptance_pinning_entry } from "./lib/span_acceptance_pinning_entry";
import { volume_weighted_acceptance_zscore_thrust } from "./lib/volume_weighted_acceptance_zscore_thrust";
import { acceptance_crossing_whipsaw_exhaustion } from "./lib/acceptance_crossing_whipsaw_exhaustion";
import { body_volume_correlation_regime_flip } from "./lib/body_volume_correlation_regime_flip";
import { close_acceptance_entropy_structure_break } from "./lib/close_acceptance_entropy_structure_break";
import { initiative_pressure_kurtosis_peak_fade } from "./lib/initiative_pressure_kurtosis_peak_fade";
import { initiative_pressure_skew_reversal } from "./lib/initiative_pressure_skew_reversal";
import { rolling_minmax_initiative_failure } from "./lib/rolling_minmax_initiative_failure";
import { sweep_reclaim_initiative_absorption } from "./lib/sweep_reclaim_initiative_absorption";
import { trailing_span_initiative_divergence } from "./lib/trailing_span_initiative_divergence";
import { triple_compression_dealer_launch } from "./lib/triple_compression_dealer_launch";
import { vol_term_structure_ratio_break } from "./lib/vol_term_structure_ratio_break";
import { acceptance_roc_dealer_repositioning } from "./lib/acceptance_roc_dealer_repositioning";
import { close_midpoint_cascade_continuation } from "./lib/close_midpoint_cascade_continuation";
import { dealer_cascade_acceptance_exhaustion } from "./lib/dealer_cascade_acceptance_exhaustion";
import { directional_volume_autocorrelation_flip } from "./lib/directional_volume_autocorrelation_flip";
import { gamma_proxy_decay_acceleration_snap } from "./lib/gamma_proxy_decay_acceleration_snap";
import { initiative_pressure_persistence_regime } from "./lib/initiative_pressure_persistence_regime";
import { realized_vol_premium_overstatement } from "./lib/realized_vol_premium_overstatement";
import { strike_proximity_acceptance_rejection } from "./lib/strike_proximity_acceptance_rejection";
import { theta_weighted_momentum_zero_cross } from "./lib/theta_weighted_momentum_zero_cross";
import { volume_concentration_dealer_cycle_start } from "./lib/volume_concentration_dealer_cycle_start";
import { body_direction_autocorrelation } from "./lib/body_direction_autocorrelation";
import { close_acceptance_streak_reversion } from "./lib/close_acceptance_streak_reversion";
import { decay_momentum_inflection } from "./lib/decay_momentum_inflection";
import { initiative_pressure_rank_exhaustion } from "./lib/initiative_pressure_rank_exhaustion";
import { open_close_drift_streak_reversion } from "./lib/open_close_drift_streak_reversion";
import { price_volume_decoupling_reversion } from "./lib/price_volume_decoupling_reversion";
import { range_body_divergence_reversal } from "./lib/range_body_divergence_reversal";
import { skewness_extreme_reversion } from "./lib/skewness_extreme_reversion";
import { sweep_reclaim_trap_entry } from "./lib/sweep_reclaim_trap_entry";
import { up_down_return_asymmetry } from "./lib/up_down_return_asymmetry";
import { body_midpoint_delta_conviction } from "./lib/body_midpoint_delta_conviction";
import { body_sentiment_shift_entry } from "./lib/body_sentiment_shift_entry";
import { cumulative_directional_volume_flip } from "./lib/cumulative_directional_volume_flip";
import { dual_timeframe_body_expansion } from "./lib/dual_timeframe_body_expansion";
import { entropy_acceleration_transition } from "./lib/entropy_acceleration_transition";
import { pivot_deviation_scaled_break } from "./lib/pivot_deviation_scaled_break";
import { pivot_range_compression_break } from "./lib/pivot_range_compression_break";
import { price_volume_crossing_divergence } from "./lib/price_volume_crossing_divergence";
import { settlement_bias_zscore_reversion } from "./lib/settlement_bias_zscore_reversion";
import { trailing_span_compression_breakout } from "./lib/trailing_span_compression_breakout";
import { body_concentration_entropy_squeeze } from "./lib/body_concentration_entropy_squeeze";
import { close_acceptance_volume_conviction } from "./lib/close_acceptance_volume_conviction";
import { close_midpoint_deviation_persistence } from "./lib/close_midpoint_deviation_persistence";
import { efficiency_ratio_volume_confirmation } from "./lib/efficiency_ratio_volume_confirmation";
import { gap_settlement_reversion } from "./lib/gap_settlement_reversion";
import { initiative_pressure_divergence_fade } from "./lib/initiative_pressure_divergence_fade";
import { range_velocity_stall_reversion } from "./lib/range_velocity_stall_reversion";
import { sweep_reclaim_momentum_continuation } from "./lib/sweep_reclaim_momentum_continuation";
import { volume_participation_skew_reversal } from "./lib/volume_participation_skew_reversal";
import { wick_imbalance_autocorr_regime } from "./lib/wick_imbalance_autocorr_regime";

export interface StrategyManifestEntry {
    key: string;
    strategy: Strategy;
    assets?: string[];
}

export const strategyManifest: readonly StrategyManifestEntry[] = [
    { key: "keltner_channel_streak_squeeze", strategy: keltner_channel_streak_squeeze },
    { key: "fractal_wick_barrier_engulfing", strategy: fractal_wick_barrier_engulfing },
    { key: "median_deviation_streak", strategy: median_deviation_streak },
    { key: "median_deviation_streak_v7", strategy: median_deviation_streak_v7 },
    { key: "skew_entropy_polarization_entry", strategy: skew_entropy_polarization_entry },
    { key: "entropy_ratio_regime_alignment", strategy: entropy_ratio_regime_alignment },
    { key: "pattern_regime_alignment", strategy: pattern_regime_alignment },
    { key: "value_area_median_shift", strategy: value_area_median_shift },
    { key: "supertrend_friction_pinch", strategy: supertrend_friction_pinch },
    { key: "candle_pattern_persistence_score", strategy: candle_pattern_persistence_score },
    { key: "candle_pattern_persistence_score_stoch_mid", strategy: candle_pattern_persistence_score_stoch_mid },
    { key: "candle_pattern_persistence_score_median_deviation_streak", strategy: candle_pattern_persistence_score_median_deviation_streak },
    { key: "efficiency_ratio_pinch_trigger", strategy: efficiency_ratio_pinch_trigger },
    { key: "dead_zone_efficiency_breakout", strategy: dead_zone_efficiency_breakout },
    { key: "fractal_volatility_pinch_impulse", strategy: fractal_volatility_pinch_impulse },
    { key: "crossing_persistence_event_regime", strategy: crossing_persistence_event_regime },
    { key: "efficiency_pinch_roc_breakout", strategy: efficiency_pinch_roc_breakout },
    { key: "cumulative_decay_regime_filter", strategy: cumulative_decay_regime_filter },
    { key: "skewness_deadzone_break", strategy: skewness_deadzone_break },
    { key: "crossing_churn_suppression", strategy: crossing_churn_suppression },
    { key: "vwap_zscore_reversion", strategy: vwap_zscore_reversion },
    { key: "supertrend_churn_resilience", strategy: supertrend_churn_resilience },
    { key: "adx_skewness_drift", strategy: adx_skewness_drift },
    { key: "macd_signal_pinch_explosion", strategy: macd_signal_pinch_explosion },
    { key: "bollinger_skewness_ride", strategy: bollinger_skewness_ride },
    { key: "supertrend_distance_zscore", strategy: supertrend_distance_zscore },
    { key: "rsi_volatility_pinch_pop", strategy: rsi_volatility_pinch_pop },
    { key: "volume_profile_poc_median_shift", strategy: volume_profile_poc_median_shift },
    { key: "absorptive_wick_volume_spike", strategy: absorptive_wick_volume_spike },
    { key: "noisy_wick_fade_reversion", strategy: noisy_wick_fade_reversion },
    { key: "micro_shock_retrace_scalp", strategy: micro_shock_retrace_scalp },
    { key: "keltner_pinch_momentum_break", strategy: keltner_pinch_momentum_break },
    { key: "percentile_rank_deadzone_launch", strategy: percentile_rank_deadzone_launch },
    { key: "zscore_kurtosis_regime", strategy: zscore_kurtosis_regime },
    { key: "zscore_false_break", strategy: zscore_false_break },
    { key: "close_percentile_range_entry", strategy: close_percentile_range_entry },
    { key: "wick_responsive_boundary", strategy: wick_responsive_boundary },
    { key: "wick_responsive_boundary_retest", strategy: wick_responsive_boundary_retest },
    { key: "poly_5m_pivot_breakout_entry", strategy: poly_5m_pivot_breakout_entry },
    { key: "true_range_ratio_pop_chase", strategy: true_range_ratio_pop_chase },
    { key: "probability_boundary_eigen_shift", strategy: probability_boundary_eigen_shift },
    { key: "volume_divergent_roc_reversion", strategy: volume_divergent_roc_reversion },
    { key: "wick_imbalance_decay_fade", strategy: wick_imbalance_decay_fade },
    { key: "velocity_percentile_phi_snap", strategy: velocity_percentile_phi_snap },
    { key: "autocorrelation_phi_decay", strategy: autocorrelation_phi_decay },
    { key: "ichimoku_conversion_base_cross", strategy: ichimoku_conversion_base_cross },
    { key: "acceptance_decay_conviction_reversal", strategy: acceptance_decay_conviction_reversal },
    { key: "body_direction_rhythmic_cycle_break", strategy: body_direction_rhythmic_cycle_break },
    { key: "dual_timeframe_initiative_pressure_divergence", strategy: dual_timeframe_initiative_pressure_divergence },
    { key: "efficiency_acceptance_dealer_conviction", strategy: efficiency_acceptance_dealer_conviction },
    { key: "initiative_acceptance_correlation_collapse", strategy: initiative_acceptance_correlation_collapse },
    { key: "initiative_crossing_dealer_commitment", strategy: initiative_crossing_dealer_commitment },
    { key: "midpoint_deviation_dual_timeframe_fade", strategy: midpoint_deviation_dual_timeframe_fade },
    { key: "range_skewness_dealer_inflection", strategy: range_skewness_dealer_inflection },
    { key: "span_acceptance_pinning_entry", strategy: span_acceptance_pinning_entry },
    { key: "volume_weighted_acceptance_zscore_thrust", strategy: volume_weighted_acceptance_zscore_thrust },
    { key: "acceptance_crossing_whipsaw_exhaustion", strategy: acceptance_crossing_whipsaw_exhaustion },
    { key: "body_volume_correlation_regime_flip", strategy: body_volume_correlation_regime_flip },
    { key: "close_acceptance_entropy_structure_break", strategy: close_acceptance_entropy_structure_break },
    { key: "initiative_pressure_kurtosis_peak_fade", strategy: initiative_pressure_kurtosis_peak_fade },
    { key: "initiative_pressure_skew_reversal", strategy: initiative_pressure_skew_reversal },
    { key: "rolling_minmax_initiative_failure", strategy: rolling_minmax_initiative_failure },
    { key: "sweep_reclaim_initiative_absorption", strategy: sweep_reclaim_initiative_absorption },
    { key: "trailing_span_initiative_divergence", strategy: trailing_span_initiative_divergence },
    { key: "triple_compression_dealer_launch", strategy: triple_compression_dealer_launch },
    { key: "vol_term_structure_ratio_break", strategy: vol_term_structure_ratio_break },
    { key: "acceptance_roc_dealer_repositioning", strategy: acceptance_roc_dealer_repositioning },
    { key: "close_midpoint_cascade_continuation", strategy: close_midpoint_cascade_continuation },
    { key: "dealer_cascade_acceptance_exhaustion", strategy: dealer_cascade_acceptance_exhaustion },
    { key: "directional_volume_autocorrelation_flip", strategy: directional_volume_autocorrelation_flip },
    { key: "gamma_proxy_decay_acceleration_snap", strategy: gamma_proxy_decay_acceleration_snap },
    { key: "initiative_pressure_persistence_regime", strategy: initiative_pressure_persistence_regime },
    { key: "realized_vol_premium_overstatement", strategy: realized_vol_premium_overstatement },
    { key: "strike_proximity_acceptance_rejection", strategy: strike_proximity_acceptance_rejection },
    { key: "theta_weighted_momentum_zero_cross", strategy: theta_weighted_momentum_zero_cross },
    { key: "volume_concentration_dealer_cycle_start", strategy: volume_concentration_dealer_cycle_start },
    { key: "body_direction_autocorrelation", strategy: body_direction_autocorrelation },
    { key: "close_acceptance_streak_reversion", strategy: close_acceptance_streak_reversion },
    { key: "decay_momentum_inflection", strategy: decay_momentum_inflection },
    { key: "initiative_pressure_rank_exhaustion", strategy: initiative_pressure_rank_exhaustion },
    { key: "open_close_drift_streak_reversion", strategy: open_close_drift_streak_reversion },
    { key: "price_volume_decoupling_reversion", strategy: price_volume_decoupling_reversion },
    { key: "range_body_divergence_reversal", strategy: range_body_divergence_reversal },
    { key: "skewness_extreme_reversion", strategy: skewness_extreme_reversion },
    { key: "sweep_reclaim_trap_entry", strategy: sweep_reclaim_trap_entry },
    { key: "up_down_return_asymmetry", strategy: up_down_return_asymmetry },
    { key: "body_midpoint_delta_conviction", strategy: body_midpoint_delta_conviction },
    { key: "body_sentiment_shift_entry", strategy: body_sentiment_shift_entry },
    { key: "cumulative_directional_volume_flip", strategy: cumulative_directional_volume_flip },
    { key: "dual_timeframe_body_expansion", strategy: dual_timeframe_body_expansion },
    { key: "entropy_acceleration_transition", strategy: entropy_acceleration_transition },
    { key: "pivot_deviation_scaled_break", strategy: pivot_deviation_scaled_break },
    { key: "pivot_range_compression_break", strategy: pivot_range_compression_break },
    { key: "price_volume_crossing_divergence", strategy: price_volume_crossing_divergence },
    { key: "settlement_bias_zscore_reversion", strategy: settlement_bias_zscore_reversion },
    { key: "trailing_span_compression_breakout", strategy: trailing_span_compression_breakout },
    { key: "body_concentration_entropy_squeeze", strategy: body_concentration_entropy_squeeze },
    { key: "close_acceptance_volume_conviction", strategy: close_acceptance_volume_conviction },
    { key: "close_midpoint_deviation_persistence", strategy: close_midpoint_deviation_persistence },
    { key: "efficiency_ratio_volume_confirmation", strategy: efficiency_ratio_volume_confirmation },
    { key: "gap_settlement_reversion", strategy: gap_settlement_reversion },
    { key: "initiative_pressure_divergence_fade", strategy: initiative_pressure_divergence_fade },
    { key: "range_velocity_stall_reversion", strategy: range_velocity_stall_reversion },
    { key: "sweep_reclaim_momentum_continuation", strategy: sweep_reclaim_momentum_continuation },
    { key: "volume_participation_skew_reversal", strategy: volume_participation_skew_reversal },
    { key: "wick_imbalance_autocorr_regime", strategy: wick_imbalance_autocorr_regime },
];

export function createStrategiesRecordFromManifest(
    manifest: readonly StrategyManifestEntry[] = strategyManifest
): Record<string, Strategy> {
    const strategies: Record<string, Strategy> = {};

    for (const entry of manifest) {
        if (entry.key in strategies) {
            throw new Error(`Duplicate strategy key in manifest: ${entry.key}`);
        }
        strategies[entry.key] = entry.strategy;
    }

    return strategies;
}
