import { getRequiredElement } from "../dom-utils";

export const EXECUTION_LAB_IDS = {
    root: "executionlabTab",
    startButton: "executionLabStartPaper",
    stopButton: "executionLabStopPaper",
    executionMode: "executionLabExecutionMode",
    startMinerButton: "executionLabStartMiner",
    stopMinerButton: "executionLabStopMiner",
    stakeInput: "executionLabStakeUsd",
    liveOrderMode: "executionLabLiveOrderMode",
    liveTakerOrderType: "executionLabLiveTakerOrderType",
    liveSizingMode: "executionLabLiveSizingMode",
    liveMaxStakeUsd: "executionLabLiveMaxStakeUsd",
    liveEntrySlippageCents: "executionLabLiveEntrySlippageCents",
    liveExitSlippageCents: "executionLabLiveExitSlippageCents",
    protectionTakeProfitEnabled: "executionLabPolymarketTakeProfitEnabled",
    protectionTakeProfitCents: "executionLabPolymarketTakeProfitCents",
    protectionStopLossEnabled: "executionLabPolymarketStopLossEnabled",
    protectionStopLossCents: "executionLabPolymarketStopLossCents",
    liveLimitOffsetEnabled: "executionLabLiveLimitOffsetEnabled",
    liveLimitOffsetCents: "executionLabLiveLimitOffsetCents",
    liveLimitFixedPriceEnabled: "executionLabLiveLimitFixedPriceEnabled",
    liveLimitFixedPriceCents: "executionLabLiveLimitFixedPriceCents",
    liveLimitCancelAllOnExit: "executionLabLiveLimitCancelAllOnExit",
    status: "executionLabStatus",
    copyDiagnosticsButton: "executionLabCopyDiagnostics",
    diagnosticsSummary: "executionLabDiagnosticsSummary",
    configSnapshot: "executionLabConfigSnapshot",
    latestCandle: "executionLabLatestCandle",
    quoteSnapshot: "executionLabQuoteSnapshot",
    feedLag: "executionLabFeedLag",
    quoteAge: "executionLabQuoteAge",
    activeEvent: "executionLabActiveEvent",
    liveExecutorStatus: "executionLabLiveExecutorStatus",
    minerStatus: "executionLabMinerStatus",
    logPath: "executionLabLogPath",
    latestSignal: "executionLabLatestSignal",
    signalParity: "executionLabSignalParity",
    signalMismatch: "executionLabSignalMismatch",
    openPosition: "executionLabOpenPosition",
    livePosition: "executionLabLivePosition",
    liveResult: "executionLabLiveResult",
    sessionPnl: "executionLabSessionPnl",
    decisionCard: "executionLabDecisionCard",
    decisionStatus: "executionLabDecisionStatus",
    signalState: "executionLabSignalState",
    decisionReason: "executionLabDecisionReason",
    decisionQuote: "executionLabDecisionQuote",
    decisionCurrentPrice: "executionLabDecisionCurrentPrice",
    decisionRejectedLabel: "executionLabDecisionRejectedLabel",
    decisionRejectedEntry: "executionLabDecisionRejectedEntry",
    paperMetrics: "executionLabPaperMetrics",
    comparisonSource: "executionLabComparisonSource",
    comparisonSavedConfig: "executionLabComparisonSavedConfig",
    runComparisonButton: "executionLabRunComparison",
    comparisonStatus: "executionLabComparisonStatus",
    comparisonMetrics: "executionLabComparisonMetrics",
    recentTrades: "executionLabRecentTrades",
} as const;

export const EXECUTION_LAB_REQUIRED_IDS = Object.values(EXECUTION_LAB_IDS);

export interface ExecutionLabDom {
    root: HTMLElement;
    startButton: HTMLButtonElement;
    stopButton: HTMLButtonElement;
    executionMode: HTMLSelectElement;
    startMinerButton: HTMLButtonElement;
    stopMinerButton: HTMLButtonElement;
    stakeInput: HTMLInputElement;
    liveOrderMode: HTMLSelectElement;
    liveTakerOrderType: HTMLSelectElement;
    liveSizingMode: HTMLSelectElement;
    liveMaxStakeUsd: HTMLInputElement;
    liveEntrySlippageCents: HTMLInputElement;
    liveExitSlippageCents: HTMLInputElement;
    protectionTakeProfitEnabled: HTMLInputElement;
    protectionTakeProfitCents: HTMLInputElement;
    protectionStopLossEnabled: HTMLInputElement;
    protectionStopLossCents: HTMLInputElement;
    liveLimitOffsetEnabled: HTMLInputElement;
    liveLimitOffsetCents: HTMLInputElement;
    liveLimitFixedPriceEnabled: HTMLInputElement;
    liveLimitFixedPriceCents: HTMLInputElement;
    liveLimitCancelAllOnExit: HTMLInputElement;
    status: HTMLElement;
    copyDiagnosticsButton: HTMLButtonElement;
    diagnosticsSummary: HTMLElement;
    configSnapshot: HTMLElement;
    latestCandle: HTMLElement;
    quoteSnapshot: HTMLElement;
    feedLag: HTMLElement;
    quoteAge: HTMLElement;
    activeEvent: HTMLElement;
    liveExecutorStatus: HTMLElement;
    minerStatus: HTMLElement;
    logPath: HTMLElement;
    latestSignal: HTMLElement;
    signalParity: HTMLElement;
    signalMismatch: HTMLElement;
    openPosition: HTMLElement;
    livePosition: HTMLElement;
    liveResult: HTMLElement;
    sessionPnl: HTMLElement;
    decisionCard: HTMLElement;
    decisionStatus: HTMLElement;
    signalState: HTMLElement;
    decisionReason: HTMLElement;
    decisionQuote: HTMLElement;
    decisionCurrentPrice: HTMLElement;
    decisionRejectedLabel: HTMLElement;
    decisionRejectedEntry: HTMLElement;
    paperMetrics: HTMLElement;
    comparisonSource: HTMLSelectElement;
    comparisonSavedConfig: HTMLSelectElement;
    runComparisonButton: HTMLButtonElement;
    comparisonStatus: HTMLElement;
    comparisonMetrics: HTMLElement;
    recentTrades: HTMLElement;
}

export function queryExecutionLabDom(): ExecutionLabDom {
    return {
        root: getRequiredElement(EXECUTION_LAB_IDS.root),
        startButton: getRequiredElement<HTMLButtonElement>(EXECUTION_LAB_IDS.startButton),
        stopButton: getRequiredElement<HTMLButtonElement>(EXECUTION_LAB_IDS.stopButton),
        executionMode: getRequiredElement<HTMLSelectElement>(EXECUTION_LAB_IDS.executionMode),
        startMinerButton: getRequiredElement<HTMLButtonElement>(EXECUTION_LAB_IDS.startMinerButton),
        stopMinerButton: getRequiredElement<HTMLButtonElement>(EXECUTION_LAB_IDS.stopMinerButton),
        stakeInput: getRequiredElement<HTMLInputElement>(EXECUTION_LAB_IDS.stakeInput),
        liveOrderMode: getRequiredElement<HTMLSelectElement>(EXECUTION_LAB_IDS.liveOrderMode),
        liveTakerOrderType: getRequiredElement<HTMLSelectElement>(EXECUTION_LAB_IDS.liveTakerOrderType),
        liveSizingMode: getRequiredElement<HTMLSelectElement>(EXECUTION_LAB_IDS.liveSizingMode),
        liveMaxStakeUsd: getRequiredElement<HTMLInputElement>(EXECUTION_LAB_IDS.liveMaxStakeUsd),
        liveEntrySlippageCents: getRequiredElement<HTMLInputElement>(EXECUTION_LAB_IDS.liveEntrySlippageCents),
        liveExitSlippageCents: getRequiredElement<HTMLInputElement>(EXECUTION_LAB_IDS.liveExitSlippageCents),
        protectionTakeProfitEnabled: getRequiredElement<HTMLInputElement>(EXECUTION_LAB_IDS.protectionTakeProfitEnabled),
        protectionTakeProfitCents: getRequiredElement<HTMLInputElement>(EXECUTION_LAB_IDS.protectionTakeProfitCents),
        protectionStopLossEnabled: getRequiredElement<HTMLInputElement>(EXECUTION_LAB_IDS.protectionStopLossEnabled),
        protectionStopLossCents: getRequiredElement<HTMLInputElement>(EXECUTION_LAB_IDS.protectionStopLossCents),
        liveLimitOffsetEnabled: getRequiredElement<HTMLInputElement>(EXECUTION_LAB_IDS.liveLimitOffsetEnabled),
        liveLimitOffsetCents: getRequiredElement<HTMLInputElement>(EXECUTION_LAB_IDS.liveLimitOffsetCents),
        liveLimitFixedPriceEnabled: getRequiredElement<HTMLInputElement>(EXECUTION_LAB_IDS.liveLimitFixedPriceEnabled),
        liveLimitFixedPriceCents: getRequiredElement<HTMLInputElement>(EXECUTION_LAB_IDS.liveLimitFixedPriceCents),
        liveLimitCancelAllOnExit: getRequiredElement<HTMLInputElement>(EXECUTION_LAB_IDS.liveLimitCancelAllOnExit),
        status: getRequiredElement(EXECUTION_LAB_IDS.status),
        copyDiagnosticsButton: getRequiredElement<HTMLButtonElement>(EXECUTION_LAB_IDS.copyDiagnosticsButton),
        diagnosticsSummary: getRequiredElement(EXECUTION_LAB_IDS.diagnosticsSummary),
        configSnapshot: getRequiredElement(EXECUTION_LAB_IDS.configSnapshot),
        latestCandle: getRequiredElement(EXECUTION_LAB_IDS.latestCandle),
        quoteSnapshot: getRequiredElement(EXECUTION_LAB_IDS.quoteSnapshot),
        feedLag: getRequiredElement(EXECUTION_LAB_IDS.feedLag),
        quoteAge: getRequiredElement(EXECUTION_LAB_IDS.quoteAge),
        activeEvent: getRequiredElement(EXECUTION_LAB_IDS.activeEvent),
        liveExecutorStatus: getRequiredElement(EXECUTION_LAB_IDS.liveExecutorStatus),
        minerStatus: getRequiredElement(EXECUTION_LAB_IDS.minerStatus),
        logPath: getRequiredElement(EXECUTION_LAB_IDS.logPath),
        latestSignal: getRequiredElement(EXECUTION_LAB_IDS.latestSignal),
        signalParity: getRequiredElement(EXECUTION_LAB_IDS.signalParity),
        signalMismatch: getRequiredElement(EXECUTION_LAB_IDS.signalMismatch),
        openPosition: getRequiredElement(EXECUTION_LAB_IDS.openPosition),
        livePosition: getRequiredElement(EXECUTION_LAB_IDS.livePosition),
        liveResult: getRequiredElement(EXECUTION_LAB_IDS.liveResult),
        sessionPnl: getRequiredElement(EXECUTION_LAB_IDS.sessionPnl),
        decisionCard: getRequiredElement(EXECUTION_LAB_IDS.decisionCard),
        decisionStatus: getRequiredElement(EXECUTION_LAB_IDS.decisionStatus),
        signalState: getRequiredElement(EXECUTION_LAB_IDS.signalState),
        decisionReason: getRequiredElement(EXECUTION_LAB_IDS.decisionReason),
        decisionQuote: getRequiredElement(EXECUTION_LAB_IDS.decisionQuote),
        decisionCurrentPrice: getRequiredElement(EXECUTION_LAB_IDS.decisionCurrentPrice),
        decisionRejectedLabel: getRequiredElement(EXECUTION_LAB_IDS.decisionRejectedLabel),
        decisionRejectedEntry: getRequiredElement(EXECUTION_LAB_IDS.decisionRejectedEntry),
        paperMetrics: getRequiredElement(EXECUTION_LAB_IDS.paperMetrics),
        comparisonSource: getRequiredElement<HTMLSelectElement>(EXECUTION_LAB_IDS.comparisonSource),
        comparisonSavedConfig: getRequiredElement<HTMLSelectElement>(EXECUTION_LAB_IDS.comparisonSavedConfig),
        runComparisonButton: getRequiredElement<HTMLButtonElement>(EXECUTION_LAB_IDS.runComparisonButton),
        comparisonStatus: getRequiredElement(EXECUTION_LAB_IDS.comparisonStatus),
        comparisonMetrics: getRequiredElement(EXECUTION_LAB_IDS.comparisonMetrics),
        recentTrades: getRequiredElement(EXECUTION_LAB_IDS.recentTrades),
    };
}
