import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const currentFilePath = fileURLToPath(import.meta.url);
const scriptsDir = path.dirname(currentFilePath);
const repoRoot = path.resolve(scriptsDir, "..");
const strategyLibDir = path.join(repoRoot, "lib", "strategies", "lib");
const manifestPath = path.join(repoRoot, "lib", "strategies", "manifest.ts");

const STRATEGY_EXPORT_PATTERN = /export\s+const\s+([a-zA-Z][a-zA-Z0-9_]*)\s*:\s*Strategy\s*=/g;
const MANIFEST_KEY_PATTERN = /key:\s*"([^"]+)"/g;
const VALID_STRATEGY_KEY_PATTERN = /^[a-z][a-z0-9_]*$/;

export interface StrategyModuleDefinition {
    key: string;
    exportName: string;
    importPath: string;
}

function normalizeLineEndings(value: string): string {
    return value.replace(/\r\n/g, "\n");
}

function readCurrentManifestOrder(): string[] {
    const source = normalizeLineEndings(readFileSync(manifestPath, "utf8"));
    const keys: string[] = [];
    let match: RegExpExecArray | null;

    while ((match = MANIFEST_KEY_PATTERN.exec(source)) !== null) {
        keys.push(match[1]);
    }

    return keys;
}

function extractStrategyExportName(source: string, fileName: string): string | null {
    const matches = [...source.matchAll(STRATEGY_EXPORT_PATTERN)];
    if (matches.length === 0) {
        return null;
    }
    if (matches.length > 1) {
        throw new Error(`Expected exactly one Strategy export in ${fileName}, found ${matches.length}.`);
    }

    return matches[0][1];
}

export function collectStrategyModuleDefinitions(): StrategyModuleDefinition[] {
    const existingOrder = readCurrentManifestOrder();
    const existingRank = new Map(existingOrder.map((key, index) => [key, index]));
    const strategyFiles = readdirSync(strategyLibDir)
        .filter((fileName) => fileName.endsWith(".ts"))
        .sort((left, right) => left.localeCompare(right));

    const definitions: StrategyModuleDefinition[] = [];
    for (const fileName of strategyFiles) {
        const source = readFileSync(path.join(strategyLibDir, fileName), "utf8");
        const exportName = extractStrategyExportName(source, fileName);
        if (!exportName) {
            continue;
        }

        if (!VALID_STRATEGY_KEY_PATTERN.test(exportName)) {
            throw new Error(`Strategy export "${exportName}" in ${fileName} is not a valid strategy key.`);
        }

        definitions.push({
            key: exportName,
            exportName,
            importPath: `./lib/${fileName.replace(/\.ts$/, "")}`,
        });
    }

    definitions.sort((left, right) => {
        const leftRank = existingRank.get(left.key);
        const rightRank = existingRank.get(right.key);

        if (leftRank !== undefined && rightRank !== undefined) {
            return leftRank - rightRank;
        }
        if (leftRank !== undefined) {
            return -1;
        }
        if (rightRank !== undefined) {
            return 1;
        }

        return left.key.localeCompare(right.key);
    });

    return definitions;
}

export function generateStrategyManifestSource(
    definitions: readonly StrategyModuleDefinition[] = collectStrategyModuleDefinitions()
): string {
    const importLines = definitions.map(
        (definition) => `import { ${definition.exportName} } from "${definition.importPath}";`
    );
    const entryLines = definitions.map(
        (definition) => `    { key: "${definition.key}", strategy: ${definition.exportName} },`
    );

    return [
        'import type { Strategy } from "../types/strategies";',
        "",
        "// AUTO-GENERATED by `npm run strategies:sync-manifest`.",
        "// Do not manually edit strategy imports or `strategyManifest` entries.",
        "",
        ...importLines,
        "",
        "export interface StrategyManifestEntry {",
        "    key: string;",
        "    strategy: Strategy;",
        "    assets?: string[];",
        "}",
        "",
        "export const strategyManifest: readonly StrategyManifestEntry[] = [",
        ...entryLines,
        "];",
        "",
        "export function createStrategiesRecordFromManifest(",
        "    manifest: readonly StrategyManifestEntry[] = strategyManifest",
        "): Record<string, Strategy> {",
        "    const strategies: Record<string, Strategy> = {};",
        "",
        "    for (const entry of manifest) {",
        "        if (entry.key in strategies) {",
        "            throw new Error(`Duplicate strategy key in manifest: ${entry.key}`);",
        "        }",
        "        strategies[entry.key] = entry.strategy;",
        "    }",
        "",
        "    return strategies;",
        "}",
        "",
    ].join("\n");
}

export function getStrategyManifestPath(): string {
    return manifestPath;
}

export function syncStrategyManifest(): { path: string; count: number } {
    const definitions = collectStrategyModuleDefinitions();
    writeFileSync(manifestPath, generateStrategyManifestSource(definitions), "utf8");
    return {
        path: manifestPath,
        count: definitions.length,
    };
}
