import { getRequiredElement } from "../dom-utils";

/**
 * Structural DOM contract for the Batch Backtest tab.
 *
 * Mirrors the `lib/hunt/hunt-dom.ts` pattern: a required-ids array used by
 * `tests/feature-dom-contracts.spec.ts`, plus a `create*Dom()` factory that
 * resolves the elements through `getRequiredElement`.
 *
 * Every id here must also exist in `html-partials/tab-batch-backtest.html`.
 */
export const BATCH_BACKTEST_REQUIRED_IDS = [
    "batchbacktestTab",
    "batchBacktestSymbols",
    "batchBacktestSymbolTemplate",
    "batchBacktestUseCurrent",
    "batchBacktestClear",
    "batchBacktestBalancedAssets",
    "batchBacktestBalancedMaxPairs",
    "batchBacktestBalancedSeed",
    "batchBacktestBalancedGenerateBtn",
    "batchBacktestBalancedCopyBtn",
    "batchBacktestBalancedSummary",
    "batchBacktestRunBtn",
    "batchBacktestStopBtn",
    "batchBacktestCopyBtn",
    "batchBacktestCopyBenchmarkBtn",
    "batchBacktestMineBtn",
    "batchBacktestCopyMinerBtn",
    "batchBacktestAutoRunStability",
    "batchBacktestStabilitySubsetSize",
    "batchBacktestStabilityReruns",
    "batchBacktestStabilitySeed",
    "batchBacktestStabilityMineBtn",
    "batchBacktestCopyStabilityBtn",
    "batchBacktestOpenScoreUsdBtn",
    "batchBacktestCopyOpenScoreUsdBtn",
    "batchBacktestOpenScoreUsdSummary",
    "batchBacktestOpenScoreUsdFrom",
    "batchBacktestOpenScoreUsdTo",
    "batchBacktestOpenScoreUsdHorizons",
    "batchBacktestProgress",
    "batchBacktestProgressFill",
    "batchBacktestProgressText",
    "batchBacktestStatus",
    "batchBacktestSummary",
    "batchBacktestSummaryGrid",
    "batchBacktestMinerSummary",
    "batchBacktestMinerResults",
    "batchBacktestResults",
    "batchBacktestEmpty",
    "batchBacktestSp500TopMeanRunBtn",
    "batchBacktestSp500TopMeanStopBtn",
    "batchBacktestSp500TopMeanHorizons",
    "batchBacktestSp500TopMeanWorkers",
    "batchBacktestSp500TopMeanMaxPairs",
    "batchBacktestSp500TopMeanCopyBtn",
    "batchBacktestSp500TopMeanDownloadBtn",
    "batchBacktestSp500TopMeanCopyDiagnosticBtn",
    "batchBacktestSp500TopMeanCoverageSummary",
    "batchBacktestSp500TopMeanProgressText",
    "batchBacktestSp500TopMeanResults",
    "batchBacktestSp500TopMeanDiagnostic",
] as const;

export function createBatchBacktestDom() {
    return {
        batchbacktestTab: getRequiredElement("batchbacktestTab"),
        batchBacktestSymbols: getRequiredElement<HTMLTextAreaElement>("batchBacktestSymbols"),
        batchBacktestSymbolTemplate: getRequiredElement<HTMLSelectElement>("batchBacktestSymbolTemplate"),
        batchBacktestUseCurrent: getRequiredElement<HTMLButtonElement>("batchBacktestUseCurrent"),
        batchBacktestClear: getRequiredElement<HTMLButtonElement>("batchBacktestClear"),
        batchBacktestBalancedAssets: getRequiredElement<HTMLTextAreaElement>("batchBacktestBalancedAssets"),
        batchBacktestBalancedMaxPairs: getRequiredElement<HTMLInputElement>("batchBacktestBalancedMaxPairs"),
        batchBacktestBalancedSeed: getRequiredElement<HTMLInputElement>("batchBacktestBalancedSeed"),
        batchBacktestBalancedGenerateBtn: getRequiredElement<HTMLButtonElement>("batchBacktestBalancedGenerateBtn"),
        batchBacktestBalancedCopyBtn: getRequiredElement<HTMLButtonElement>("batchBacktestBalancedCopyBtn"),
        batchBacktestBalancedSummary: getRequiredElement<HTMLDivElement>("batchBacktestBalancedSummary"),
        batchBacktestRunBtn: getRequiredElement<HTMLButtonElement>("batchBacktestRunBtn"),
        batchBacktestStopBtn: getRequiredElement<HTMLButtonElement>("batchBacktestStopBtn"),
        batchBacktestCopyBtn: getRequiredElement<HTMLButtonElement>("batchBacktestCopyBtn"),
        batchBacktestCopyBenchmarkBtn: getRequiredElement<HTMLButtonElement>("batchBacktestCopyBenchmarkBtn"),
        batchBacktestMineBtn: getRequiredElement<HTMLButtonElement>("batchBacktestMineBtn"),
        batchBacktestCopyMinerBtn: getRequiredElement<HTMLButtonElement>("batchBacktestCopyMinerBtn"),
        batchBacktestAutoRunStability: getRequiredElement<HTMLInputElement>("batchBacktestAutoRunStability"),
        batchBacktestStabilitySubsetSize: getRequiredElement<HTMLInputElement>("batchBacktestStabilitySubsetSize"),
        batchBacktestStabilityReruns: getRequiredElement<HTMLInputElement>("batchBacktestStabilityReruns"),
        batchBacktestStabilitySeed: getRequiredElement<HTMLInputElement>("batchBacktestStabilitySeed"),
        batchBacktestStabilityMineBtn: getRequiredElement<HTMLButtonElement>("batchBacktestStabilityMineBtn"),
        batchBacktestCopyStabilityBtn: getRequiredElement<HTMLButtonElement>("batchBacktestCopyStabilityBtn"),
        batchBacktestOpenScoreUsdBtn: getRequiredElement<HTMLButtonElement>("batchBacktestOpenScoreUsdBtn"),
        batchBacktestCopyOpenScoreUsdBtn: getRequiredElement<HTMLButtonElement>("batchBacktestCopyOpenScoreUsdBtn"),
        batchBacktestOpenScoreUsdSummary: getRequiredElement<HTMLDivElement>("batchBacktestOpenScoreUsdSummary"),
        batchBacktestOpenScoreUsdFrom: getRequiredElement<HTMLInputElement>("batchBacktestOpenScoreUsdFrom"),
        batchBacktestOpenScoreUsdTo: getRequiredElement<HTMLInputElement>("batchBacktestOpenScoreUsdTo"),
        batchBacktestOpenScoreUsdHorizons: getRequiredElement<HTMLInputElement>("batchBacktestOpenScoreUsdHorizons"),
        batchBacktestProgress: getRequiredElement("batchBacktestProgress"),
        batchBacktestProgressFill: getRequiredElement<HTMLDivElement>("batchBacktestProgressFill"),
        batchBacktestProgressText: getRequiredElement<HTMLDivElement>("batchBacktestProgressText"),
        batchBacktestStatus: getRequiredElement<HTMLDivElement>("batchBacktestStatus"),
        batchBacktestSummary: getRequiredElement<HTMLDivElement>("batchBacktestSummary"),
        batchBacktestSummaryGrid: getRequiredElement<HTMLDivElement>("batchBacktestSummaryGrid"),
        batchBacktestMinerSummary: getRequiredElement<HTMLDivElement>("batchBacktestMinerSummary"),
        batchBacktestMinerResults: getRequiredElement<HTMLDivElement>("batchBacktestMinerResults"),
        batchBacktestResults: getRequiredElement<HTMLDivElement>("batchBacktestResults"),
        batchBacktestEmpty: getRequiredElement<HTMLDivElement>("batchBacktestEmpty"),
        batchBacktestSp500TopMeanRunBtn: getRequiredElement<HTMLButtonElement>("batchBacktestSp500TopMeanRunBtn"),
        batchBacktestSp500TopMeanStopBtn: getRequiredElement<HTMLButtonElement>("batchBacktestSp500TopMeanStopBtn"),
        batchBacktestSp500TopMeanHorizons: getRequiredElement<HTMLInputElement>("batchBacktestSp500TopMeanHorizons"),
        batchBacktestSp500TopMeanWorkers: getRequiredElement<HTMLInputElement>("batchBacktestSp500TopMeanWorkers"),
        batchBacktestSp500TopMeanMaxPairs: getRequiredElement<HTMLInputElement>("batchBacktestSp500TopMeanMaxPairs"),
        batchBacktestSp500TopMeanCopyBtn: getRequiredElement<HTMLButtonElement>("batchBacktestSp500TopMeanCopyBtn"),
        batchBacktestSp500TopMeanDownloadBtn: getRequiredElement<HTMLButtonElement>("batchBacktestSp500TopMeanDownloadBtn"),
        batchBacktestSp500TopMeanCopyDiagnosticBtn: getRequiredElement<HTMLButtonElement>("batchBacktestSp500TopMeanCopyDiagnosticBtn"),
        batchBacktestSp500TopMeanCoverageSummary: getRequiredElement<HTMLDivElement>("batchBacktestSp500TopMeanCoverageSummary"),
        batchBacktestSp500TopMeanProgressText: getRequiredElement<HTMLDivElement>("batchBacktestSp500TopMeanProgressText"),
        batchBacktestSp500TopMeanResults: getRequiredElement<HTMLDivElement>("batchBacktestSp500TopMeanResults"),
        batchBacktestSp500TopMeanDiagnostic: getRequiredElement<HTMLPreElement>("batchBacktestSp500TopMeanDiagnostic"),
    };
}

export type BatchBacktestDom = ReturnType<typeof createBatchBacktestDom>;
